select 
UPPER(CONCAT(coalesce(CNTWRK.HASH_FULL_RECORD ::VARCHAR,''),'~','JDAWMSLA1')) as INVTY_CYCLE_CNT_KEY,
'JDAWMS' AS  {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(coalesce(CNTWRK.HASH_FULL_RECORD ::VARCHAR,''),'~','JDAWMSLA1'))) AS  {{var('column_rechashkey')}},
{{var('default_n')}} as {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS  {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS  {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_UPD_DTE')}},
CNTWRK.LOADDTS AS  {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS  {{var('column_verexpirydt')}},
{{var('default_y')}} as {{var('column_currrecflag')}},
{{var('default_n')}} as {{var('column_orprecflag')}},
CNTWRK.LOADDTS AS  {{var('column_z3loddtm')}},
'JDAWMSLA1' as WMS_SCHEMA_NAME,
CNTWRK.PRTNUM as PROD_ID,
CNTWRK.STOLOC as SLOC_ID,
try_to_number(CNTWRK.UNTQTY) as BASE_UNIT_QTY,
case when length(trim(CNTWRK.CNT_USR_ID)) <1 then {{var('default_mapkey')}} when CNTWRK.CNT_USR_ID IS NULL then {{var('default_mapkey')}} else UPPER(CNTWRK.CNT_USR_ID) end as ASGN_USER_ID,
case when length(trim(CNTWRK.CNTTYP)) <1 then {{var('default_mapkey')}} when CNTWRK.CNTTYP IS NULL then {{var('default_mapkey')}} else UPPER(CNTWRK.CNTTYP) end as CYCLE_CNT_CLS_KEY,
CNTWRK.CNTSTS as CNT_STAT_TYP,
CNTWRK.CNTGRP as CNT_GRP_TYP,
TRY_TO_TIMESTAMP(CNTWRK.CNTDTE) AS CYCLE_CNT_BATCH_DTE,
CNTWRK.CNTBAT AS CYCLE_CNT_BATCH_NBR,
CNTWRK.PRT_CLIENT_ID AS CUST_ITEM_GRP_NBR,
case when length(trim(CNTWRK.CNTDEV)) <1 then {{var('default_mapkey')}} when CNTWRK.CNTDEV IS NULL then {{var('default_mapkey')}} else UPPER(CNTWRK.CNTDEV) end as RF_GUN_ID,
try_to_number(CNTWRK.CNTQTY) AS BASE_CNT,
try_to_number(CNTWRK.CATCH_QTY) AS PRE_CNT_CATCH_QTY
from {{source('JDAWMSLA1','CNTWRK')}} CNTWRK