select
UPPER(CONCAT(coalesce(RESERVATIONENTRY.COMPANY::VARCHAR,''),'~',coalesce(RESERVATIONENTRY.ENTRY_NO::VARCHAR,''),'~',coalesce(RESERVATIONENTRY.POSITIVE::VARCHAR,''))) AS INVTY_RSRV_HDR_KEY,
'NAVISIONHY' AS {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(coalesce(RESERVATIONENTRY.COMPANY::VARCHAR,''),'~',coalesce(RESERVATIONENTRY.ENTRY_NO::VARCHAR,''),'~',coalesce(RESERVATIONENTRY.POSITIVE::VARCHAR,'')))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
RESERVATIONENTRY.LOADDTS AS {{var('column_z3loddtm')}},
RESERVATIONENTRY.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},


case when length(trim(UPPER((RESERVATIONENTRY.ITEM_NO)))) <1 then {{var('default_mapkey')}} when UPPER(RESERVATIONENTRY.ITEM_NO)
IS NULL then {{var('default_mapkey')}} else UPPER(RESERVATIONENTRY.ITEM_NO) end AS RESERVED_PROD_KEY,

case when length(trim(UPPER((RESERVATIONENTRY.LOCATION_CODE)))) <1 then {{var('default_mapkey')}} when UPPER(RESERVATIONENTRY.LOCATION_CODE)
IS NULL then {{var('default_mapkey')}} else UPPER(RESERVATIONENTRY.LOCATION_CODE) end AS LOC_KEY,

case when length(trim(UPPER((RESERVATIONENTRY.QTY_PER_UNIT_OF_MEASURE)))) <1 then {{var('default_mapkey')}} when UPPER(RESERVATIONENTRY.QTY_PER_UNIT_OF_MEASURE)
IS NULL then {{var('default_mapkey')}} else UPPER(RESERVATIONENTRY.QTY_PER_UNIT_OF_MEASURE) end AS UOM_KEY,


case when length(trim(UPPER((RESERVATIONENTRY.SOURCE_TYPE)))) <1 then {{var('default_mapkey')}} when UPPER(RESERVATIONENTRY.SOURCE_TYPE)
IS NULL then {{var('default_mapkey')}} else UPPER(RESERVATIONENTRY.SOURCE_TYPE) end AS REL_SRC_TYP_LKEY,

case when length(trim(UPPER((RESERVATIONENTRY.SOURCE_SUBTYPE)))) <1 then {{var('default_mapkey')}} when UPPER(RESERVATIONENTRY.SOURCE_SUBTYPE)
IS NULL then {{var('default_mapkey')}} else UPPER(RESERVATIONENTRY.SOURCE_SUBTYPE) end AS REL_SRC_STYP_LKEY,



case when UPPER(RESERVATIONENTRY.POSITIVE) in ('NO','FALSE','0') or UPPER(RESERVATIONENTRY.POSITIVE) is null
or length(TRIM(RESERVATIONENTRY.POSITIVE))<1 then 'N' when UPPER(RESERVATIONENTRY.POSITIVE) in ('YES','TRUE','1')
then 'Y' else 'U' end as SUPPLY_DMD_FLAG,

case when UPPER(RESERVATIONENTRY.PLANNING_FLEXIBILITY) in ('NO','FALSE','0') or UPPER(RESERVATIONENTRY.PLANNING_FLEXIBILITY) is null
or length(TRIM(RESERVATIONENTRY.PLANNING_FLEXIBILITY))<1 then 'N' when UPPER(RESERVATIONENTRY.PLANNING_FLEXIBILITY) in ('YES','TRUE','1')
then 'Y' else 'U' end as SUPPLY_PLNG_FLEXIBILITY_FLAG,

case when UPPER(RESERVATIONENTRY.DISALLOW_CANCELLATION) in ('NO','FALSE','0') or UPPER(RESERVATIONENTRY.DISALLOW_CANCELLATION) is null
or length(TRIM(RESERVATIONENTRY.DISALLOW_CANCELLATION))<1 then 'N' when UPPER(RESERVATIONENTRY.DISALLOW_CANCELLATION) in ('YES','TRUE','1')
then 'Y' else 'U' end as DISALLOW_RSRV_CNCL_FLAG,

TRY_TO_TIMESTAMP(RESERVATIONENTRY.EXPECTED_RECEIPT_DATE,'YYYY-MM-DD HH:MI:SS.FF') AS EXPCT_RCPT_DTE,
TRY_TO_TIMESTAMP(RESERVATIONENTRY.SHIPMENT_DATE,'YYYY-MM-DD HH:MI:SS.FF') AS EXPCT_SHIP_DTE,
TRY_TO_TIMESTAMP(RESERVATIONENTRY.WARRANTY_DATE,'YYYY-MM-DD HH:MI:SS.FF') AS WRNTY_DTE,
TRY_TO_TIMESTAMP(RESERVATIONENTRY.EXPIRATION_DATE,'YYYY-MM-DD HH:MI:SS.FF') AS LOT_EXPR_DTE,
TRY_TO_TIMESTAMP(RESERVATIONENTRY.NEW_EXPIRATION_DATE,'YYYY-MM-DD HH:MI:SS.FF') AS NEW_EXPR_DTE,

RESERVATIONENTRY.QUANTITY__BASE_ as RESERVED_PROD_QTY,
RESERVATIONENTRY.RESERVATION_STATUS AS PROD_RSRV_STAT_TYP,
RESERVATIONENTRY.TRANSFERRED_FROM_ENTRY_NO AS REF_ENTR_NBR,
RESERVATIONENTRY.SOURCE_BATCH_NAME AS JRNL_BATCH_NAME,
RESERVATIONENTRY.SOURCE_PROD_ORDER_LINE AS PRODTN_ORD_LN_NBR,
RESERVATIONENTRY.SOURCE_REF_NO AS REF_LN_NBR,
RESERVATIONENTRY.ITEM_LEDGER_ENTRY_NO AS PROD_LEDGER_ENTR_NBR,
RESERVATIONENTRY.QUANTITY AS PROD_RESERVED_QTY,
RESERVATIONENTRY.SUPPRESSED_ACTION_MSG AS SUPPRESSED_ACTN_TEXT,
RESERVATIONENTRY.QTY_TO_HANDLE__BASE_ AS PRTL_QTY,
RESERVATIONENTRY.QTY_TO_INVOICE__BASE_ AS PRTL_INVC_QTY,
RESERVATIONENTRY.QUANTITY_INVOICED__BASE_ AS INVC_QTY,
RESERVATIONENTRY.APPL_FROM_ITEM_ENTRY AS PROD_LEDGER_NBR,
RESERVATIONENTRY.CORRECTION AS CRCTD_PROD_LEDGER_NBR,
RESERVATIONENTRY.ITEM_TRACKING AS PROD_TRK_NBR,
RESERVATIONENTRY.ENTRY_NO AS RSRV_ENTR_NBR,
RESERVATIONENTRY.APPL_TO_ITEM_ENTRY AS APPLIED_LEDGER_ENTR_NBR,
RESERVATIONENTRY.SOURCE_ID AS LN_NBR,
RESERVATIONENTRY.DESCRIPTION AS PROD_DESC,
RESERVATIONENTRY.SERIAL_NO AS PROD_SERL_NBR

FROM {{source('NAVISIONHY','RESERVATIONENTRY')}} RESERVATIONENTRY