select 
UPPER(CONCAT(COALESCE(PRODUCTIONBOMHEADER.COMPANY::VARCHAR,''),'~',Coalesce((PRODUCTIONBOMHEADER.NO)::varchar,''))) AS PROD_BOM_PRNT_KEY,
'NAVISIONHY' AS  {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(COALESCE(PRODUCTIONBOMHEADER.COMPANY::VARCHAR,''),'~',Coalesce((PRODUCTIONBOMHEADER.NO)::varchar,'')))) AS  {{var('column_rechashkey')}},
{{var('default_n')}} as {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS  {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS  {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_UPD_DTE')}},
PRODUCTIONBOMHEADER.LOADDTS AS  {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS  {{var('column_verexpirydt')}},
{{var('default_y')}} as {{var('column_currrecflag')}},
{{var('default_n')}} as {{var('column_orprecflag')}},
PRODUCTIONBOMHEADER.LOADDTS AS  {{var('column_z3loddtm')}},
case when length(trim(PRODUCTIONBOMHEADER.SOURCE_COMPANY)) <1 then {{var('default_mapkey')}} when PRODUCTIONBOMHEADER.SOURCE_COMPANY IS NULL then {{var('default_mapkey')}} else (PRODUCTIONBOMHEADER.SOURCE_COMPANY) end as SRC_CO_KEY,
case when length(trim(PRODUCTIONBOMHEADER.UNIT_OF_MEASURE_CODE)) <1 then {{var('default_mapkey')}} when PRODUCTIONBOMHEADER.UNIT_OF_MEASURE_CODE IS NULL then {{var('default_mapkey')}} else (PRODUCTIONBOMHEADER.UNIT_OF_MEASURE_CODE) end as BASE_UOM_KEY,
PRODUCTIONBOMHEADER.Description AS BOM_HDR_DESC,
PRODUCTIONBOMHEADER.Description_2 AS BOM_HDR_ADDTN_DESC,
case when UPPER(PRODUCTIONBOMHEADER.IC_ITEM_BOM)=1 then 'Y' else 'N' end INTER_BOM_FLAG,
TRY_TO_TIMESTAMP(PRODUCTIONBOMHEADER.LAST_SYNC_DATE,'YYYY-MM-DD HH:MI:SS.FF') AS LAST_SYNCHRONIZE_DTE,
case when length(trim(PRODUCTIONBOMHEADER.Status)) <1 then {{var('default_mapkey')}} when PRODUCTIONBOMHEADER.Status IS NULL then {{var('default_mapkey')}} else (PRODUCTIONBOMHEADER.Status) end as BOM_STAT_LKEY,
PRODUCTIONBOMHEADER.timestamp AS BOM_HDR_ENTR_DTE,
case when length(trim(PRODUCTIONBOMHEADER.No)) <1 then {{var('default_mapkey')}} when PRODUCTIONBOMHEADER.No IS NULL then {{var('default_mapkey')}} else (PRODUCTIONBOMHEADER.No) end as BOM_CTGY_LKEY,
PRODUCTIONBOMHEADER.LOW_LEVEL_CODE AS PROD_NODE_NBR,
PRODUCTIONBOMHEADER.SEARCH_NAME AS SRCH_PROD_NAME,
PRODUCTIONBOMHEADER.VERSION_NOS AS PROD_BOM_VER_NBR
from {{source('NAVISIONHY','PRODUCTIONBOMHEADER')}} PRODUCTIONBOMHEADER