SELECT
UPPER(CONCAT(COALESCE(F3002.IXKIT::VARCHAR,''),'~',COALESCE(F3002.IXMMCU::VARCHAR,''),'~',COALESCE(F3002.IXTBM::VARCHAR,''),'~',COALESCE(F3002.IXBQTY::VARCHAR,''),'~',COALESCE(F3002.IXCPNB::VARCHAR,''),'~',COALESCE(F3002.IXSBNT::VARCHAR,''),'~',COALESCE(F3002.IXCOBY::VARCHAR,''))) AS PROD_BOM_CMPNT_KEY,
'JDEEF' AS {{var('column_srcsyskey')}},
dateadd(day,case when length(F3002.IXUPMJ)=6 then to_number(substring (F3002.IXUPMJ,4,3)-1) else 0 end-1,dateadd(year,to_number(substring (F3002.IXUPMJ,1,3))-70,'0')) AS {{var('column_SRC_RCRD_UPD_DTE')}},
F3002.IXUSER AS {{var('column_SRC_RCRD_UPD_USERID')}},
MD5(UPPER(CONCAT(COALESCE(F3002.IXKIT::VARCHAR,''),'~',COALESCE(F3002.IXMMCU::VARCHAR,''),'~',COALESCE(F3002.IXTBM::VARCHAR,''),'~',COALESCE(F3002.IXBQTY::VARCHAR,''),'~',COALESCE(F3002.IXCPNB::VARCHAR,''),'~',COALESCE(F3002.IXSBNT::VARCHAR,''),'~',COALESCE(F3002.IXCOBY::VARCHAR,'')))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
F3002.LOADDTS AS {{var('column_z3loddtm')}},
F3002.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},
case when length(trim(F3002.IXMMCU))<1 then {{var('default_mapkey')}} when F3002.IXMMCU IS NULL then  {{var('default_mapkey')}} else (F3002.IXMMCU) end AS BUS_UNIT_KEY,
case when length(trim(F3002.IXLNTY))<1 then {{var('default_mapkey')}} when F3002.IXLNTY IS NULL then  {{var('default_mapkey')}} else (F3002.IXLNTY) end AS PROD_LN_TYP_LKEY,
case when length(trim(F3002.IXKITL))<1 then {{var('default_mapkey')}} when F3002.IXKITL IS NULL then  {{var('default_mapkey')}} else (F3002.IXKITL) end AS PROD_KEY,
F3002.IXKITA AS BOM_ALT_KIT_NBR,
F3002.IXKIT AS ITRL_PROD_NBR,
F3002.IXQNTY AS BASE_QTY,
case when length(trim(F3002.IXUM))<1 then {{var('default_mapkey')}} when F3002.IXUM IS NULL then  {{var('default_mapkey')}} else (F3002.IXUM) end AS BASE_UOM_KEY,
dateadd(day,case when length(F3002.IXEFFF)=6 then to_number(substring (F3002.IXEFFF,4,3)-1) else 0 end-1,dateadd(year,to_number(substring (F3002.IXEFFF,1,3))-70,'0')) AS BOM_RELATION_START_DTE,
dateadd(day,case when length(F3002.IXEFFT)=6 then to_number(substring (F3002.IXEFFT,4,3)-1) else 0 end-1,dateadd(year,to_number(substring (F3002.IXEFFT,1,3))-70,'0')) AS BOM_RELATION_END_DTE,
F3002.IXLITM AS PROD_BOM_MSTR_FILE_NBR,
case when length(trim(F3002.IXTBM))<1 then {{var('default_mapkey')}} when F3002.IXTBM IS NULL then  {{var('default_mapkey')}} else (F3002.IXTBM) end AS BOM_KEY,
F3002.IXITC AS ISS_CD_TYP,
TRY_TO_NUMBER(F3002.IXFORQ) AS VARBL_QTY,
F3002.IXBQTY AS BATCH_UNIT_QTY,
F3002.IXSBNT AS SUBST_ITEM_SEQ_NBR,
CASE WHEN F3002.IXPRTA = 'Y' THEN 'Y' ELSE 'N' END  AS PARTIALS_ALLOW_FLAG,
F3002.IXFTRC AS REQUIRED,
TRY_TO_NUMBER(F3002.IXOPTK) AS OPTIONAL_PROD,
{{var('default_key')}} AS BOM_CTGY_LKEY,
{{var('default_key')}} AS RESIDING_LOC_KEY,
{{var('default_key')}} AS ISS_PLANT_LOC_KEY,
{{var('default_key')}} AS CMPNT_UOM_KEY,
{{var('default_key')}} AS BOM_CMPNT_ITEM_CTGY_LKEY,
{{var('default_key')}} AS CLS_TYP_LKEY,
{{var('default_key')}} AS DOC_TYP_LKEY,
{{var('default_key')}} AS PROD_GRP_LKEY,
{{var('default_key')}} AS PROD_BOM_PRNT_KEY,
--{{var('default_key')}} AS OPTIONAL_PROD_BOM_CMPNT_KEY,
-- {{var('default_key')}} AS AUXILIARY_UOM_KEY,
-- {{var('default_key')}} AS PRNT_PROD_KEY,
{{var('default_key')}} AS CMPNT_PROD_KEY,
{{var('default_key')}} AS QTY_PER_TYP_LKEY,
{{var('default_key')}} AS PROD_GRP_TYP_LKEY,
{{var('default_key')}} AS CMDTY_CD_LKEY,
{{var('default_key')}} AS JOINT_PROD_TYP_LKEY,
{{var('default_key')}} AS PROD_EXPLD_TYP_LKEY,
--{{var('default_key')}} AS PUR_ORG_KEY,
{{var('default_key')}} AS BOM_PROCUR_TYP_LKEY,
{{var('default_key')}} AS LANG_FMT_TYP_LKEY,
--{{var('default_key')}} AS LEADTIME_OFFSET_UOM_KEY,
{{var('default_key')}} AS PROD_OBJ_CTGY_LKEY,
{{var('default_key')}} AS PRODTN_SUPPLY_AREA_LKEY,
{{var('default_key')}} AS PROD_COST_RELVNT_LKEY,
{{var('default_key')}} AS CRNCY_KEY,
{{var('default_key')}} AS ALT_PROD_STRAT_LKEY,
--{{var('default_key')}} AS ALT_DISPLAY_FMT_KEY,
{{var('default_key')}} AS PROD_BOM_CTGY_LKEY,
--{{var('default_key')}} AS FORMULA_KEY,
{{var('default_key')}} AS PROD_BOM_REF_POINT_LKEY,
{{var('default_key')}} AS CMPNT_CNSMPTN_DIST_LKEY,
{{var('default_key')}} AS PRODTN_BOM_LKEY,
{{var('default_key')}} AS PROD_CMPNT_TYP_LKEY,
{{var('default_key')}} AS LAST_MTNC_USER_KEY,
{{var('default_key')}} AS PROD_CLS_LKEY,
{{var('default_flag')}} AS FIXED_QTY_FLAG,
{{var('default_flag')}} AS REQ_CMPNT_FLAG,
{{var('default_flag')}} AS PRODTN_RELVNT_FLAG,
{{var('default_flag')}} AS FIXED_BATCH_SZ_FLAG,
{{var('default_flag')}} AS BY_PROD_FLAG,
{{var('default_flag')}} AS IS_CMPNT_ITEM_REQ_FLAG,
{{var('default_flag')}} AS CRTCL_CMPNT_ASSEMBLY_STAT_FLAG,
{{var('default_flag')}} AS ALE_STAT_FLAG,
{{var('default_flag')}} AS PROD_FOLLOW_UP_FLAG,
{{var('default_flag')}} AS BOM_PROD_DEL_FLAG,
{{var('default_flag')}} AS NEW_SCRAP_INDCTR_FLAG,
{{var('default_flag')}} AS RECURSIVE_BOM_FLAG,
{{var('default_flag')}} AS RECURSIVENESS_CHK_FLAG,
{{var('default_flag')}} AS PROD_PLANT_MTNC_FLAG,
{{var('default_flag')}} AS ENGNR_RELVNT_PROD_FLAG,
{{var('default_flag')}} AS BULK_MATL_FLAG,
{{var('default_flag')}} AS SUB_PROD_BOM_EXIST_FLAG,
{{var('default_flag')}} AS CMPNT_PRESENT_IN_MULT_ALT_FLAG,
{{var('default_flag')}} AS ALT_PROD_FLAG,
{{var('default_flag')}} AS CAD_FLAG,
{{var('default_flag')}} AS MULT_SELECTION_ALLOW_FLAG,
{{var('default_flag')}} AS INSTANCE_FLAG,
{{var('default_flag')}} AS SUB_PROD_FLAG,
{{var('default_flag')}} AS PROD_ORIG_CONFIGURATION_FLAG,
{{var('default_flag')}} AS PLANT_MTNC_ASSEMBLY_FLAG,
{{var('default_flag')}} AS PROD_BOM_RESTRICTIONS_FLAG,
{{var('default_flag')}} AS AUTO_CONFIGURATION_DISPLAY_FLAG,
{{var('default_flag')}} AS CONFIGURATION_EDITOR_DISPLAY_FLAG,
{{var('default_flag')}} AS SINGLE_LVL_CONFIGURATION_DISPLAY_FLAG,
{{var('default_flag')}} AS REF_DESIGNATORS_FLAG,
F3002.IXCPNB AS CMPNT_SEQ_NBR
FROM {{source('JDEEF','F3002')}} F3002