select 
UPPER(CONCAT(COALESCE(F4141.PJCYNO::varchar,''),'~',COALESCE(F4141.PJLITM::varchar,''),'~',COALESCE(F4141.PJMCU::varchar,''),'~',COALESCE(F4141.PJLOCN::varchar,''),'~',COALESCE(F4141.PJLOTN::varchar,''),'~',COALESCE(F4141.PJSTUN::varchar,''),'~')) as INVTY_CYCLE_CNT_KEY,
'JDEEF' AS  {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(COALESCE(F4141.PJCYNO::varchar,''),'~',COALESCE(F4141.PJLITM::varchar,''),'~',COALESCE(F4141.PJMCU::varchar,''),'~',COALESCE(F4141.PJLOCN::varchar,''),'~',COALESCE(F4141.PJLOTN::varchar,''),'~',COALESCE(F4141.PJSTUN::varchar,''),'~'))) AS  {{var('column_rechashkey')}},
{{var('default_n')}} as {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS  {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS  {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_UPD_DTE')}},
F4141.LOADDTS AS  {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS  {{var('column_verexpirydt')}},
{{var('default_y')}} as {{var('column_currrecflag')}},
{{var('default_n')}} as {{var('column_orprecflag')}},
F4141.LOADDTS AS  {{var('column_z3loddtm')}},
case when length(trim(F4141.PJMCU)) <1 then {{var('default_mapkey')}} when F4141.PJMCU IS NULL then {{var('default_mapkey')}} else (F4141.PJMCU) end as BUS_UNIT_KEY,
case when length(trim(F4141.PJLOCN)) <1 then {{var('default_mapkey')}} when F4141.PJLOCN IS NULL then {{var('default_mapkey')}} else (F4141.PJLOCN) end as LOC_KEY,
case when length(trim(F4141.PJCNTB)) <1 then {{var('default_mapkey')}} when F4141.PJCNTB IS NULL then {{var('default_mapkey')}} else (F4141.PJCNTB) end as ASGN_USER_KEY,
case when length(trim(F4141.PJGLPT)) <1 then {{var('default_mapkey')}} when F4141.PJGLPT IS NULL then {{var('default_mapkey')}} else (F4141.PJGLPT) end as GL_CLS_CD_LKEY,
F4141.PJCNTJ AS CYCLE_CNT_ACT_DTE,
F4141.PJUPMJ AS CYCLE_CNT_SYS_UPD_DTE,
F4141.PJCYNO AS CYCLE_CNT_ASGN_NBR,
F4141.PJCCCD AS CYCLE_CNT_NBR,
case when length(trim(F4141.PJITM)) <1 then {{var('default_mapkey')}} when F4141.PJITM IS NULL then {{var('default_mapkey')}} else (F4141.PJITM) end as PROD_KEY,
F4141.PJLITM AS USER_DEFINED_PROD_NBR,
F4141.PJAITM AS BOM_ALT_PROD_NBR,
F4141.PJLOTN AS LOT_SERL_NBR,
F4141.PJSRP1 AS PROD_FAMILY_SLS_NBR,
case when length(trim(F4141.PJSRP2)) <1 then {{var('default_mapkey')}} when F4141.PJSRP2 IS NULL then {{var('default_mapkey')}} else (F4141.PJSRP2) end as FAMILY_SECT_KEY,
F4141.PJSRP3 AS SLS_CTGY_3_NBR,
F4141.PJSRP4 AS SLS_CTGY_4_NBR,
F4141.PJSRP5 AS SLS_CTGY_5_NBR,
F4141.PJAISL AS INVTY_AISLE_NBR,
F4141.PJBIN AS INVTY_BIN_NBR,
F4141.PJPID AS PGM_NBR,
F4141.PJJOBN AS WORK_STATION_NBR,
F4141.PJTQCT AS COUNTED_PROD_QTY,
F4141.PJTQOH AS CYCLE_CNT_START_ON_HAND_QTY,
F4141.PJTAOH AS CYCLE_CNT_START_ON_HAND_AMT,
F4141.PJTACT AS COUNTED_PROD_AMT,
F4141.PJUNCS AS UNIT_PROD_COST
F4141.PJLOT1 AS MEMO_LOT_1_TEXT, 
F4141.PJLOT2 AS MEMO_LOT_2_TEXT,
F4141.PJLOT3 AS MEMO_LOT_3_TEXT 
from {{source('JDEEF','F4141')}} F4141 