version: 2

sources:
 
  - name: WMSBREWSTER
    schema: WMSBREWSTER
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: LOCATOR
        identifier: VW_LOCATOR
      - name: CYCLE_COUNT
        identifier: VW_CYCLE_COUNT
      - name: INVENTORY
        identifier: VW_INVENTORY
      - name: ITEM
        identifier: VW_ITEM
      - name: LOCATION
        identifier: VW_LOCATION

  - name: WMSEASTLONGMEADOW
    schema: WMSEASTLONGMEADOW
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: LOCATOR
        identifier: VW_LOCATOR
      - name: INVENTORY
        identifier: VW_INVENTORY
      - name: ITEM
        identifier: VW_ITEM
      - name: LOCATION
        identifier: VW_LOCATION
      - name: CYCLE_COUNT
        identifier: VW_CYCLE_COUNT

  - name: WMSFONTANA
    schema: WMSFONTANA
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: LOCATOR
        identifier: VW_LOCATOR
      - name: INVENTORY
        identifier: VW_INVENTORY
      - name: ITEM
        identifier: VW_ITEM
      - name: LOCATION
        identifier: VW_LOCATION  
      - name: CYCLE_COUNT
        identifier: VW_CYCLE_COUNT     
    
  - name: WMSFORTMILL
    schema: WMSFORTMILL
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: LOCATOR
        identifier: VW_LOCATOR  
      - name: INVENTORY
        identifier: VW_INVENTORY
      - name: ITEM
        identifier: VW_ITEM
      - name: LOCATION
        identifier: VW_LOCATION     
      - name: CYCLE_COUNT
        identifier: VW_CYCLE_COUNT     

  - name: WMSJACKSON
    schema: WMSJACKSON
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: LOCATOR
        identifier: VW_LOCATOR
      - name: INVENTORY
        identifier: VW_INVENTORY
      - name: ITEM
        identifier: VW_ITEM
      - name: LOCATION
        identifier: VW_LOCATION     
      - name: CYCLE_COUNT
        identifier: VW_CYCLE_COUNT   

  - name: WMSKANNAPOLIS
    schema: WMSKANNAPOLIS
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: LOCATOR
        identifier: VW_LOCATOR
      - name: INVENTORY
        identifier: VW_INVENTORY
      - name: ITEM
        identifier: VW_ITEM
      - name: LOCATION
        identifier: VW_LOCATION    
      - name: CYCLE_COUNT
        identifier: VW_CYCLE_COUNT    

  - name: WMSMILLCREEK
    schema: WMSMILLCREEK
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: LOCATOR
        identifier: VW_LOCATOR
      - name: INVENTORY
        identifier: VW_INVENTORY
      - name: ITEM
        identifier: VW_ITEM
      - name: LOCATION
        identifier: VW_LOCATION    
      - name: CYCLE_COUNT
        identifier: VW_CYCLE_COUNT    

  - name: WMSNORTHLAKE
    schema: WMSNORTHLAKE
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: LOCATOR
        identifier: VW_LOCATOR
      - name: INVENTORY
        identifier: VW_INVENTORY
      - name: ITEM
        identifier: VW_ITEM
      - name: LOCATION
        identifier: VW_LOCATION   
      - name: CYCLE_COUNT
        identifier: VW_CYCLE_COUNT     

  - name: WMSWEB
    schema: WMSWEB
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: LOCATOR
        identifier: VW_LOCATOR
      - name: INVENTORY
        identifier: VW_INVENTORY
      - name: ITEM
        identifier: VW_ITEM
      - name: LOCATION
        identifier: VW_LOCATION
      - name: CYCLE_COUNT
        identifier: VW_CYCLE_COUNT
