select
UPPER(CONCAT(coalesce(PRODUCTIONMETHOD.PRODUCTIONMETHOD::VARCHAR,''),'~',coalesce(PRODUCTIONMETHOD.ITEM::VARCHAR,''),'~' ,coalesce(PRODUCTIONMETHOD.LOC::VARCHAR,''))) AS PRODTN_MTHD_KEY,
'JDAEDW' AS {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(coalesce(PRODUCTIONMETHOD.PRODUCTIONMETHOD::VARCHAR,''),'~',coalesce(PRODUCTIONMETHOD.ITEM::VARCHAR,''),'~' ,coalesce(PRODUCTIONMETHOD.LOC::VARCHAR,'')))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
PRODUCTIONMETHOD.LOADDTS AS {{var('column_z3loddtm')}},
PRODUCTIONMETHOD.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},

PRODUCTIONMETHOD.FINISHCAL AS FINISHED_CLNDR_TYP,

case when length(trim(UPPER((PRODUCTIONMETHOD.ITEM)))) <1 then {{var('default_mapkey')}} when UPPER(PRODUCTIONMETHOD.ITEM)
IS NULL then {{var('default_mapkey')}} else UPPER(PRODUCTIONMETHOD.ITEM) end AS PROD_KEY,

case when length(trim(UPPER((PRODUCTIONMETHOD.LOC)))) <1 then {{var('default_mapkey')}} when UPPER(PRODUCTIONMETHOD.LOC)
IS NULL then {{var('default_mapkey')}} else UPPER(PRODUCTIONMETHOD.LOC) end AS LOC_KEY,

PRODUCTIONMETHOD.ENABLESW as PRODTN_MTHD_OPTIMIZER,
PRODUCTIONMETHOD.SPLITORDERSW as INVTY_SPLIT,
PRODUCTIONMETHOD.LEADTIMECAL AS SUPPLY_LEADTIME_DUR,
PRODUCTIONMETHOD.LOADOPT AS LOD_OPT,
PRODUCTIONMETHOD.OFFSETTYPE AS LOD_OFFSET_TYP,

PRODUCTIONMETHOD.BOMNUM AS BOM_NBR,
PRODUCTIONMETHOD.LEADTIME AS PRODTN_LEADTIME_DUR,
PRODUCTIONMETHOD.MAXFINDUR AS MAX_FINISH_DUR_DY_CNT,
PRODUCTIONMETHOD.PRIORITY AS PRYRT_NBR,
PRODUCTIONMETHOD.U_IO_PREV_BOMNUM AS PREV_BOM_NBR,
PRODUCTIONMETHOD.U_IO_PREV_LEADTIME AS PREV_LEADTIME_DY_CNT,
PRODUCTIONMETHOD.INCQTY AS INCREMENTAL_QTY,
PRODUCTIONMETHOD.MAXQTY AS LOT_MAX_QTY,
PRODUCTIONMETHOD.MAXSTARTDUR AS MAX_DUR_DY_CNT,
PRODUCTIONMETHOD.MINQTY AS MIN_PLAN_QTY,
PRODUCTIONMETHOD.PRODUCTIONMETHOD AS PRODTN_MTHD_NAME,
PRODUCTIONMETHOD.DESCR AS PRODTN_MTHD_DESC,
PRODUCTIONMETHOD.MAXLEADTIME AS MAX_LEADTIME_DY_CNT,
PRODUCTIONMETHOD.MINLEADTIME AS MIN_LEADTIME_DY_CNT,
PRODUCTIONMETHOD.SPLITFACTOR AS INVTY_SPLIT_FACTOR,
PRODUCTIONMETHOD.WORKSCOPE AS WORK_SCOPE_DESC,
PRODUCTIONMETHOD.YIELDQTY AS YIELD_QTY,

--TRY_TO_DATE(PRODUCTIONMETHOD.DISC,'YYYYMMDD') AS PRODTN_EFF_END_DTE,
--TRY_TO_DATE(PRODUCTIONMETHOD.EFF,'YYYYMMDD') AS PRODTN_EFF_START_DTE,
--TRY_TO_DATE(PRODUCTIONMETHOD.NONEWSUPPLYDATE,'YYYYMMDD') AS NO_NEW_SUPPLY_DTE,

PRODUCTIONMETHOD.DISC AS PRODTN_EFF_END_DTE,
PRODUCTIONMETHOD.EFF AS PRODTN_EFF_START_DTE,
PRODUCTIONMETHOD.NONEWSUPPLYDATE AS NO_NEW_SUPPLY_DTE,

PRODUCTIONMETHOD.PRODFAMILY AS PRODTN_FAMILY ,
PRODUCTIONMETHOD.PRODGROUP AS PROD_GRP ,
PRODUCTIONMETHOD.CAMPAIGNPRIORITY AS CAMPAIGN_PRYRT_NBR ,
PRODUCTIONMETHOD.LEADTIMESTDDEV AS STD_DEVN_LEADTIME_DUR ,
PRODUCTIONMETHOD.REPLENDUR AS REPLENISH_DUR_DY_CNT ,
PRODUCTIONMETHOD.CAMPAIGNMINQTY AS CAMPAIGN_MIN_QTY, 
PRODUCTIONMETHOD.PRODCOST AS PRODTN_COST, 
PRODUCTIONMETHOD.YIELDFACTOR AS YIELD_FACTOR 

FROM {{source('JDAEDW','PRODUCTIONMETHOD')}} PRODUCTIONMETHOD