select
UPPER(CONCAT(coalesce(PRICEPROFILEVAL.PRICEPROFILENAME ::VARCHAR,''),'~',coalesce(PRICEPROFILEVAL.STARTDATE ::VARCHAR,''))) AS PRC_PRFL_KEY,
'JDAEDW' AS {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(coalesce(PRICEPROFILEVAL.PRICEPROFILENAME::VARCHAR,''),'~',coalesce(PRICEPROFILEVAL.STARTDATE::VARCHAR,'')))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
PRICEPROFILEVAL.LOADDTS AS {{var('column_z3loddtm')}},
PRICEPROFILEVAL.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},

PRICEPROFILEVAL.PRICEPROFILENAME AS PRC_PRFL_NAME,

--TRY_TO_DATE(PRICEPROFILEVAL.STARTDATE,'YYYYMMDD') AS PRC_PRFL_EFF_DTE,
--TRY_TO_DATE(PRICEPROFILEVAL.ENDDATE,'YYYYMMDD') AS PRC_PRFL_EXPR_DTE,
PRICEPROFILEVAL.STARTDATE AS PRC_PRFL_EFF_DTE,
PRICEPROFILEVAL.ENDDATE AS PRC_PRFL_EXPR_DTE,

PRICEPROFILEVAL.VALUE AS PRC_PRFL_BCRNCY_AMT


FROM {{source('JDAEDW','PRICEPROFILEVAL')}} PRICEPROFILEVAL