select 
UPPER(CONCAT(coalesce(CNTHST.CNTHST_ID ::VARCHAR,''),'~','JDAWMSASIA')) as INVTY_CYCLE_CNT_KEY,
'JDAWMS' AS  {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(coalesce(CNTHST.CNTHST_ID ::VARCHAR,''),'~','JDAWMSASIA'))) AS  {{var('column_rechashkey')}},
{{var('default_n')}} as {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS  {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS  {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_UPD_DTE')}},
CNTHST.LOADDTS AS  {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS  {{var('column_verexpirydt')}},
{{var('default_y')}} as {{var('column_currrecflag')}},
{{var('default_n')}} as {{var('column_orprecflag')}},
CNTHST.LOADDTS AS  {{var('column_z3loddtm')}},
'JDAWMSASIA' as WMS_SCHEMA_NAME,
case when length(trim(CNTHST.CRNCY_CODE)) <1 then {{var('default_mapkey')}} when CNTHST.CRNCY_CODE IS NULL then {{var('default_mapkey')}} else UPPER(CNTHST.CRNCY_CODE) end as CRNCY_CD,
TRY_TO_TIMESTAMP(CNTHST.TRNDTE) AS CNT_CMPLT_DTE,
CNTHST.GENCOD AS CYCLE_CNT_NBR,
case when UPPER(CNTHST.CATCH_QTY) ='NULL' then null else CNTHST.CATCH_QTY end AS CATCH_QTY,
TRY_TO_TIMESTAMP(CNTHST.CNTDTE) AS CYCLE_CNT_DTE,
to_number(case when UPPER(CNTHST.CNTQTY) ='NULL' then null else CNTHST.CNTQTY end) AS COUNTED_PROD_QTY,
case when UPPER(CNTHST.UNTCST)='NULL' then null else CNTHST.UNTCST end AS PROD_UNIT_COST,
to_number(case when UPPER(CNTHST.UNTQTY)='NULL' then null else CNTHST.UNTQTY end) as BASE_UNIT_QTY,
CNTHST.CNTMOD AS CNT_MODE_NAME,
CNTHST.PRT_CLIENT_ID AS CUST_ITEM_GRP_NBR,
CNTHST.CNTBAT AS CYCLE_CNT_BATCH_NBR,
case when length(trim(CNTHST.CNTTYP)) <1 then {{var('default_mapkey')}} when CNTHST.CNTTYP IS NULL then {{var('default_mapkey')}} else UPPER(CNTHST.CNTTYP) end as CYCLE_CNT_CLS_KEY,
CNTHST.PRTNUM as PROD_ID,
CNTHST.STOLOC as SLOC_ID,
CNTHST.CNTHST_ID AS CNT_HIST_NBR
from {{source('JDAWMSASIA','CNTHST')}} CNTHST 