SELECT DISTINCT * FROM
(
SELECT 'TRNITEM' AS SRCTBLNAME,
'SLIES' AS SYSTEMNAME,
'EDW_WAREHOUSE_TRANSFER_ORDER_LINE' AS TBLNAME,
'WHSE_TRNSFR_ORD_LN_KEY' AS DEST_CHANGE_KEY,
'TRNITEM_CHANGES' AS SOURCE_CHANGE_TBL,
'TRN_NUM~SITE_REF' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
UNION ALL

SELECT 'ITEMLOC' AS SRCTBLNAME,
'SLIES' AS SYSTEMNAME,
'EDW_INVENTORY_ON_HAND_SNAPSHOT' AS TBLNAME,
'INVTY_ON_HAND_SNAPSHOT_KEY' AS DEST_CHANGE_KEY,
'ITEMLOC_CHANGES' AS SOURCE_CHANGE_TBL,
'LOC~WHSE~ITEM~SITE_REF' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'TRANSFER' AS SRCTBLNAME,
'SLIES' AS SYSTEMNAME,
'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER' AS TBLNAME,
'WHSE_TRNSFR_ORD_HDR_KEY' AS DEST_CHANGE_KEY,
'TRANSFER_CHANGES' AS SOURCE_CHANGE_TBL,
'SITE_REF~trn_num' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'matltran' AS SRCTBLNAME,
'SLIES' AS SYSTEMNAME,
'EDW_INVENTORY_MOVEMENT_LINE' AS TBLNAME,
'INVTY_MVMNT_LN_KEY,' AS DEST_CHANGE_KEY,
'matltran_CHANGES' AS SOURCE_CHANGE_TBL,
'site_ref~trans_num' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'ITEMWHSE' AS SRCTBLNAME,
'SLIES' AS SYSTEMNAME,
'EDW_INVENTORY_PHYSICAL_COUNT' AS TBLNAME,
'PHY_INVTY_KEY' AS DEST_CHANGE_KEY,
'ITEMWHSE_CHANGES' AS SOURCE_CHANGE_TBL,
'SITE_REF~ROW_SQN~ITEM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION


)