SELECT DISTINCT * FROM
(
SELECT 'VW_LOCATOR' AS SRCTBLNAME,
'WMSBREWSTER' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_LOCATOR' AS SRCTBLNAME,
'WMSEASTLONGMEADOW' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATOR' AS SRCTBLNAME,
'WMSFONTANA' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATOR' AS SRCTBLNAME,
'WMSFORTMILL' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATOR' AS SRCTBLNAME,
'WMSJACKSON' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATOR' AS SRCTBLNAME,
'WMSKANNAPOLIS' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATOR' AS SRCTBLNAME,
'WMSMILLCREEK' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATOR' AS SRCTBLNAME,
'WMSNORTHLAKE' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATOR' AS SRCTBLNAME,
'WMSWEB' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_CYCLE_COUNT' AS SRCTBLNAME,
'WMSBREWSTER' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,
'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'CC_NUMBER~LOCATION~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_CYCLE_COUNT' AS SRCTBLNAME,
'WMSEASTLONGMEADOW' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,
'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'CC_NUMBER~LOCATION~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_CYCLE_COUNT' AS SRCTBLNAME,
'WMSFONTANA' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,
'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'CC_NUMBER~LOCATION~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_CYCLE_COUNT' AS SRCTBLNAME,
'WMSFORTMILL' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,
'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'CC_NUMBER~LOCATION~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_CYCLE_COUNT' AS SRCTBLNAME,
'WMSJACKSON' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,
'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'CC_NUMBER~LOCATION~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_CYCLE_COUNT' AS SRCTBLNAME,
'WMSKANNAPOLIS' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,
'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'CC_NUMBER~LOCATION~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_CYCLE_COUNT' AS SRCTBLNAME,
'WMSMILLCREEK' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,
'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'CC_NUMBER~LOCATION~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_CYCLE_COUNT' AS SRCTBLNAME,
'WMSNORTHLAKE' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,
'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'CC_NUMBER~LOCATION~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_CYCLE_COUNT' AS SRCTBLNAME,
'WMSWEB' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,
'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'CC_NUMBER~LOCATION~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_INVENTORY' AS SRCTBLNAME,
'WMSBREWSTER' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_ITEM' AS SRCTBLNAME,
'WMSNORTHLAKE' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_ITEM' AS SRCTBLNAME,
'WMSBREWSTER' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_INVENTORY' AS SRCTBLNAME,
'WMSEASTLONGMEADOW' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL 

SELECT 'VW_ITEM' AS SRCTBLNAME,
'WMSEASTLONGMEADOW' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_INVENTORY' AS SRCTBLNAME,
'WMSFONTANA' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_ITEM' AS SRCTBLNAME,
'WMSFONTANA' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_INVENTORY' AS SRCTBLNAME,
'WMSFORTMILL' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_ITEM' AS SRCTBLNAME,
'WMSFORTMILL' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_INVENTORY' AS SRCTBLNAME,
'WMSJACKSON' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_ITEM' AS SRCTBLNAME,
'WMSJACKSON' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_INVENTORY' AS SRCTBLNAME,
'WMSKANNAPOLIS' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_ITEM' AS SRCTBLNAME,
'WMSKANNAPOLIS' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_INVENTORY' AS SRCTBLNAME,
'WMSMILLCREEK' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_ITEM' AS SRCTBLNAME,
'WMSMILLCREEK' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_INVENTORY' AS SRCTBLNAME,
'WMSNORTHLAKE' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_INVENTORY' AS SRCTBLNAME,
'WMSWEB' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LODNUM~SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_ITEM' AS SRCTBLNAME,
'WMSWEB' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'SKU' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATION' AS SRCTBLNAME,
'WMSBREWSTER' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LOCATION' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATION' AS SRCTBLNAME,
'WMSEASTLONGMEADOW' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LOCATION' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATION' AS SRCTBLNAME,
'WMSFONTANA' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LOCATION' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATION' AS SRCTBLNAME,
'WMSFORTMILL' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LOCATION' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATION' AS SRCTBLNAME,
'WMSJACKSON' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LOCATION' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATION' AS SRCTBLNAME,
'WMSKANNAPOLIS' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LOCATION' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATION' AS SRCTBLNAME,
'WMSMILLCREEK' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LOCATION' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATION' AS SRCTBLNAME,
'WMSNORTHLAKE' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LOCATION' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_LOCATION' AS SRCTBLNAME,
'WMSWEB' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'' AS SOURCE_CHANGE_TBL,
'LOCATION' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
)
