SELECT DISTINCT * FROM
(
SELECT 'VW_TR_HIST'AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_MOVEMENT_LINE' AS TBLNAME, 'INVTY_MVMNT_LN_KEY' AS DEST_CHANGE_KEY, 'VW_TR_HIST_CHANGES' AS SOURCE_CHANGE_TBL, 'tr_trnbr~tr_date~tr_line' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
union all
SELECT 'VW_TR_HIST'AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_MOVEMENT_HEADER' AS TBLNAME, 'INVTY_MVMNT_HDR_KEY' AS DEST_CHANGE_KEY, 'VW_TR_HIST_CHANGES' AS SOURCE_CHANGE_TBL, 'tr_trnbr~tr_date' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
union all
SELECT 'VW_LAD_DET'AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_ALLOCATION' AS TBLNAME, 'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY, 'VW_LAD_DET_CHANGES' AS SOURCE_CHANGE_TBL, 'lad_dataset~lad_nbr~lad_line~lad_site~lad_loc~lad_ref~lad_part~lad_lot' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
-- union all
-- SELECT 'VW_UPISU'AS SRCTBLNAME, 'EXCEL_ERRORPROOF' AS SYSTEMNAME, 'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME, 'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY, 'VW_UPISU_CHANGES' AS SOURCE_CHANGE_TBL, 'user_field_1~PART_ID~Identity_Column' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION 
-- '@@DBNAME.EXCEL_QADDB.VW_LD_DET A 
-- LEFT JOIN  @@DBNAME.EXCEL_QADDB.VW_LOC_MSTR LOC_MSTR
-- ON UPPER (LOC_MSTR.LOC_SITE) = UPPER(A.LD_SITE) AND UPPER(LOC_MSTR.LOC_LOC) = UPPER(A.LD_LOC) AND UPPER(LOC_MSTR.LOC_DOMAIN) = ''EXCEL''
-- LEFT JOIN 
-- (SELECT TR_NBR,TR_SITE,TR_LOC,TR_PART,TR_SERIAL,TR_DOMAIN,TR_LINE,TR_TYPE,TR_ADDR
--  FROM @@DBNAME.EXCEL_QADDB.VW_TR_HIST
-- QUALIFY ROW_NUMBER() OVER (PARTITION BY  UPPER(TR_SITE),UPPER(tr_LOC),UPPER(tr_PART),UPPER(TR_SERIAL) ORDER BY QLIK_INGST_TIMESTAMP DESC) =1) TR_HIST 
-- ON UPPER(TR_HIST.TR_SITE) = UPPER(A.LD_SITE) AND UPPER(TR_HIST.TR_LOC) = UPPER(A.LD_LOC) AND UPPER(TR_HIST.TR_PART) = UPPER(A.LD_PART) AND UPPER(TR_HIST.TR_SERIAL) = UPPER(A.LD_LOT) AND  UPPER(TR_HIST.TR_DOMAIN) = ''EXCEL''
-- LEFT JOIN @@DBNAME.EXCEL_QADDB.VW_PTP_DET PTP_DET ON UPPER(PTP_DET.PTP_PART) = UPPER(TR_HIST.TR_PART) AND UPPER(PTP_DET.PTP_SITE) = UPPER(TR_HIST.TR_SITE) AND UPPER(PTP_DOMAIN) = ''EXCEL''
-- LEFT JOIN @@DBNAME.EXCEL_QADDB.VW_PRH_HIST PRH_HIST ON UPPER(PRH_HIST.PRH_NBR) = UPPER(TR_HIST.TR_NBR) AND UPPER(PRH_HIST.PRH_LINE) =UPPER(TR_HIST.TR_LINE) AND  UPPER(TR_TYPE) IN (''rct-po'',''iss-prv'') AND UPPER(PRH_HIST.PRH_DOMAIN) = ''EXCEL''
-- LEFT JOIN @@DBNAME.EXCEL_QADDB.VW_IN_MSTR IN_MSTR ON UPPER(IN_MSTR.IN_SITE) = UPPER(A.LD_SITE) AND UPPER(IN_MSTR.IN_PART) = UPPER(A.LD_PART) AND UPPER(IN_DOMAIN) = ''EXCEL''
-- LEFT JOIN @@DBNAME.EXCEL_QADDB.VW_AD_MSTR AD_MSTR ON UPPER(AD_MSTR.AD_ADDR) =  UPPER(TR_HIST.TR_ADDR) AND UPPER(AD_DOMAIN) = ''EXCEL''
-- LEFT JOIN @@DBNAME.EXCEL_QADDB.VW_SI_MSTR SI_MSTR ON UPPER(SI_MSTR.SI_SITE) = UPPER(A.LD_SITE) AND UPPER(SI_DOMAIN) = ''EXCEL'' 
-- LEFT JOIN @@DBNAME.EXCEL_QADDB.VW_PT_MSTR PT_MSTR ON  UPPER(PT_MSTR.PT_PART) = UPPER(TR_HIST.TR_PART) AND UPPER(PT_MSTR.PT_DOMAIN) = ''EXCEL'' 
-- where UPPER(TRIM(A.LD_DOMAIN))=''EXCEL''' AS SRCTBLCONDITION
--SELECT 'VW_TR_HIST'AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_MOVEMENT_HEADER' AS TBLNAME, 'INVTY_MVMNT_HDR_KEY' AS DEST_CHANGE_KEY, 'VW_TR_HIST_CHANGES' AS SOURCE_CHANGE_TBL, 'tr_trnbr~tr_date' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
  union all
SELECT 'VW_LAD_DET'AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_ALLOCATION' AS TBLNAME, 'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY, 'VW_LAD_DET_CHANGES' AS SOURCE_CHANGE_TBL, 'lad_dataset~lad_nbr~lad_line~lad_site~lad_loc~lad_ref~lad_part~lad_lot' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION

UNION all
SELECT 'VW_LD_DET' AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME, 'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY, 'VW_LD_DET_CHANGES' AS SOURCE_CHANGE_TBL, 'LD_LOC~LD_SITE~LD_PART~LD_LOT~LD_REF~LD_DOMAIN' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION
UNION all
SELECT 'VW_WO_MSTR' AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_RESERVATION_HEADER' AS TBLNAME, 'INVTY_RSRV_HDR_KEY' AS DEST_CHANGE_KEY, 'VW_WO_MSTR_CHANGES' AS SOURCE_CHANGE_TBL, 'WO_NBR~WO_LOT' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION
UNION all
SELECT 'VW_UPISU' AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_CYCLE_COUNT_CLASS' AS TBLNAME, 'CYCLE_CNT_CLS_KEY' AS DEST_CHANGE_KEY, 'VW_UPISU_CHANGES' AS SOURCE_CHANGE_TBL, 'USER_FIELD_1~PART_ID~IDENTITY_COLUMN' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION
UNION all
SELECT 'VW_TR_HIST' AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_MOVEMENT_HEADER' AS TBLNAME, 'INVTY_MVMNT_HDR_KEY' AS DEST_CHANGE_KEY, 'VW_TR_HIST_CHANGES' AS SOURCE_CHANGE_TBL, 'tr_trnbr~tr_date' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'VW_LD_DET' AS SRCTBLNAME,'EXCEL_QADDB' AS SYSTEMNAME,'EDW_INVENTORY_ON_HAND_SNAPSHOT' AS TBLNAME,'INVTY_ON_HAND_SNAPSHOT_KEY' AS DEST_CHANGE_KEY,'VW_LD_DET_CHANGES' AS SOURCE_CHANGE_TBL,'LD_LOC~LD_PART~LD_LOT~LD_REF~LD_SITE' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE, NULL AS SRCTBLCONDITION
UNION all
SELECT 'VW_LD_DET' AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_ON_HAND_SNAPSHOT' AS TBLNAME, 'INVTY_ON_HAND_SNAPSHOT_KEY' AS DEST_CHANGE_KEY, 'VW_LD_DET_CHANGES' AS SOURCE_CHANGE_TBL, 'LD_SITE~LD_LOC~LD_PART~LD_LOT~LD_REF~LD_DATE' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION
union all
SELECT 'VW_WOD_DET' AS SRCTBLNAME, 'EXCEL_QADDB' AS SYSTEMNAME, 'EDW_INVENTORY_RESERVATION_DETAIL' AS TBLNAME, 'INVTY_RSRV_DTL_KEY' AS DEST_CHANGE_KEY, 'VW_WOD_DET_CHANGES' AS SOURCE_CHANGE_TBL, 'WOD_LOT~WOD_OP~WOD_PART~WOD_DOMAIN' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION
)

