SELECT DISTINCT * FROM
(
SELECT 'VW_F3002'AS SRCTBLNAME, 'JDEEF' AS SYSTEMNAME, 'EDW_PRODUCT_BOM_COMPONENT' AS TBLNAME, 'PROD_BOM_CMPNT_KEY' AS DEST_CHANGE_KEY, 'VW_F3002_CHANGES' AS SOURCE_CHANGE_TBL, 'IXKIT~IXMMCU~IXTBM~IXBQTY~IXCPNB~IXSBNT~IXCOBY' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
union all
SELECT 'F4141' AS SRCTBLNAME, 'JDEEF' AS SYSTEMNAME, 'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME, 'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY, 'F4141_CHANGES' AS SOURCE_CHANGE_TBL, 'PJCYNO~PJLITM~PJMCU~PJLOCN~PJLOTN~PJSTUN' AS SOURCE_CHANGE_KEY, 'SCD1' AS SCDTYPE , null AS SRCTBLCONDITION 
union all
SELECT 'VW_F4140' AS SRCTBLNAME, 'JDEEF' AS SYSTEMNAME, 'EDW_INVENTORY_CYCLE_COUNT_CLASS' AS TBLNAME, 'CYCLE_CNT_CLS_KEY' AS DEST_CHANGE_KEY, 'F4140_CHANGES' AS SOURCE_CHANGE_TBL, 'PICYNO' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE , null AS SRCTBLCONDITION 
)