SELECT DISTINCT * FROM
(
SELECT 'HIST' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_SALES_HISTORY' AS TBLNAME,
'DMD_SLS_HIST_KEY' AS DEST_CHANGE_KEY,
'HIST_CHANGES' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~HISTSTREAM~STARTDATE~TYPE~EVENT' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'CURRENCYPROFILEVAL' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_CURRENCY_PROFILE' AS TBLNAME,
'CRNCY_PRFL_KEY' AS DEST_CHANGE_KEY,
'CURRENCYPROFILEVAL_CHANGES' AS SOURCE_CHANGE_TBL,
'FROMCURRENCY~TOCURRENCY~STARTDATE' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'DYNDEPSRC' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_DYNAMIC_DEPLOYMENT_SOURCE' AS TBLNAME,
'SUPPLY_PLNG_DYN_DPLY_SRC_KEY' AS DEST_CHANGE_KEY,
'DYNDEPSRC_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~SOURCE~EFF~TRANSMODE~DEST' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'DFUMAP' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_FORECASTING_UNIT_MAP' AS TBLNAME,
'DMD_FORECASTING_UNIT_MAP_KEY' AS DEST_CHANGE_KEY,
'DFUMAP_CHANGES' AS SOURCE_CHANGE_TBL,
'FROMDFULOC~FROMDMDGROUP~FROMDMDUNIT~FROMMODEL~MAP~TODFULOC~TODMDGROUP~TODMDUNIT~EFF'
AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'DMDGROUP' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_GROUP' AS TBLNAME,
'DMD_GRP_KEY' AS DEST_CHANGE_KEY,
'DMDGROUP_CHANGES' AS SOURCE_CHANGE_TBL,
'DMDGROUP' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'DFUEXCEPTION' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_FORECASTING_EXCEPTION' AS TBLNAME,
'DMD_FCST_EXCEPTION_KEY' AS DEST_CHANGE_KEY,
'DFUEXCEPTION_CHANGES' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~MODEL~FUNCTIONNAME~EXCEPTION~FUNCTIONNUM' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
UNION ALL

SELECT 'DFUTOSKUFCST' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_DFU_SKU_FORECAST' AS TBLNAME,
'DFU_SKU_FCST_KEY' AS DEST_CHANGE_KEY,
'VW_DFUTOSKUFCST' AS SOURCE_CHANGE_TBL,
'ITEM~SKULOC~DMDUNIT~DMDGROUP~DFULOC~STARTDATE~DUR~TYPE~SUPERSEDESW' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
UNION ALL

SELECT 'FCST' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_DEMAND_FORECAST' AS TBLNAME,
'DMD_FCST_KEY' AS DEST_CHANGE_KEY,
'FCST_CHANGES' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~STARTDATE~TYPE~FCSTID~MODEL ' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'FCSTDRAFT' AS SRCTBLNAME,
'JDAEDW_BACK' AS SYSTEMNAME,
'EDW_DEMAND_FORECAST' AS TBLNAME,
'DMD_FCST_KEY' AS DEST_CHANGE_KEY,
'VW_FCSTDRAFT' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~STARTDATE~TYPE~FCSTID~MODEL' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union ALL
SELECT 'VEHICLELOAD' AS SRCTBLNAME, 
'JDAEDW' AS SYSTEMNAME, 
'EDW_VEHICLE_LOAD_HEADER' AS TBLNAME, 
'VHCL_LOD_HDR_KEY' AS DEST_CHANGE_KEY, 
'VW_VEHICLELOAD' AS SOURCE_CHANGE_TBL, 
'loadid' AS SOURCE_CHANGE_KEY, 
'SCD1' AS SCDTYPE , 
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'PRODUCTIONSTEP' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_PRODUCTION_METHOD_STEP' AS TBLNAME,
'PRODTN_MTHD_STEP_KEY' AS DEST_CHANGE_KEY,
'PRODUCTIONSTEP_CHANGES' AS SOURCE_CHANGE_TBL,
'PRODUCTIONMETHOD~STEPNUM~ITEM~LOC~EFF' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'PLANORDER' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNED_ORDER' AS TBLNAME,
'SUPPLY_PLND_ORD_KEY' AS DEST_CHANGE_KEY,
'PLANORDER_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC~SEQNUM' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union all

SELECT 'RESPROJSTATIC' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_RESOURCE_PROJECTION' AS TBLNAME,
'SUPPLY_PLNG_RESOURCE_PROJECTION_KEY' AS DEST_CHANGE_KEY,
'RESPROJSTATIC_CHANGES' AS SOURCE_CHANGE_TBL,
'LOC~OPTIONSET~RES~STARTDATE' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union all

SELECT 'SKUDEMANDPARAM' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_DEMAND_PARAMETER' AS TBLNAME,
'SUPPLY_PLNG_DMD_PARM_KEY' AS DEST_CHANGE_KEY,
'SKUDEMANDPARAM_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union ALL
SELECT 'DFUTOSKU' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DFU_SKU_ASSOCIATION' AS TBLNAME,
'DFU_SKU_ASSOC_KEY' AS DEST_CHANGE_KEY,
'DFUTOSKU_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~SKULOC~DMDUNIT~DMDGROUP~DFULOC~EFF~DISC' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union ALL
SELECT 'SOURCING' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_SOURCING' AS TBLNAME,
'SUPPLY_PLNG_PROD_SOURCING_KEY' AS DEST_CHANGE_KEY,
'SOURCING_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~DEST~SOURCE~SOURCING' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union all

SELECT 'VEHICLELOADLINE' AS SRCTBLNAME, 
'JDAEDW' AS SYSTEMNAME, 
'EDW_VEHICLE_LOAD_LINE' AS TBLNAME,
 'VHCL_LOD_LN_KEY' AS DEST_CHANGE_KEY, 
'VW_VEHICLELOADLINE' AS SOURCE_CHANGE_TBL,
  'LOADID~PRIMARYITEM~EXPDATE~ITEM~DEST' AS SOURCE_CHANGE_KEY, 
  'SCD1' AS SCDTYPE , 
  NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'PRICEPROFILEVAL' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_PRICE_PROFILE' AS TBLNAME,
'PRC_PRFL_KEY' AS DEST_CHANGE_KEY,
'VW_PRICEPROFILEVAL' AS SOURCE_CHANGE_TBL,
'PRICEPROFILENAME~STARTDATE' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'ITEM' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'ITEM_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'DMDUNIT' AS SRCTBLNAME,
'JDAEDW_BACK' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'VW_DMDUNIT' AS SOURCE_CHANGE_TBL,
'DMDUNIT' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION


UNION ALL


SELECT 'SKUSAFETYSTOCKPARAM' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_SAFETY_STOCK_PARAMETER' AS TBLNAME,
'SUPPLY_PLNG_SFTY_STK_PARM_KEY' AS DEST_CHANGE_KEY,
'SKUSAFETYSTOCKPARAM_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'HISTFCST' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_DEMAND_FORECAST_HISTORY' AS TBLNAME,
'DMD_FCST_HIST_KEY' AS DEST_CHANGE_KEY,
'VW_HISTFCST' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~MODEL~FCSTDATE~STARTDATE' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'SKUPLANNINGPARAM' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SKU_PLANNING_PARAMETER' AS TBLNAME,
'SKU_PLNG_PARM_KEY' AS DEST_CHANGE_KEY,
'SKUPLANNINGPARAM_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union all
SELECT 'CAL' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_PLANNING_CALENDAR' AS TBLNAME,
'PLNG_CLNDR_KEY' AS DEST_CHANGE_KEY,
'CAL_CHANGES' AS SOURCE_CHANGE_TBL,
'CAL' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union all
SELECT 'CALDATA' AS SRCTBLNAME,
'JDA_BACK' AS SYSTEMNAME,
'EDW_PLANNING_CALENDAR' AS TBLNAME,
'PLNG_CLNDR_KEY' AS DEST_CHANGE_KEY,
'CALDATA_CHANGES' AS SOURCE_CHANGE_TBL,
'CAL~EFF' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL


SELECT 'RECSHIP' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNED_RECOMMENDED_SHIPMENT' AS TBLNAME,
'SUPPLY_PLND_RECOMMENDED_SHIP_KEY' AS DEST_CHANGE_KEY,
'RECSHIP_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~DEST~SEQNUM~SOURCE~TYPE' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'SKUDISPLAY' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_VIEW' AS TBLNAME,
'SUPPLY_PLNG_PROD_VW_KEY' AS DEST_CHANGE_KEY,
'SKUDISPLAY_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'SKU' AS SRCTBLNAME,
'JDAEDW_BACK' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_VIEW' AS TBLNAME,
'SUPPLY_PLNG_PROD_VW_KEY' AS DEST_CHANGE_KEY,
'SKU_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'SKUDEPLOYMENTPARAM' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_DEPLOYMENT_PARAMETER' AS TBLNAME,
'SUPPLY_PLNG_DPLY_PARM_KEY' AS DEST_CHANGE_KEY,
'RSKUDEPLOYMENTPARAM_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'LOC' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'LOC_CHANGES' AS SOURCE_CHANGE_TBL,
'LOC' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'CUSTORDER' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_CUSTOMER_ORDER' AS TBLNAME,
'CUST_ORD_KEY' AS DEST_CHANGE_KEY,
'CUSTORDER_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC~ORDERID~SHIPDATE' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
UNION ALL

SELECT 'RES' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME, 
'EDW_RESOURCE' AS TBLNAME,
'RESOURCE_KEY' AS DEST_CHANGE_KEY,
'RES_CHANGES' AS SOURCE_CHANGE_TBL,
'RES' AS SOURCE_CHANGE_KEY,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'PRODUCTIONMETHOD' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_PRODUCTION_METHOD' AS TBLNAME,
'PRODTN_MTHD_KEY' AS DEST_CHANGE_KEY,
'VW_PRODUCTIONMETHOD' AS SOURCE_CHANGE_TBL,
'PRODUCTIONMETHOD~ITEM~LOC' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'RESLOADDETAIL' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_RESOURCE_LOAD_DETAILS' AS TBLNAME,
'RESOURCE_LOD_DETAILS_KEY' AS DEST_CHANGE_KEY,
'RESLOADDETAIL_CHANGES' AS SOURCE_CHANGE_TBL,
'DMDORDERTYPE~DMDORDERSEQNUM~SUPPLYSEQNUM~WHENLOADED~STEPNUM~PRODUCTIONMETHOD~SUPPLYTYPE~RES~LOC~ITEM' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
UNION ALL

SELECT 'NETWORK' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_NETWORK' AS TBLNAME,
'NETWORK_KEY' AS DEST_CHANGE_KEY,
'VW_NETWORK' AS SOURCE_CHANGE_TBL,
'SOURCE~TRANSMODE~DEST' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'UDTSKUPROJSTATICWEEKLY' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_PROJECTION' AS TBLNAME,
'SUPPLY_PLNG_PROD_PROJECTION_KEY' AS DEST_CHANGE_KEY,
'UDTSKUPROJSTATICWEEKLY_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC~OPTION_SET~START_DATE' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'DFU' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_FORECASTING_UNIT' AS TBLNAME,
'DMD_FORCAST_UNIT_KEY' AS DEST_CHANGE_KEY,
'DFU_CHANGES' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~MODEL' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'BOM' AS SRCTBLNAME,
'JDAEDW' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_BOM_VIEW' AS TBLNAME,
'SUPPLY_PLNG_PROD_BOM_VW_KEY' AS DEST_CHANGE_KEY,
'VW_BOM' AS SOURCE_CHANGE_TBL,
'ITEM~SUBORD~LOC~BOMNUM~EFF~OFFSET' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_UDTIOROOTCAUSE' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_IO_ROOTCAUSE' AS TBLNAME,
'SUPPLY_PLNG_IO_RC_KEY' AS DEST_CHANGE_KEY,
'UDTIOROOTCAUSE_CHANGES' AS SOURCE_CHANGE_TBL,
'U_ITEM~U_LOC~U_PLAN_DATE~U_TARGET_DATE' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_UDTGLBLPLANNER' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_GLOBAL_PLANNER' AS TBLNAME,
'SUPPLY_PLNG_GLB_PLNR_KEY' AS DEST_CHANGE_KEY,
'UDTGLBLPLANNER_CHANGES' AS SOURCE_CHANGE_TBL,
'U_PLANNER_CD' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_IOSKUPERFORMANCE' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_IO_SKU_PERFORMANCE' AS TBLNAME,
'SUPPLY_PLNG_IO_SKU_PERFORM_KEY' AS DEST_CHANGE_KEY,
'IOSKUPERFORMANCE_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC~PLANID~EFF' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION


UNION ALL

SELECT 'VW_UDTIOROOTCAUSE' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_IO_ROOTCAUSE' AS TBLNAME,
'SUPPLY_PLNG_IO_RC_KEY' AS DEST_CHANGE_KEY,
'UDTIOROOTCAUSE_CHANGES' AS SOURCE_CHANGE_TBL,
'U_ITEM~U_LOC~U_PLAN_DATE~U_TARGET_DATE' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_UDTGLBLPLANNER' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_GLOBAL_PLANNER' AS TBLNAME,
'SUPPLY_PLNG_GLB_PLNR_KEY' AS DEST_CHANGE_KEY,
'UDTGLBLPLANNER_CHANGES' AS SOURCE_CHANGE_TBL,
'U_PLANNER_CD' AS SOURCE_CHANGE_KEY ,
'SCD1' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_IOSKUPERFORMANCE' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_IO_SKU_PERFORMANCE' AS TBLNAME,
'SUPPLY_PLNG_IO_SKU_PERFORM_KEY' AS DEST_CHANGE_KEY,
'IOSKUPERFORMANCE_CHANGES' AS SOURCE_CHANGE_TBL,
'ITEM~LOC~PLANID~EFF' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
)
