SELECT DISTINCT * FROM
(
SELECT 'STPO'AS SRCTBLNAME, 'SAPSHP' AS SYSTEMNAME, 'EDW_PRODUCT_BOM_COMPONENT' AS TBLNAME, 'PROD_BOM_CMPNT_KEY' AS DEST_CHANGE_KEY, 'STPO_CHANGES' AS SOURCE_CHANGE_TBL, 'STLTY~STLNR~STLKN~STPOZ' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,'@@DBNAME.SAPSHP.STPO A where A.MANDT = ''100''' AS SRCTBLCONDITION
Union All
SELECT 'MAST' AS SRCTBLNAME, 
'SAPSHP' AS SYSTEMNAME, 
'EDW_PRODUCT_BOM_PARENT' AS TBLNAME, 
'PROD_BOM_PRNT_KEY' AS DEST_CHANGE_KEY, 
'MAST_CHANGES' AS SOURCE_CHANGE_TBL, 
'stlnr~stlal' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE , 
null AS SRCTBLCONDITION 

union all

SELECT 'T001L' AS SRCTBLNAME, 
'SAPSHP' AS SYSTEMNAME, 
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME, 
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY, 
'T001L_CHANGES' AS SOURCE_CHANGE_TBL, 
'LGORT~WERKS' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE , 
null AS SRCTBLCONDITION 

union all

SELECT 'RKPF' AS SRCTBLNAME, 
'SAPSHP' AS SYSTEMNAME, 
'EDW_INVENTORY_RESERVATION_HEADER' AS TBLNAME, 
'INVTY_RSRV_HDR_KEY' AS DEST_CHANGE_KEY, 
'RKPF_CHANGES' AS SOURCE_CHANGE_TBL, 
'RSNUM' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE , 
null AS SRCTBLCONDITION 

union all 

SELECT 'VW_MSEG' AS SRCTBLNAME, 
'SAPSHP' AS SYSTEMNAME, 
'EDW_INVENTORY_MOVEMENT_LINE' AS TBLNAME, 
'INVTY_MVMNT_LN_KEY' AS DEST_CHANGE_KEY, 
'VW_MSEG_CHANGES' AS SOURCE_CHANGE_TBL, 
'MBLNR~MJAHR~ZEILE' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
null AS SRCTBLCONDITION 
)