select distinct * from 
(
SELECT 'cnttyp' AS SRCTBLNAME,'JDAWMSASIA' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT_CLASS' AS TBLNAME,'CYCLE_CNT_CLS_KEY' AS DEST_CHANGE_KEY,'cnttyp_changes' AS SOURCE_CHANGE_TBL,'cnttyp' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'cnttyp' AS SRCTBLNAME,'JDAWMSEANZ' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT_CLASS' AS TBLNAME,'CYCLE_CNT_CLS_KEY' AS DEST_CHANGE_KEY,'cnttyp_changes' AS SOURCE_CHANGE_TBL,'cnttyp' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'cnttyp' AS SRCTBLNAME,'JDAWMSNA1' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT_CLASS' AS TBLNAME,'CYCLE_CNT_CLS_KEY' AS DEST_CHANGE_KEY,'cnttyp_changes' AS SOURCE_CHANGE_TBL,'cnttyp' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'cnttyp' AS SRCTBLNAME,'JDAWMSLA1' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT_CLASS' AS TBLNAME,'CYCLE_CNT_CLS_KEY' AS DEST_CHANGE_KEY,'cnttyp_changes' AS SOURCE_CHANGE_TBL,'cnttyp' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'invsub' AS SRCTBLNAME,'JDAWMSASIA' AS SYSTEMNAME,'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER' AS TBLNAME,'WHSE_TRNSFR_ORD_HDR_KEY' AS DEST_CHANGE_KEY,'invsub_changes' AS SOURCE_CHANGE_TBL,'subnum' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'invsub' AS SRCTBLNAME,'JDAWMSEANZ' AS SYSTEMNAME,'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER' AS TBLNAME,'WHSE_TRNSFR_ORD_HDR_KEY' AS DEST_CHANGE_KEY,'invsub_changes' AS SOURCE_CHANGE_TBL,'subnum' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'invsub' AS SRCTBLNAME,'JDAWMSNA1' AS SYSTEMNAME,'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER' AS TBLNAME,'WHSE_TRNSFR_ORD_HDR_KEY' AS DEST_CHANGE_KEY,'invsub_changes' AS SOURCE_CHANGE_TBL,'subnum' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'invsub' AS SRCTBLNAME,'JDAWMSLA1' AS SYSTEMNAME,'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER' AS TBLNAME,'WHSE_TRNSFR_ORD_HDR_KEY' AS DEST_CHANGE_KEY,'invsub_changes' AS SOURCE_CHANGE_TBL,'subnum' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'INVDTL' AS SRCTBLNAME,'JDAWMSASIA' AS SYSTEMNAME,'EDW_WAREHOUSE_TRANSFER_ORDER_LINE' AS TBLNAME,'WHSE_TRNSFR_ORD_LN_KEY' AS DEST_CHANGE_KEY,'INVDTL_changes' AS SOURCE_CHANGE_TBL,'dtlnum~subnum' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'INVDTL' AS SRCTBLNAME,'JDAWMSEANZ' AS SYSTEMNAME,'EDW_WAREHOUSE_TRANSFER_ORDER_LINE' AS TBLNAME,'WHSE_TRNSFR_ORD_LN_KEY' AS DEST_CHANGE_KEY,'INVDTL_changes' AS SOURCE_CHANGE_TBL,'dtlnum~subnum' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'INVDTL' AS SRCTBLNAME,'JDAWMSNA1' AS SYSTEMNAME,'EDW_WAREHOUSE_TRANSFER_ORDER_LINE' AS TBLNAME,'WHSE_TRNSFR_ORD_LN_KEY' AS DEST_CHANGE_KEY,'INVDTL_changes' AS SOURCE_CHANGE_TBL,'dtlnum~subnum' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'INVDTL' AS SRCTBLNAME,'JDAWMSLA1' AS SYSTEMNAME,'EDW_WAREHOUSE_TRANSFER_ORDER_LINE' AS TBLNAME,'WHSE_TRNSFR_ORD_LN_KEY' AS DEST_CHANGE_KEY,'INVDTL_changes' AS SOURCE_CHANGE_TBL,'dtlnum~subnum' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all

SELECT 'CNTHST' AS SRCTBLNAME,'JDAWMSASIA' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,'CNTHST_changes' AS SOURCE_CHANGE_TBL,'CNTHST_ID' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'CNTHST' AS SRCTBLNAME,'JDAWMSEANZ' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,'CNTHST_changes' AS SOURCE_CHANGE_TBL,'CNTHST_ID' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'CNTHST' AS SRCTBLNAME,'JDAWMSNA1' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,'CNTHST_changes' AS SOURCE_CHANGE_TBL,'CNTHST_ID' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'CNTHST' AS SRCTBLNAME,'JDAWMSLA1' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,'CNTHST_changes' AS SOURCE_CHANGE_TBL,'CNTHST_ID' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all

SELECT 'CNTWRK' AS SRCTBLNAME,'JDAWMSASIA_BACK' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,'CNTWRK_changes' AS SOURCE_CHANGE_TBL,'HASH_FULL_RECORD' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'CNTWRK' AS SRCTBLNAME,'JDAWMSEANZ_BACK' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,'CNTWRK_changes' AS SOURCE_CHANGE_TBL,'HASH_FULL_RECORD' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'CNTWRK' AS SRCTBLNAME,'JDAWMSNA1_BACK' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,'CNTWRK_changes' AS SOURCE_CHANGE_TBL,'HASH_FULL_RECORD' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION

union all
SELECT 'CNTWRK' AS SRCTBLNAME,'JDAWMSLA1_BACK' AS SYSTEMNAME,'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME,'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY,'CNTWRK_changes' AS SOURCE_CHANGE_TBL,'HASH_FULL_RECORD' AS SOURCE_CHANGE_KEY,'SCD2' AS SCDTYPE,NULL AS SRCTBLCONDITION



)