SELECT DISTINCT * FROM
(
SELECT 'IWI' AS SRCTBLNAME,
'INFORLX' AS SYSTEMNAME,
'EDW_INVENTORY_ON_HAND_SNAPSHOT' AS TBLNAME,
'INVTY_ON_HAND_SNAPSHOT_KEY' AS DEST_CHANGE_KEY,
'IWI_CHANGES' AS SOURCE_CHANGE_TBL,
'WWHS~WPROD' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
UNION ALL 
SELECT 'MBM' AS SRCTBLNAME,
'INFORLX' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT' AS TBLNAME,
'PROD_BOM_CMPNT_KEY' AS DEST_CHANGE_KEY,
'MBM_CHANGES' AS SOURCE_CHANGE_TBL,
'BPROD~BMWHS~BMBOMM~BSEQ' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

Union All

SELECT 'IPH' AS SRCTBLNAME,
'INFORLX' AS SYSTEMNAME,
'EDW_INVENTORY_PHYSICAL_COUNT' AS TBLNAME,
'PHY_INVTY_KEY' AS DEST_CHANGE_KEY,
'IPH_CHANGES' AS SOURCE_CHANGE_TBL,
'PHWHSE~PHTAG' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

)