SELECT DISTINCT * FROM
(
SELECT 'VW_SLQNTY_RVI'AS SRCTBLNAME, 'INFORXA' AS SYSTEMNAME, 'EDW_INVENTORY_ON_HAND_SNAPSHOT' AS TBLNAME, 'INVTY_ON_HAND_SNAPSHOT_KEY' AS DEST_CHANGE_KEY, 'VW_SLQNTY_RVI_CHANGES' AS SOURCE_CHANGE_TBL, 'ITNBR~HOUSE~LLOCN' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,
'(select loaddts,lqnty,llocn,house,fdate,itnbr
    from @@DBNAME.INFORXA.VW_SLQNTY_RVI) A
left join
    @@DBNAME.INFORXA.VW_WHSMST as whsmst
    on upper(trim(A.house)) = upper(trim(whsmst.whid))
left join
    (SELECT * FROM @@DBNAME.INFORXA.VW_ITEMBL  qualify
            row_number() over (PARTITION BY trim(ITNBR),trim(house) ORDER BY LOADDTS DESC)
            = 1
    ) as itembl
    on upper(trim(A.itnbr)) = upper(trim(itembl.itnbr))
    and upper(trim(A.house)) = upper(trim(itembl.house))
left join
    (
        select b2cocd, unmsr, itnbr, stid
        from @@DBNAME.INFORXA.VW_ITMRVA 
        qualify
            row_number() over (PARTITION BY trim(ITNBR),trim(STID) ORDER BY ITRV,CHDE DESC)
            = 1
    ) as itmrva
    on upper(trim(A.itnbr)) = upper(trim(itmrva.itnbr))
    and upper(trim(whsmst.stid)) = upper(trim(itmrva.stid))' AS SRCTBLCONDITION
union all
SELECT 'VW_SLALLO' AS SRCTBLNAME, 'INFORXA' AS SYSTEMNAME, 'EDW_INVENTORY_ALLOCATION' AS TBLNAME, 'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY, 'VW_SLALLO_CHANGES' AS SOURCE_CHANGE_TBL, 'ITNBR~HOUSE~ORDNO~CONO~ITMSQ~RLNB~LLOCN' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,
'@@DBNAME.INFORXA.VW_SLALLO AS A
LEFT JOIN  @@DBNAME.INFORXA.VW_WHSMST AS WHSMST
ON upper(trim(A.HOUSE)) = upper(trim(WHSMST.WHID))
LEFT JOIN  @@DBNAME.INFORXA.VW_ITEMASUE AS ITEMASUE
ON upper(trim(A.ITNBR)) = upper(trim(ITEMASUE.IEITNO))
LEFT JOIN  @@DBNAME.INFORXA.VW_ITMRVA AS ITMRVA
ON  upper(trim(A.ITNBR))=upper(trim(ITMRVA.ITNBR))  AND upper(trim(WHSMST.STID))=upper(trim(ITMRVA.STID))
LEFT JOIN  @@DBNAME.INFORXA.VW_ITEMBL AS ITEMBL
ON  upper(trim(A.ITNBR)) = upper(trim(ITEMBL.ITNBR)) AND upper(trim(A.HOUSE))=upper(trim(ITEMBL.HOUSE))' AS SRCTBLCONDITION 
union all
SELECT 'VW_PHYINVCT_MAR'AS SRCTBLNAME, 'INFORXA' AS SYSTEMNAME, 'EDW_INVENTORY_CYCLE_COUNT' AS TBLNAME, 'INVTY_CYCLE_CNT_KEY' AS DEST_CHANGE_KEY, 'VW_PHYINVCT_MAR_CHANGES' AS SOURCE_CHANGE_TBL, 'CNTDTE~CNTPRT~CNTLOC~CNTUSR~CNTUOM~CNTSUB' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
union all
SELECT 'VW_IMHISTAUS'AS SRCTBLNAME, 'INFORXA' AS SYSTEMNAME, 'EDW_INVENTORY_MOVEMENT_LINE' AS TBLNAME, 'INVTY_MVMNT_LN_KEY' AS DEST_CHANGE_KEY, 'VW_IMHISTAUS_CHANGES' AS SOURCE_CHANGE_TBL, 'ITNBR~HOUSE~TAID~TCODE~PSTMAV' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
union all
SELECT 'VW_IMHISTAUS'AS SRCTBLNAME, 'INFORXA' AS SYSTEMNAME, 'EDW_INVENTORY_MOVEMENT_HEADER' AS TBLNAME, 'INVTY_MVMNT_HDR_KEY' AS DEST_CHANGE_KEY, 'VW_IMHISTAUS_CHANGES' AS SOURCE_CHANGE_TBL, 'ITNBR~HOUSE~TAID~TCODE~PSTMAV' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
union all
SELECT 'VW_SLQNTY'AS SRCTBLNAME, 'INFORXA' AS SYSTEMNAME, 'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME, 'INVTY_MVMNT_HDR_KEY' AS DEST_CHANGE_KEY, 'VW_SLQNTY_CHANGES' AS SOURCE_CHANGE_TBL, 'SLQNTY~HOUSE~LLOCN~ITNBR' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
union all
SELECT 'VW_ITMRVB'AS SRCTBLNAME, 'INFORXA' AS SYSTEMNAME, 'EDW_PRODUCT_COST' AS TBLNAME, 'PROD_KEY' AS DEST_CHANGE_KEY, 'VW_ITMRVB_CHANGES' AS SOURCE_CHANGE_TBL, 'STID~ITNBR~ITRV' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
)
--union all
--SELECT 'VW_F4140' AS SRCTBLNAME, 'JDEEF' AS SYSTEMNAME, 'EDW_INVENTORY_CYCLE_COUNT_CLASS' AS TBLNAME, 'CYCLE_CNT_CLS_KEY' AS DEST_CHANGE_KEY, 'F4140_CHANGES' AS SOURCE_CHANGE_TBL, 'PICYNO' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE , null AS SRCTBLCONDITION 
--)