SELECT DISTINCT * FROM
(
SELECT 'BOMOPCOMPONENT'AS SRCTBLNAME, 'UFIDA' AS SYSTEMNAME, 'EDW_PRODUCT_BOM_COMPONENT' AS TBLNAME, 'PROD_BOM_CMPNT_KEY' AS DEST_CHANGE_KEY, 'BOMOPCOMPONENT_CHANGES' AS SOURCE_CHANGE_TBL, 'OPCOMPONENTID' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION UNION ALL
SELECT 'BOMPARENT'AS SRCTBLNAME, 'UFIDA' AS SYSTEMNAME, 'EDW_PRODUCT_BOM_PARENT' AS TBLNAME,
 'PROD_BOM_PRNT_KEY' AS DEST_CHANGE_KEY, 'BOMPARENT_CHANGES' AS SOURCE_CHANGE_TBL, 
 'BOMID' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION UNION ALL
SELECT 'CHECKVOUCHS'AS SRCTBLNAME, 'UFIDA' AS SYSTEMNAME, 'EDW_INVENTORY_PHYSICAL_COUNT' AS TBLNAME, 'PHY_INVTY_KEY' AS DEST_CHANGE_KEY, 'CHECKVOUCHS_CHANGES' AS SOURCE_CHANGE_TBL, 'AUTOID' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
)