SELECT DISTINCT * FROM
(
SELECT 'PSMSTR'AS SRCTBLNAME, 'QADBR' AS SYSTEMNAME, 'EDW_PRODUCT_BOM_COMPONENT' AS TBLNAME, 'PROD_BOM_CMPNT_KEY' AS DEST_CHANGE_KEY, 'PSMSTR_CHANGES' AS SOURCE_CHANGE_TBL, 'PS_PAR~PS_COMP~PS_START~PS_REF' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE ,NULL AS SRCTBLCONDITION
UNION ALL 
SELECT 'tagmstr' AS SRCTBLNAME, 'QADBR' AS SYSTEMNAME, 'EDW_INVENTORY_PHYSICAL_COUNT' AS TBLNAME, 'PHY_INVTY_KEY' AS DEST_CHANGE_KEY, 'tagmstr_CHANGES' AS SOURCE_CHANGE_TBL, 'cnthst_id' AS SOURCE_CHANGE_KEY, 'SCD1' AS SCDTYPE , null AS SRCTBLCONDITION
UNION ALL 
SELECT 'BDRESERVA' AS SRCTBLNAME, 'QADBR' AS SYSTEMNAME, 'EDW_INVENTORY_RESERVATION_HEADER' AS TBLNAME, 'INVTY_RSRV_HDR_KEY' AS DEST_CHANGE_KEY, 'BDRESERVA_CHANGES' AS SOURCE_CHANGE_TBL, 'bd_domain~bd_cli' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE , null AS SRCTBLCONDITION
UNION ALL 
SELECT 'BDRESITEM' AS SRCTBLNAME, 'QADBR' AS SYSTEMNAME, 'EDW_INVENTORY_RESERVATION_DETAIL' AS TBLNAME, 'INVTY_RSRV_DTL_KEY' AS DEST_CHANGE_KEY, 'BDRESITEM_CHANGES' AS SOURCE_CHANGE_TBL, 'bd_domain~bd_lugar~bd_mes~bd_ano~bd_item' AS SOURCE_CHANGE_KEY, 'SCD2' AS SCDTYPE , null AS SRCTBLCONDITION
)