SELECT DISTINCT * FROM
(
SELECT 'LDDET' AS SRCTBLNAME,
'QADPE' AS SYSTEMNAME,
'EDW_INVENTORY_ON_HAND_SNAPSHOT' AS TBLNAME,
'INVTY_ON_HAND_SNAPSHOT_KEY' AS DEST_CHANGE_KEY,
'LDDET_CHANGES' AS SOURCE_CHANGE_TBL,
'LD_PART~LD_SITE~LD_LOC~LD_LOT~LD_REF' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_PTPDET' AS SRCTBLNAME, 
'QADPE' AS SYSTEMNAME, 
'EDW_INVENTORY_MOVEMENT_HEADER' AS TBLNAME, 
'INVTY_MVMNT_HDR_KEY' AS DEST_CHANGE_KEY, 
'VW_PTPDET_CHANGES' AS SOURCE_CHANGE_TBL, 
'PTP_PART~PTP_SITE' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
UNION ALL 

SELECT 'BDPSMSTR' AS SRCTBLNAME,
'QADPE' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT' AS TBLNAME,
'PROD_BOM_CMPNT_KEY' AS DEST_CHANGE_KEY,
'BDPSMSTR_CHANGES' AS SOURCE_CHANGE_TBL,
'BDPS_PAR~BDPS_COMP~BDPS_START~BDPS_REF~BDPS_SITE' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'LADDET' AS SRCTBLNAME,
'QADPE' AS SYSTEMNAME,
'EDW_INVENTORY_ALLOCATION' AS TBLNAME,
'INVTY_ALLOC_KEY' AS DEST_CHANGE_KEY,
'LADDET_CHANGES' AS SOURCE_CHANGE_TBL,
'lad_dataset~lad_nbr~lad_line~lad_site~lad_loc~lad_ref~lad_part~lad_lot' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
)
