SELECT DISTINCT * FROM
(
SELECT 'PTPDET' AS SRCTBLNAME, 
'QADDE' AS SYSTEMNAME, 
'EDW_INVENTORY_MOVEMENT_HEADER' AS TBLNAME, 
'INVTY_MVMNT_HDR_KEY' AS DEST_CHANGE_KEY, 
'PTPDET_CHANGES' AS SOURCE_CHANGE_TBL, 
'PTP_PART~PTP_SITE' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
union all
SELECT 'PSMSTR' AS SRCTBLNAME,
'QADDE' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT' AS TBLNAME,
'PROD_BOM_CMPNT_KEY' AS DEST_CHANGE_KEY,
'PSMSTR_CHANGES' AS SOURCE_CHANGE_TBL,
'PS_PAR~PS_COMP~PS_REF~PS_START' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
 NULL AS SRCTBLCONDITION
)