SELECT DISTINCT * FROM
(
SELECT 'PRODUCTIONBOMLINE'AS SRCTBLNAME, 
'NAVISIONHY' AS SYSTEMNAME, 
'EDW_PRODUCT_BOM_COMPONENT' AS TBLNAME, 
'PROD_BOM_CMPNT_KEY' AS DEST_CHANGE_KEY, 
'PRODUCTIONBOMLINE_CHANGES' AS SOURCE_CHANGE_TBL, 
'COMPANY~PRODUCTIONBOMNO~VERSIONCODE~LINENO' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union all

SELECT 'PRODUCTIONBOMHEADER' AS SRCTBLNAME, 
'NAVISIONHY' AS SYSTEMNAME, 
'EDW_PRODUCT_BOM_PARENT' AS TBLNAME, 
'PROD_BOM_PRNT_KEY' AS DEST_CHANGE_KEY, 
'PRODUCTIONBOMHEADER_CHANGES' AS SOURCE_CHANGE_TBL, 
'COMPANY~no' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE , 
null AS SRCTBLCONDITION 

union all

SELECT 'RESERVATIONENTRY'AS SRCTBLNAME, 
'NAVISIONHY' AS SYSTEMNAME, 
'EDW_INVENTORY_RESERVATION_HEADER' AS TBLNAME, 
'INVTY_RSRV_HDR_KEY' AS DEST_CHANGE_KEY, 
'RESERVATIONENTRY_CHANGES' AS SOURCE_CHANGE_TBL, 
'COMPANY~POSITIVE~ENTRY_NO' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union all

SELECT 'ITEMLEDGERENTRY'AS SRCTBLNAME, 
'NAVISIONHY' AS SYSTEMNAME, 
'EDW_INVENTORY_ON_HAND_SNAPSHOT' AS TBLNAME, 
'INVTY_ON_HAND_SNAPSHOT_KEY' AS DEST_CHANGE_KEY, 
'ITEMLEDGERENTRY_CHANGES' AS SOURCE_CHANGE_TBL, 
'COMPANY~POSITIVE~ENTRYNO' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION

union all

SELECT 'PHYSINVENTORYLEDGERENTRY'AS SRCTBLNAME, 
'NAVISIONHY' AS SYSTEMNAME, 
'EDW_INVENTORY_PHYSICAL_COUNT' AS TBLNAME, 
'PHY_INVTY_KEY' AS DEST_CHANGE_KEY, 
'PHYSINVENTORYLEDGERENTRY_CHANGES' AS SOURCE_CHANGE_TBL, 
'COMPANY~ENTRY_NO' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
NULL AS SRCTBLCONDITION
)