SELECT DISTINCT * FROM
(
SELECT 'VW_MAST' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_PRODUCT_BOM_PARENT' AS TBLNAME, 
'PROD_BOM_PRNT_KEY' AS DEST_CHANGE_KEY, 
'VW_MAST_CHANGES' AS SOURCE_CHANGE_TBL, 
'MATNR~WERKS~STLAN~STLNR~STLAL' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_MAST A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'VW_T001L' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME, 
'INVTY_SLOC_KEY' AS DEST_CHANGE_KEY, 
'VW_T001L_CHANGES' AS SOURCE_CHANGE_TBL, 
'LGORT~WERKS' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_T001L A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'VW_RKPF' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_INVENTORY_RESERVATION_HEADER' AS TBLNAME, 
'INVTY_RSRV_HDR_KEY' AS DEST_CHANGE_KEY, 
'VW_RKPF_CHANGES' AS SOURCE_CHANGE_TBL, 
'RSNUM' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_RKPF A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_LTAP' AS SRCTBLNAME,
 'SAPE03' AS SYSTEMNAME, 
 'EDW_WAREHOUSE_TRANSFER_ORDER_LINE' AS TBLNAME, 
 'WHSE_TRNSFR_ORD_LN_KEY' AS DEST_CHANGE_KEY, 
 'VW_LTAP_CHANGES' AS SOURCE_CHANGE_TBL,
 'TANUM~TAPOS~LGNUM' AS SOURCE_CHANGE_KEY,
 'SCD2' AS SCDTYPE,
 '@@DBNAME.SAPE03.VW_LTAP A where A.MANDT = ''320''' AS SRCTBLCONDITION
union all 

SELECT 'VW_MARD' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_INVENTORY_ON_HAND_SNAPSHOT' AS TBLNAME, 
'INVTY_ON_HAND_SNAPSHOT_KEY' AS DEST_CHANGE_KEY, 
'VW_MARD_CHANGES' AS SOURCE_CHANGE_TBL, 
'MATNR~WERKS~LGORT' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_MARD A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'VW_MARDH' AS SRCTBLNAME, 
'SAPE03_BACK' AS SYSTEMNAME, 
'EDW_INVENTORY_ON_HAND_SNAPSHOT' AS TBLNAME, 
'INVTY_ON_HAND_SNAPSHOT_KEY' AS DEST_CHANGE_KEY, 
'VW_MARD_CHANGES' AS SOURCE_CHANGE_TBL, 
'MATNR~WERKS~LGORT~LFGJA~LFMON' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_MARDH A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'VW_RESB' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_INVENTORY_RESERVATION_DETAIL' AS TBLNAME, 
'INVTY_RSRV_DTL_KEY' AS DEST_CHANGE_KEY, 
'VW_RESB_CHANGES' AS SOURCE_CHANGE_TBL, 
'RSNUM~RSPOS~RSART' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_RESB A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'VW_MKPF' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_INVENTORY_MOVEMENT_HEADER' AS TBLNAME, 
'INVTY_MVMNT_HDR_KEY' AS DEST_CHANGE_KEY, 
'VW_MKPF_CHANGES' AS SOURCE_CHANGE_TBL, 
'MBLNR~MJAHR' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_MKPF A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'VW_MSEG' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_INVENTORY_MOVEMENT_LINE' AS TBLNAME, 
'INVTY_MVMNT_LN_KEY' AS DEST_CHANGE_KEY, 
'VW_MSEG_CHANGES' AS SOURCE_CHANGE_TBL, 
'MBLNR~MJAHR~ZEILE' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_MSEG A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'STPO' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_PRODUCT_BOM_COMPONENT' AS TBLNAME, 
'PROD_BOM_CMPNT_KEY' AS DEST_CHANGE_KEY, 
'VW_STPO_CHANGES' AS SOURCE_CHANGE_TBL, 
'STLNR~STLKN~STLTY~STPOZ' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_STPO A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION
union all

SELECT 'VW_LTAK' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER' AS TBLNAME, 
'WHSE_TRNSFR_ORD_HDR_KEY' AS DEST_CHANGE_KEY, 
'VW_LTAK_CHANGES' AS SOURCE_CHANGE_TBL, 
'LGNUM~TANUM' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_LTAK A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_IKPF' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_INVENTORY_PHYSICAL_COUNT' AS TBLNAME, 
'PHY_INVTY_KEY' AS DEST_CHANGE_KEY, 
'VW_IKPF_CHANGES' AS SOURCE_CHANGE_TBL, 
'IBLNR~GJAHR' AS SOURCE_CHANGE_KEY, 
'SCD2' AS SCDTYPE ,
'@@DBNAME.SAPE03.VW_IKPF A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION
)
