SELECT DISTINCT * FROM
(
SELECT 'VW_RESPROJSTATIC' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_RESOURCE_PROJECTION' AS TBLNAME,
'SUPPLY_PLNG_RESOURCE_PROJECTION_KEY' AS DEST_CHANGE_KEY,
'VW_RESPROJSTATIC' AS SOURCE_CHANGE_TBL,
'LOC~OPTIONSET~RES~STARTDATE' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_VEHICLELOADLINE' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_VEHICLE_LOAD_LINE' AS TBLNAME,
'VHCL_LOD_LN_KEY' AS DEST_CHANGE_KEY,
'VW_VEHICLELOADLINE' AS SOURCE_CHANGE_TBL,
'LOADID~PRIMARYITEM~EXPDATE~ITEM~DEST' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_RESLOADDETAIL' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_RESOURCE_LOAD_DETAILS' AS TBLNAME,
'RESOURCE_LOD_DETAILS_KEY' AS DEST_CHANGE_KEY,
'VW_RESLOADDETAIL' AS SOURCE_CHANGE_TBL,
'DMDORDERTYPE~DMDORDERSEQNUM~SUPPLYSEQNUM~WHENLOADED~STEPNUM~PRODUCTIONMETHOD~SUPPLYTYPE~RES~LOC~ITEM' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_PLANORDER' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNED_ORDER' AS TBLNAME,
'SUPPLY_PLND_ORD_KEY' AS DEST_CHANGE_KEY,
'VW_PLANORDER' AS SOURCE_CHANGE_TBL,
'ITEM~LOC~SEQNUM' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_PRODUCTIONMETHOD' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_PRODUCTION_METHOD' AS TBLNAME,
'PRODTN_MTHD_KEY' AS DEST_CHANGE_KEY,
'VW_PRODUCTIONMETHOD' AS SOURCE_CHANGE_TBL,
'PRODUCTIONMETHOD~ITEM~LOC' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_DFUEXCEPTION' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_DEMAND_FORECASTING_EXCEPTION' AS TBLNAME,
'DMD_FCST_EXCEPTION_KEY' AS DEST_CHANGE_KEY,
'VW_DFUEXCEPTION' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~MODEL~FUNCTIONNAME~EXCEPTION~FUNCTIONNUM' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_BOM' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_BOM_VIEW' AS TBLNAME,
'SUPPLY_PLNG_PROD_BOM_VW_KEY' AS DEST_CHANGE_KEY,
'VW_BOM' AS SOURCE_CHANGE_TBL,
'ITEM~SUBORD~LOC~BOMNUM~EFF~OFFSET' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_PRODUCTIONSTEP' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_PRODUCTION_METHOD_STEP' AS TBLNAME,
'PRODTN_MTHD_STEP_KEY' AS DEST_CHANGE_KEY,
'VW_PRODUCTIONSTEP' AS SOURCE_CHANGE_TBL,
'PRODUCTIONMETHOD~STEPNUM~ITEM~LOC~EFF' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_DFUMAP' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_DEMAND_FORECASTING_UNIT_MAP' AS TBLNAME,
'DMD_FORECASTING_UNIT_MAP_KEY' AS DEST_CHANGE_KEY,
'VW_DFUMAP' AS SOURCE_CHANGE_TBL,
'FROMDFULOC~FROMDMDGROUP~FROMDMDUNIT~FROMMODEL~MAP~TODFULOC~TODMDGROUP~TODMDUNIT~EFF' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_SKUPROJSTATIC' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_PROJECTION' AS TBLNAME,
'SUPPLY_PLNG_PROD_PROJECTION_KEY' AS DEST_CHANGE_KEY,
'VW_SKUPROJSTATIC' AS SOURCE_CHANGE_TBL,
'ITEM~LOC~OPTIONSET~STARTDATE' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_CAL' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_PLANNING_CALENDAR' AS TBLNAME,
'PLNG_CLNDR_KEY' AS DEST_CHANGE_KEY,
'VW_CAL' AS SOURCE_CHANGE_TBL,
'CAL' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_DFU' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_DEMAND_FORECASTING_UNIT' AS TBLNAME,
'DMD_FORCAST_UNIT_KEY' AS DEST_CHANGE_KEY,
'VW_DFU' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~MODEL' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_DFUTOSKUFCST' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_DFU_SKU_FORECAST' AS TBLNAME,
'DFU_SKU_FCST_KEY' AS DEST_CHANGE_KEY,
'VW_DFUTOSKUFCST' AS SOURCE_CHANGE_TBL,
'ITEM~SKULOC~DMDUNIT~DMDGROUP~DFULOC~STARTDATE~DUR~TYPE~SUPERSEDESW' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_CUST' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_CUSTOMER' AS TBLNAME,
'CUST_KEY' AS DEST_CHANGE_KEY,
'VW_CUST' AS SOURCE_CHANGE_TBL,
'CUST' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_SKUEXCEPTION' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SKU_EXCEPTION' AS TBLNAME,
'SKU_EXCEPTION_KEY' AS DEST_CHANGE_KEY,
'VW_SKUEXCEPTION' AS SOURCE_CHANGE_TBL,
'FUNCTIONNUM~LEVELNUM~PROCESSID~SEQNUM~BATCHNUM' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_RESEXCEPTION' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_RES_EXCEPTION' AS TBLNAME,
'RES_EXCEPTION_KEY' AS DEST_CHANGE_KEY,
'VW_RESEXCEPTION' AS SOURCE_CHANGE_TBL,
'FUNCTIONNUM~PROCESSID~SEQNUM~BATCHNUM' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_INTERR_HIST' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_INTERR_HIST' AS TBLNAME,
'INTERR_HIST_KEY' AS DEST_CHANGE_KEY,
'VW_INTERR_HIST' AS SOURCE_CHANGE_TBL,
'ERROR_STAMP~ERROR_STR~DMDUNIT~DMDGROUP~LOC~HISTSTREAM~EVENT~STARTDATE~TYPE~INTEGRATION_STAMP~INTEGRATION_JOBID' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_TARGET' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_TARGET' AS TBLNAME,
'TARGET_KEY' AS DEST_CHANGE_KEY,
'VW_TARGET' AS SOURCE_CHANGE_TBL,
'TARGET~TARGET' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_CUSTORDER' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_CUSTOMER_ORDER' AS TBLNAME,
'CUST_ORD_KEY' AS DEST_CHANGE_KEY,
'VW_CUSTORDER' AS SOURCE_CHANGE_TBL,
'ITEM~LOC~ORDERID~SHIPDATE' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_DMDGROUP' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_DEMAND_GROUP' AS TBLNAME,
'DMD_GRP_KEY' AS DEST_CHANGE_KEY,
'VW_DMDGROUP' AS SOURCE_CHANGE_TBL,
'DMDGROUP' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_LOC' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_LOCATION' AS TBLNAME,
'LOC_KEY' AS DEST_CHANGE_KEY,
'VW_LOC' AS SOURCE_CHANGE_TBL,
'LOC' AS SOURCE_CHANGE_KEY ,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_HIST' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_DEMAND_SALES_HISTORY' AS TBLNAME,
'DMD_SLS_HIST_KEY' AS DEST_CHANGE_KEY,
'VW_HIST' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~HISTSTREAM~STARTDATE~TYPE~EVENT' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_NETWORK' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_NETWORK' AS TBLNAME,
'NETWORK_KEY' AS DEST_CHANGE_KEY,
'VW_NETWORK' AS SOURCE_CHANGE_TBL,
'SOURCE~TRANSMODE~DEST' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_RES' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_RESOURCE' AS TBLNAME,
'RESOURCE_KEY' AS DEST_CHANGE_KEY,
'VW_RES' AS SOURCE_CHANGE_TBL,
'RES' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_SKUDEMANDPARAM' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_DEMAND_PARAMETER' AS TBLNAME,
'SUPPLY_PLNG_DMD_PARM_KEY' AS DEST_CHANGE_KEY,
'VW_SKUDEMANDPARAM' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_SKUPLANNINGPARAM' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SKU_PLANNING_PARAMETER' AS TBLNAME,
'SKU_PLNG_PARM_KEY' AS DEST_CHANGE_KEY,
'VW_SKUPLANNINGPARAM' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_SKUSAFETYSTOCKPARAM' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_SAFETY_STOCK_PARAMETER' AS TBLNAME,
'SUPPLY_PLNG_SFTY_STK_PARM_KEY' AS DEST_CHANGE_KEY,
'VW_SKUSAFETYSTOCKPARAM' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_SOURCING' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_SOURCING' AS TBLNAME,
'SUPPLY_PLNG_PROD_SOURCING_KEY' AS DEST_CHANGE_KEY,
'VW_SOURCING' AS SOURCE_CHANGE_TBL,
'ITEM~DEST~SOURCE~SOURCING' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_VEHICLELOAD' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_VEHICLE_LOAD_HEADER' AS TBLNAME,
'VHCL_LOD_HDR_KEY' AS DEST_CHANGE_KEY,
'VW_VEHICLELOAD' AS SOURCE_CHANGE_TBL,
'LOADID' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_DFUTOSKU' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_DFU_SKU_ASSOCIATION' AS TBLNAME,
'DFU_SKU_ASSOC_KEY' AS DEST_CHANGE_KEY,
'VW_DFUTOSKU' AS SOURCE_CHANGE_TBL,
'ITEM~SKULOC~DMDUNIT~DMDGROUP~DFULOC~EFF~DISC' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_SKUEXTERNALFCST' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SKU_EXTERNAL_FCST' AS TBLNAME,
'SKU_EXTERNAL_FCST_KEY' AS DEST_CHANGE_KEY,
'VW_SKUEXTERNALFCST' AS SOURCE_CHANGE_TBL,
'ITEM~LOC~STARTDATE~PROJECT' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_FCSTPERFSTATIC' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_FCST_PERF_STATIC' AS TBLNAME,
'FCST_PERF_STATIC_KEY' AS DEST_CHANGE_KEY,
'VW_FCSTPERFSTATIC' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~MODEL~FCSTDATE~STARTDATE~DUR' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_TARGETDFUMAP' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_TARGET_DFU_MAP' AS TBLNAME,
'TARGET_DFU_MAP_KEY' AS DEST_CHANGE_KEY,
'VW_TARGETDFUMAP' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~MODEL~TARGET' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_MODEL' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_MODEL' AS TBLNAME,
'MODEL_KEY' AS DEST_CHANGE_KEY,
'VW_MODEL' AS SOURCE_CHANGE_TBL,
'MODEL' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_PLANARRIV' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SUPPLY_PLAN_ARRIVAL' AS TBLNAME,
'SUPPLY_PLN_ARRVL_KEY' AS DEST_CHANGE_KEY,
'VW_PLANARRIV' AS SOURCE_CHANGE_TBL,
'SEQNUM~ITEM~DEST' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION 

UNION ALL

SELECT 'VW_ITEM' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_PRODUCT' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'VW_ITEM' AS SOURCE_CHANGE_TBL,
'ITEM' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
'@@DBNAME.BLUEYONDER.VW_ITEM as a
LEFT JOIN @@DBNAME.BLUEYONDER.VW_DMDUNIT as D
On a.ITEM=D.DMDUNIT' AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_HISTFCST' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_DEMAND_FORECAST_HISTORY' AS TBLNAME,
'DMD_FCST_HIST_KEY' AS DEST_CHANGE_KEY,
'VW_HISTFCST' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~MODEL~FCSTDATE~STARTDATE' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_FCST' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_DEMAND_FORECAST' AS TBLNAME,
'DMD_FCST_KEY' AS DEST_CHANGE_KEY,
'VW_FCST' AS SOURCE_CHANGE_TBL,
'DMDUNIT~DMDGROUP~LOC~STARTDATE~TYPE~FCSTID~MODEL' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_SKU' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_VIEW' AS TBLNAME,
'SUPPLY_PLNG_PROD_VW_KEY' AS DEST_CHANGE_KEY,
'VW_SKU' AS SOURCE_CHANGE_TBL,
'ITEM~LOC' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_DMDUNIT' AS SRCTBLNAME,
'BLUEYONDER' AS SYSTEMNAME,
'EDW_PRODUCT_HIERARCHY' AS TBLNAME,
'PROD_KEY' AS DEST_CHANGE_KEY,
'VW_DMDUNIT' AS SOURCE_CHANGE_TBL,
'DMDUNIT' AS SOURCE_CHANGE_KEY,
'SCD2' AS SCDTYPE,
NULL AS SRCTBLCONDITION

)
