SELECT DISTINCT * FROM
(
SELECT 'HIST' AS SRCTBLNAME,'JDA' AS SYSTEMNAME,'EDW_DEMAND_SALES_HISTORY' AS TBLNAME,NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'CURRENCYPROFILEVAL' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_CURRENCY_PROFILE' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'DEMANDGROUP' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_GROUP' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'DFUEXCEPTION' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_FORECASTING_EXCEPTION' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'DFUMAP' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_FORECASTING_UNIT_MAP' AS TBLNAME,
NULL AS SRCTBLCONDITION
union ALL
SELECT 'FCST' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_FORECAST' AS TBLNAME,
NULL AS SRCTBLCONDITION
union ALL
SELECT 'PRODUCTIONSTEP' AS SRCTBLNAME,'JDA' AS SYSTEMNAME,'EDW_PRODUCTION_METHOD_STEP'  AS TBLNAME ,NULL AS SRCTBLCONDITION  
union ALL
SELECT 'VEHICLELOAD' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_VEHICLE_LOAD_HEADER'  AS TBLNAME ,
NULL AS SRCTBLCONDITION 
UNION ALL
SELECT 'RESPROJSTATIC' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_RESOURCE_PROJECTION' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'SKUDEMANDPARAM' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_DEMAND_PARAMETER' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'DFUTOSKU' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DFU_SKU_ASSOCIATION' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'SOURCING' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_SOURCING' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'VEHICLELOADLINE' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_VEHICLE_LOAD_LINE'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'PRICEPROFILEVAL' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_PRICE_PROFILE' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'SKUSAFETYSTOCKPARAM' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_SAFETY_STOCK_PARAMETER'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'F3003' AS SRCTBLNAME,
'JDEEF' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT'  AS TBLNAME ,
NULL AS SRCTBLCONDITION

UNION ALL
SELECT 'CAL' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_PLANNING_CALENDAR' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'ITEM' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_PRODUCT'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'DMDUNIT' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_PRODUCT'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'RECSHIP' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNED_RECOMMENDED_SHIPMENT'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'PLANORDER' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNED_ORDER'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'SKUDISPLAY' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_VIEW'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'SKU' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_VIEW'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'RES' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_RESOURCE'  AS TBLNAME ,
NULL AS SRCTBLCONDITION 
UNION ALL
SELECT 'RESLOADDETAIL' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_RESOURCE_LOAD_DETAILS'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'PRODUCTIONMETHOD' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_PRODUCTION_METHOD'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'NETWORK' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_NETWORK'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'TRANSFER' AS SRCTBLNAME,
'SLIES' AS SYSTEMNAME,
'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
union ALL
SELECT 'MAST' AS SRCTBLNAME,'SAPSHP' AS SYSTEMNAME,'EDW_PRODUCT_BOM_PARENT'  AS TBLNAME 
,NULL AS SRCTBLCONDITION 
union ALL
SELECT 'T001L' AS SRCTBLNAME,'SAPSHP' AS SYSTEMNAME,'EDW_INVENTORY_STORAGE_LOCATION'  AS TBLNAME 
,NULL AS SRCTBLCONDITION 
UNION ALL
SELECT 'cnttyp' AS SRCTBLNAME,
'jdawms' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT_CLASS'  AS TBLNAME ,
NULL AS SRCTBLCONDITION 
union ALL
SELECT 'RKPF' AS SRCTBLNAME,'SAPSHP' AS SYSTEMNAME,'EDW_INVENTORY_RESERVATION_HEADER'  AS TBLNAME 
,NULL AS SRCTBLCONDITION 
UNION ALL
SELECT 'VW_STKO' AS SRCTBLNAME,
'SAPC11' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_PARENT'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_STKO A where A.STLTY = ''M''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_STKO' AS SRCTBLNAME,
'SAPE03' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_PARENT'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_STKO A where A.STLTY = ''M''' AS SRCTBLCONDITION 
UNION ALL
SELECT 'VW_STKO' AS SRCTBLNAME,
'SAPP10' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_PARENT'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_STKO A where A.STLTY = ''M''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_T001L' AS SRCTBLNAME,
'SAPC11' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_T001L A WHERE A.MANDT= ''040''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_T001L' AS SRCTBLNAME,
'SAPP10' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION'  AS TBLNAME ,
'@@DBNAME.SAPP10.VW_T001L A WHERE A.MANDT= ''100''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_T001L' AS SRCTBLNAME,
'SAPE03' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION'  AS TBLNAME ,
'@@DBNAME.SAPE03.VW_T001L A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_RKPF' AS SRCTBLNAME,
'SAPE03' AS SYSTEMNAME,
'EDW_INVENTORY_RESERVATION_HEADER'  AS TBLNAME ,
'@@DBNAME.SAPE03.VW_T001L A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_RKPF' AS SRCTBLNAME,
'SAPP10' AS SYSTEMNAME,
'EDW_INVENTORY_RESERVATION_HEADER'  AS TBLNAME ,
'@@DBNAME.SAPP10.VW_T001L A WHERE A.MANDT= ''100''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_RKPF' AS SRCTBLNAME,
'SAPC11' AS SYSTEMNAME,
'EDW_INVENTORY_RESERVATION_HEADER'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_T001L A WHERE A.MANDT= ''040''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_LTAP' AS SRCTBLNAME,
'SAPC11' AS SYSTEMNAME,
'EDW_WAREHOUSE_TRANSFER_ORDER_LINE' AS TBLNAME,
'@@DBNAME.SAPC11.VW_LTAP A WHERE A.MANDT= ''040''' SRCTBLCONDITION
UNION ALL
SELECT 'VW_LTAP' AS SRCTBLNAME,
'SAPE03' AS SYSTEMNAME,
'EDW_WAREHOUSE_TRANSFER_ORDER_LINE' AS TBLNAME,
'@@DBNAME.SAPE03.VW_LTAP A WHERE A.MANDT= ''320''' SRCTBLCONDITION
UNION ALL
SELECT 'UDT_SKUPROJSTATIC_WEEKLY' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_SUPPLY_PLANNING_PRODUCT_PROJECTION'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'MBM' AS SRCTBLNAME,
'INFORLX' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'BDPSMSTR' AS SRCTBLNAME,
'QADPE' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'PSMSTR' AS SRCTBLNAME,
'QADDE' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_LTAK' AS SRCTBLNAME,
'SAPC11' AS SYSTEMNAME,
'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_LTAK A WHERE A.MANDT= ''040''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_LTAK' AS SRCTBLNAME,
'SAPP10' AS SYSTEMNAME,
'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER'  AS TBLNAME ,
'@@DBNAME.SAPP10.VW_LTAK A WHERE A.MANDT= ''100''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_LTAK' AS SRCTBLNAME,
'SAPE03' AS SYSTEMNAME,
'EDW_WAREHOUSE_TRANSFER_ORDER_HEADER'  AS TBLNAME ,
'@@DBNAME.SAPE03.VW_LTAK A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_LTAP' AS SRCTBLNAME,
'SAPP10' AS SYSTEMNAME,
'EDW_WAREHOUSE_TRANSFER_ORDER_LINE' AS TBLNAME,
'@@DBNAME.SAPP10.VW_LTAP A WHERE A.MANDT= ''100''' SRCTBLCONDITION

UNION ALL

SELECT 'RESERVATIONENTRY' AS SRCTBLNAME,
'NAVISIONHY' AS SYSTEMNAME,
'EDW_INVENTORY_RESERVATION_HEADER'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'VW_MSEG' AS SRCTBLNAME,
'SAPC11' AS SYSTEMNAME,
'EDW_INVENTORY_MOVEMENT_LINE'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_MSEG A WHERE A.MANDT= ''040''' AS SRCTBLCONDITION

union all 

SELECT 'RESB' AS SRCTBLNAME, 
'SAPC11' AS SYSTEMNAME, 
'EDW_INVENTORY_RESERVATION_DETAIL' AS TBLNAME, 
'@@DBNAME.SAPC11.RESB A WHERE A.MANDT= ''40''' AS SRCTBLCONDITION

union all 

SELECT 'VW_RESB' AS SRCTBLNAME, 
'SAPE03' AS SYSTEMNAME, 
'EDW_INVENTORY_RESERVATION_DETAIL' AS TBLNAME, 
'@@DBNAME.SAPE03.VW_RESB A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'VW_RESB' AS SRCTBLNAME, 
'SAPP10' AS SYSTEMNAME, 
'EDW_INVENTORY_RESERVATION_DETAIL' AS TBLNAME, 
'@@DBNAME.SAPP10.VW_RESB A WHERE A.MANDT= ''100''' AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_MSEG' AS SRCTBLNAME,
'SAPP10' AS SYSTEMNAME,
'EDW_INVENTORY_MOVEMENT_LINE'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_MSEG A WHERE A.MANDT= ''100''' AS SRCTBLCONDITION

UNION ALL
SELECT 'VW_MSEG' AS SRCTBLNAME,
'SAPE03' AS SYSTEMNAME,
'EDW_INVENTORY_MOVEMENT_LINE'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_MSEG A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'IPH' AS SRCTBLNAME,
'INFORLX' AS SYSTEMNAME,
'EDW_INVENTORY_PHYSICAL_COUNT' AS TBLNAME,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'F4140' AS SRCTBLNAME,
'JDEEF' AS SYSTEMNAME,
'EDW_INVENTORY_CYCLE_COUNT_CLASS'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'STPO' AS SRCTBLNAME,
'SAPC11' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_STPO A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION
UNION ALL
SELECT 'STPO' AS SRCTBLNAME,
'SAPP10' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT'  AS TBLNAME ,
'@@DBNAME.SAPP10.VW_STPO A WHERE A.MANDT= ''100''' AS SRCTBLCONDITION
UNION ALL
SELECT 'STPO' AS SRCTBLNAME,
'SAPE03' AS SYSTEMNAME,
'EDW_PRODUCT_BOM_COMPONENT'  AS TBLNAME ,
'@@DBNAME.SAPE03.VW_STPO A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

union all 

SELECT 'WMWMSMP' AS SRCTBLNAME,
'LAWSONMAC' AS SYSTEMNAME,
'EDW_INVENTORY_STORAGE_LOCATION' AS TBLNAME,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'CHECKVOUCHS' AS SRCTBLNAME,
'UFIDA' AS SYSTEMNAME,
'EDW_INVENTORY_PHYSICAL_COUNT'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
UNION ALL
SELECT 'DFU' AS SRCTBLNAME,
'JDA' AS SYSTEMNAME,
'EDW_DEMAND_FORECASTING_UNIT'  AS TBLNAME ,
NULL AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_IKPF' AS SRCTBLNAME,
'SAPC11' AS SYSTEMNAME,
'EDW_INVENTORY_PHYSICAL_COUNT'  AS TBLNAME ,
'@@DBNAME.SAPC11.VW_IKPF A WHERE A.MANDT= ''040''' AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_IKPF' AS SRCTBLNAME,
'SAPE03' AS SYSTEMNAME,
'EDW_INVENTORY_PHYSICAL_COUNT'  AS TBLNAME ,
'@@DBNAME.SAPE03.VW_IKPF A WHERE A.MANDT= ''320''' AS SRCTBLCONDITION

UNION ALL

SELECT 'VW_IKPF' AS SRCTBLNAME,
'SAPP10' AS SYSTEMNAME,
'EDW_INVENTORY_PHYSICAL_COUNT'  AS TBLNAME ,
'@@DBNAME.SAPP10.VW_IKPF A WHERE A.MANDT= ''100''' AS SRCTBLCONDITION

UNION ALL
SELECT 'BDRESERVA' AS SRCTBLNAME,
'QADBR' AS SYSTEMNAME,
'EDW_INVENTORY_RESERVATION_HEADER'  AS TBLNAME ,
NULL AS SRCTBLCONDITION
)