select 
UPPER(tagmstr.tag_nbr) as PHY_INVTY_KEY,
'QADBR' AS  {{var('column_srcsyskey')}},
MD5(UPPER(tagmstr.tag_nbr)) AS  {{var('column_rechashkey')}},
{{var('default_n')}} as {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS  {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS  {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_UPD_DTE')}},
tagmstr.LOADDTS AS  {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS  {{var('column_verexpirydt')}},
{{var('default_y')}} as {{var('column_currrecflag')}},
{{var('default_n')}} as {{var('column_orprecflag')}},
tagmstr.LOADDTS AS  {{var('column_z3loddtm')}},
tagmstr.tag_cnt_nam as CNT_NAME,
case when UPPER(tagmstr.tag_void)='YES' then 'Y' else 'N' end PROD_TAG_PROC_FLAG,
tagmstr.tag_cnt_cnv AS CNT_QTY_CONV_FACTOR,
TRY_TO_DATE(tagmstr.tag_cnt_dt,'MM/DD/YY') AS CNT_DTE,
tagmstr.tag_cnt_qty AS CNT_QTY,
tagmstr.tag_cnt_um as CNT_UOM_ID,
TRY_TO_DATE(tagmstr.tag_crt_dt,'MM/DD/YY') AS CNT_CREATE_DTE,
case when length(trim(tagmstr.tag_loc)) <1 then {{var('default_mapkey')}} when tagmstr.tag_loc IS NULL then {{var('default_mapkey')}} else (tagmstr.tag_loc) end as CNT_SUB_LOC_KEY,
tagmstr.tag_nbr AS PHY_INVTY_CNT_NBR,
case when length(trim(tagmstr.tag_part)) <1 then {{var('default_mapkey')}} when tagmstr.tag_part IS NULL then {{var('default_mapkey')}} else (tagmstr.tag_part) end as CNT_PROD_KEY,
case when UPPER(tagmstr.tag_posted)='YES' then 'Y' else 'N' end TAG_POST_FLAG,
tagmstr.tag_rcnt_cnv AS RECOUNT_CONV_FACTOR,
TRY_TO_DATE(tagmstr.tag_rcnt_dt,'MM/DD/YY') AS RECOUNT_DTE,
tagmstr.tag_rcnt_qty AS RECOUNT_QTY,
tagmstr.tag_rcnt_um as RECOUNT_CONV_FACTOR_UOM_ID,
tagmstr.tag_ref AS TAG_REF_NBR,
case when length(trim(tagmstr.tag_site)) <1 then {{var('default_mapkey')}} when tagmstr.tag_site IS NULL then {{var('default_mapkey')}} else (tagmstr.tag_site) end as TAG_LOC_KEY,
case when length(trim(tagmstr.tag_type)) <1 then {{var('default_mapkey')}} when tagmstr.tag_type IS NULL then {{var('default_mapkey')}} else (tagmstr.tag_type) end as TAG_CNT_TYP_LKEY
from {{source('QADBR','TAGMSTR')}} tagmstr 