create or replace TABLE PROD_EDW.CONSOLIDATED.EDW_SUPPLY_PLANNING_PRODUCT_VIEW (
	SUPPLY_PLNG_PROD_VW_KEY VARCHAR(255) NOT NULL COMMENT 'SKUDISPLAY has been derived from combination of the source column ITEM and LOC\nSKU  has been derived from combination of the source column ITEM and LOC',
	SRC_SYS_KEY VARCHAR(255) NOT NULL COMMENT 'Identifies the origin of data source, in other word source system from where data is brought. The Key will be available in Source System table where one entry will exist for each participating system.',
	SRC_RCRD_CREATE_DTE TIMESTAMP_NTZ(9) COMMENT 'Date and time when this record was created at source system table (driver table in case of multiple table/files are involved). ',
	SRC_RCRD_CREATE_USERID VARCHAR(255) COMMENT 'The ID of the user who created the record at the at source system table (driver table in case of multiple table/files are involved).',
	SRC_RCRD_UPD_DTE TIMESTAMP_NTZ(9) COMMENT 'Date and time when this record was updated at source system table (driver table in case of multiple table/files are involved).',
	SRC_RCRD_UPD_USERID VARCHAR(255) COMMENT 'The ID of the user who updated the record at the at source system table (driver table in case of multiple table/files are involved).',
	RCRD_HASH_KEY VARCHAR(255) COMMENT 'The hash value (MD5/SHA256/etc.) of the qualified columns, that is considered to be different to enable versioning of record, will be stored in this column. ',
	DEL_FROM_SRC_FLAG VARCHAR(1) COMMENT 'When it is detected that the record has been deleted from the source table, then the corresponding record at target is marked as delete (soft delete) setting the flag as “Y” ',
	ETL_INS_PID VARCHAR(255) COMMENT 'Contains information about the ETL/ELT job & package which has created the record',
	ETL_INS_DTE TIMESTAMP_NTZ(9) COMMENT 'Date and time when this record is created or inserted at the target table. ',
	ETL_UPD_PID VARCHAR(255) COMMENT 'Contains information about the ETL/ELT job & package which has updated the record last time',
	ETL_UPD_DTE TIMESTAMP_NTZ(9) COMMENT 'Date and time when this record is updated last time at the target table.',
	ZONE3_LOD_DTE TIMESTAMP_NTZ(9) COMMENT 'Zone3 Load DateTime (This will be used in ETL load from Zone 3 to Snowflake)',
	EFF_DTE TIMESTAMP_NTZ(9) COMMENT 'Date and time when this version of the record is created and become effective ',
	EXPR_DTE TIMESTAMP_NTZ(9) COMMENT 'Date and time when this version of the record has expired and no longer effective created at the target',
	CURR_RCRD_FLAG VARCHAR(1) COMMENT 'This flag Indicates if the version of record is current or obsolete. “Y” indicates that the record is current and “N” indicates the record is obsolete or old. ',
	ORP_RCRD_FLAG VARCHAR(1) COMMENT 'This flag indicates if the record is orphan (not originated from source). “Y” indicates that the record is orphan, and some program has created this record with missing/dummy key value in the Master/Reference table to maintain integrity. When the actual record arrives from its parent source, the column values are updated and this flag is set as “N”.',
	BKORD_QTY NUMBER(28,10) COMMENT 'Back Order Quantity',
	PROD_KEY VARCHAR(255) COMMENT 'Product Key',
	AVAIL_PROMISE_QTY NUMBER(28,10) COMMENT 'C11 Only:\nC11: SAP Transaction Code:  CO09\nSelection Screen parameters\n              Material\n              Plant\nCheck ATP(Available to Promise) qty. It is derived from Source System',
	BOH_6_MTHS_AVG VARCHAR(255) COMMENT '6mnth BOH Hist avg (BOH - Balance On Hand)',
	BOH_8_WKS_AVG VARCHAR(255) COMMENT '8wk BOH Hist avg',
	CASE_QTY NUMBER(28,10) COMMENT 'SAP Transaction Code:  MM03. Derived from Source System\nMM03 -> BASIC 1 ->  Additional Data ->  Unit of Measure',
	CURR_GRS_SLS_VAL VARCHAR(255) COMMENT 'Current Gross Sales Value ',
	REMOVING_PROMOS_6_MTHS_AVG VARCHAR(255) COMMENT '6mnth AVG removing Promos - subtracts from History qty , the events qty from Histfcst (internalevents + externalevents',
	REMOVING_PROMOS_8_WKS_AVG VARCHAR(255) COMMENT '8wk AVG removing Promos - subtracts from History qty , the events qty from Histfcst (internalevents + externalevents',
	LONG_DESC VARCHAR(2000) COMMENT 'Long Description',
	REPLCE_PROD_ID VARCHAR(255) COMMENT 'The recommended replacement item. Derived from ERP - MARC ',
	GRS_SLS_VAL VARCHAR(255) COMMENT 'Gross Sales Value in USD ',
	INVTY_OPTIMIZATION_DSCTU_DTE TIMESTAMP_NTZ(9) COMMENT 'Inventory Optimization Discontinue Date',
	INVTY_OPTIMIZATION_GRS_SLS_VAL VARCHAR(255) COMMENT 'Inventory Optimization Gross Sales Value for Demand ',
	LAST_MOVE_DTE TIMESTAMP_NTZ(9) COMMENT 'Last time an inventory movement took place from SAP (C11/E03). Derived from Source System',
	PLNR_CD_CNTCT_NAME VARCHAR(255) COMMENT 'Plannercode of local (in the marketperson that can help if Marketplanner is not available). User maintained',
	ULTM_SRC_LEADTIME_DUR NUMBER(28,10) COMMENT 'Lead time to ultimate source in days',
	MKT_PLNR VARCHAR(255) COMMENT 'Code assigned to the responsible planner for the location. Derived from Source System. Maintained in ERP for loctype 1-2;For loctype 4 the values need to be maintained in JDA',
	SUPPLY_SRC_LOC_ID VARCHAR(255) COMMENT 'The source of supply for the specifc location. Scripted in JDA',
	UOM_ID VARCHAR(255) COMMENT 'MM03 -> BASIC 1 ->  Additional Data ->  Unit of Measure. This fields defines the Unit of measure. Derived from Source System',
	DYLY_DMD_AVG_QTY NUMBER(28,10) COMMENT 'The mean daily demand. User Maintained ',
	PRODTN_GRP VARCHAR(255) COMMENT 'field to identify ERP grouping',
	NEXT_SCHED_FREEZE_DUR NUMBER(28,10) COMMENT 'The duration at the plant that should be driven by S1R1 demand and event forecast. Supports S1R1  and Planning / Sched Solution.  Part of the cumulative replenishment lead time.  This represent the current freeze + what is going to be scheduled next.  This will work with Network:TransLeadTime to ensure that the plant only creates the next increment of the schedule against S1R1 demand + Event requirements.  Calculated at the Plant SKU. \nScripted in JDA\nNext Scheduled Freeze',
	PENDING_INVTY_ADJ VARCHAR(255) COMMENT 'Inventory not included in OH. Derived from Source System\nPending Inventory Adjustment',
	USER_PLNR_CMT_TEXT VARCHAR(2000) COMMENT 'Field for user comments at SKU level (50 char). User Maintained',
	PLANT_STAT VARCHAR(255) COMMENT 'MM03 -> MRP 1 -> General Data -> Plant-sp. Matl status. Derived from Source System',
	PLND_DLV_TM NUMBER(38,0) COMMENT 'For Third Party/GSMA this field dictates total Lead time (Manufacturing + Transit Time to Location); For Key Vendor it should represent the MFGpart of the sku.\nIt is recommended to have the U_Planned delivery time in multiples of 7D to work correctly together with the prodcal.\nUser maintained (replentype 2, 806, KV)',
	HIST_3_WKS_POS_AVG VARCHAR(255) COMMENT 'Average 3-week POS history, for POS planned DFUs',
	HIST_6_MTHS_POS_AVG VARCHAR(255) COMMENT 'Average 6-month POS history, for POS planned DFUs',
	HIST_8_WKS_POS_AVG VARCHAR(255) COMMENT 'Average 8-week POS history, for POS planned DFUs',
	FORCAST_6_MTHS_POS_AVG VARCHAR(255) COMMENT 'Average 6-month POS forecast, for POS planned DFUs',
	FORCAST_8_WKS_POS_AVG VARCHAR(255) COMMENT 'Average 8-week POS forecast, for POS planned DFUs',
	CURR_WK_POS_AVG VARCHAR(255) COMMENT 'Most recent POS that was received into BW for that week',
	QLTY_INSPCT_QTY NUMBER(28,10) COMMENT 'Inventory in a QI status in ERP. Derived from Source System\nQuantity in Quality Inspection',
	INCREMENTAL_REPL_QTY NUMBER(28,10) COMMENT 'The incremental ask or production quantity. User maintained\nIncremental Production Qty',
	MIN_REPL_QTY NUMBER(28,10) COMMENT 'The minimum ask or production quantity. User maintained\nMinimum Production Qty',
	S1R1 NUMBER(28,10) COMMENT 'Horizon at the destination that must be cleared of forecast to drive S1R1 demand and event forecasting at the shipping location\nScripted in JDA',
	REQ_FREEZE_PERD VARCHAR(255) COMMENT 'The Frozen Period as of Monday (MFG lock period) during this period JDA will not recalculate requirements \nUser Maintained\nRequirement Freeze Period',
	CNTRY_OF_ORIG VARCHAR(255) COMMENT 'Derived field from ERP to define CoO. Derived from Source System\nCountry of Origin',
	STD_COST NUMBER(28,10) COMMENT 'GSMA:\nMM03 -> Accounting 1 ->  Moving Price (MBEW - VERPR)\nMM03 -> Accounting 1 ->  Price Unit (MBEW - PEINH)\nOther than GSMA\nMM03 -> Accounting 1 ->  Standard Price (MBEW-STPRS)\nMM03 -> Accounting 1 -> Price Unit (MBEW-PEINH)',
	LEADTIME TIMESTAMP_NTZ(9) COMMENT 'Leadtime into first leadtime location. \nlead time',
	SRC_LOC_ID VARCHAR(255) COMMENT 'Identifies the source for the location.\nSource Location',
	UNITS_PER_PAL_QTY NUMBER(28,10) COMMENT 'Units Per Pallet. Derived from Source System',
	CNSGN_INVTY_TEXT VARCHAR(2000) COMMENT 'Derived from ERP if we have inventory at vendor in consignment \nConsignee Inventory',
	VEND_DESC VARCHAR(2000) COMMENT 'SAP Transaction Code: MK03 -->Selection Screen parameters --> Vendor, Purchasing Org and Check  Address  Check  Name (Vendor Description)\nDerived from Source System (replentype 2 or KV dest)\nVendor Description',
	PROD_VOL VARCHAR(255) COMMENT 'Volume from ERP. Derived from Source System',
	PROD_WGT NUMBER(28,10) COMMENT 'Weight from ERP. Derived from Source System',
	VEND_NBR VARCHAR(255) COMMENT 'The vendor from whom this part is procured. Its Vendor number',
	SKU_ID_NBR VARCHAR(255) COMMENT 'An abbreviation used on the application interface as a brief identifier for the SKU.',
	AGRT_GRS_REQ_QTY NUMBER(28,10) COMMENT 'Original Aggregate Gross Requirement (AGRORI) is the original AGR (Aggregate Gross Requirement) imported into the database.',
	SKU_BUYER_NAME VARCHAR(255) COMMENT 'The buyer for this SKU.',
	SKU_FAMILY_CD_NBR VARCHAR(255) COMMENT 'The family code for this SKU.',
	SKU_ISS_POLICY VARCHAR(255) COMMENT 'The issuing policy for this SKU.',
	SKU_PROD_GRP VARCHAR(255) COMMENT 'The item group for this SKU.',
	LABR_HRS_NBR VARCHAR(255) COMMENT 'The labor hours needed for this SKU.',
	SKU_PROD_TYP VARCHAR(255) COMMENT 'The material type used in this SKU.',
	ACT_ON_ORD_QTY NUMBER(28,10) COMMENT 'Stores the on-order quantity currently known by the Vendor Managed Inventory (VMI) partner for this\nSKU. The VMI planner uses this data for comparison with the\nexpected on-order quantity.',
	SKU_CD_PLNR VARCHAR(255) COMMENT 'The code of the planner in charge of the SKU',
	ABC_CD VARCHAR(255) COMMENT 'ABC CODE',
	ADD_S1R1 VARCHAR(255) COMMENT 'ADD S1R1',
	AUTO_REPLEN_TYP VARCHAR(255) COMMENT 'AUTO REPLEN TYPE',
	BOM_USAGE VARCHAR(255) COMMENT 'BOM USAGE',
	CNTRY_ABC_CD VARCHAR(255) COMMENT 'COUNTRY ABC CODE',
	CUST_HIER_1 VARCHAR(255) COMMENT 'CUST HIER 1',
	CUST_HIER_2 VARCHAR(255) COMMENT 'CUST HIER 2',
	CUST_HIER_3 VARCHAR(255) COMMENT 'CUST HIER 3',
	CUST_HIER_4 VARCHAR(255) COMMENT 'CUST HIER 4',
	CUST_PROD VARCHAR(255) COMMENT 'CUST ITEM',
	DEL_FLAG VARCHAR(1) COMMENT 'DELETE FLAG',
	DV_LEADTIME TIMESTAMP_NTZ(9) COMMENT 'DV LEAD TIME',
	ERP_STRAT_GRP VARCHAR(255) COMMENT 'ERP STRATEGY GROUP',
	INTER_CO_ONLY_FLAG VARCHAR(1) COMMENT 'INTER CO ONLY FLAG',
	IO_BATCH_PRFL VARCHAR(255) COMMENT 'IO BATCH PROFILE',
	IO_DV_LEADTIME TIMESTAMP_NTZ(9) COMMENT 'IO DV LEAD TIME',
	IO_OVRD_WMAPE VARCHAR(255) COMMENT 'IO OVRD WMAPE',
	IO_PLNR_PRFL VARCHAR(255) COMMENT 'IO PLANNER PROFILE',
	IO_SEASONAL_SKU VARCHAR(255) COMMENT 'IO SEASONAL SKU',
	IO_SKU_CLS VARCHAR(255) COMMENT 'IO SKU CLASS',
	IO_STRSW VARCHAR(255) COMMENT 'IO STRSW',
	IO_STRSW_OVER VARCHAR(255) COMMENT 'IO STRSW OVR',
	LIFE_CYCLE VARCHAR(255) COMMENT 'LIFE CYCLE',
	LOC_ABC_CD VARCHAR(255) COMMENT 'LOCATION ABC CODE',
	LOT_SZ_CD VARCHAR(255) COMMENT 'LOT SIZE KEY',
	LOT_SZ_KEY_DESC VARCHAR(2000) COMMENT 'LOT SIZE KEY DESCR',
	MAKE_BUY_SD VARCHAR(255) COMMENT 'MAKE BUY SD',
	MDD_COPY VARCHAR(255) COMMENT 'MDD COPY',
	MDD_UPD_RULE VARCHAR(255) COMMENT 'MDD UPD RULE',
	MINSS_EQ_OH VARCHAR(255) COMMENT 'MINSS EQ OH',
	MINSS_UPD VARCHAR(255) COMMENT 'MINSS UPDT',
	MINSS_COV VARCHAR(255) COMMENT 'MINSS COV',
	NEW_TO_JDA VARCHAR(255) COMMENT 'NEW TO JDA',
	NEW_TO_PRODTN VARCHAR(255) COMMENT 'NEW TO PRD',
	NEW_TO_SRC VARCHAR(255) COMMENT 'NEW TO SRC',
	NEXT_SCHED_STEP_DUR VARCHAR(255) COMMENT 'NEXT SCHED STEP DUR',
	OFFSET VARCHAR(255) COMMENT 'OFFSET',
	PLANT_CD_SD VARCHAR(255) COMMENT 'PLANT CODE SD',
	PROCUR_TYP VARCHAR(255) COMMENT 'PROCUREMENT TYPE',
	PRODTN_STEP_DY VARCHAR(255) COMMENT 'PROD STEP DAY',
	PROD_STAT VARCHAR(255) COMMENT 'PRODUCT STATUS',
	REGN_ABC_CD VARCHAR(255) COMMENT 'REGION ABC CODE',
	REGN_IND VARCHAR(255) COMMENT 'REGIONAL IND',
	REV_FLOW VARCHAR(255) COMMENT 'REV FLOW',
	RS_ALLOC_RULE VARCHAR(255) COMMENT 'RS ALLOC RULE',
	SHIP_LOGIC VARCHAR(255) COMMENT 'SHIP LOGIC',
	SKU_INTERFACE_ID VARCHAR(255) COMMENT 'SKU INTERFACE KEY',
	SKU_STAT VARCHAR(255) COMMENT 'SKU STATUS',
	SRC_PRYRT VARCHAR(255) COMMENT 'SOURCE PRIORITY',
	SS_TGT_MTHD VARCHAR(255) COMMENT 'SS TARGET METHOD',
	SUPPLY_STRAT VARCHAR(255) COMMENT 'SUPPLY STRATEGY',
	SURPLUS_COVER_DUR VARCHAR(255) COMMENT 'SURPLUS COV DUR',
	UOM VARCHAR(255) COMMENT 'UOM',
	UPD_CUST_DUR VARCHAR(255) COMMENT 'UPD CUS DUR',
	VEND_MFG_LIMITED VARCHAR(255) COMMENT 'VEND MFG LDTM',
	VEND_GLB_CD VARCHAR(255) COMMENT 'VENDOR GLOBAL CODE',
	VOL_UOM VARCHAR(255) COMMENT 'VOL UOM',
	LOC_KEY VARCHAR(255) COMMENT 'The location associated with the SKU. A SKU is a combnation of an Item (Product) at Location',
	BATCH_NBR VARCHAR(255) COMMENT 'The batch numbers assigned to the SKUs that are processed as part of the Calculate Master Plan process.\nE.g. Drill Chucks ( 3 point drill chucks  and self locking chucks are SKUs related to Drill chucks.) are grouped into a batch, a batch number is assigned and stored in a table(ProcessSKUS). While the Calculate Master Plan Process run, a search criteria \"Drill Chucks\" will picks all related SKUs and pack them to be part of the Calculate Master Plan process ',
	SKU_STORE_GRADE VARCHAR(255) COMMENT 'Grade assigned to the SKU based on Average Sales at Stores',
	REPL_MTHD_TYP VARCHAR(255) COMMENT 'The replenishment method dentifies if this SKU is eligible to receive allocation, replenishment or both allocation and replenishment. ',
	SKU_CREATE_DTE TIMESTAMP_NTZ(9) COMMENT 'The date on which the SKU is created i.e when this  SKU is created using NPI ',
	LAST_ON_HAND_POST_DTE TIMESTAMP_NTZ(9) COMMENT 'The last time On Hand inventory was posted for this SKU at this location',
	TRANSITION_PHASE_DUR_DY_CNT NUMBER(38,0) COMMENT 'The number of days for which a new product is in transition phase',
	STORABLE_PROD_FLAG VARCHAR(1) COMMENT 'Flag to indicate if this SKU is storable',
	ON_HAND_QTY NUMBER(28,10) COMMENT 'The on Hand quantity of this SKU in inventory at the location ',
	NET_SKU_CHG_FLAG VARCHAR(1) COMMENT 'Set by Calculate Plan to incidate that this SKU has been changed',
	SKU_REPL_PLAN VARCHAR(255) COMMENT 'Indicates how Calculate Plan, Calculate Supply Plan and Calculate Master Plan create replenishment plans for this SKU',
	SKU_PLAN_LVL VARCHAR(255) COMMENT 'Defines the level at which this SKU relates to other SKUs in the same item family',
	PROD_OUT_OF_STK_DESC VARCHAR(255) COMMENT 'Description of the status for the SKU that will be projected to be out of Stock',
	PROD_PROJECTED_OUT_OF_STK_DTE VARCHAR(255) COMMENT 'Date that the SKU is currently projected to be out of Stock',
	DISCONTINUATION_RESN VARCHAR(255) COMMENT 'Reason for Discontination',
	PROD_INIT_OUT_OF_STK_DTE VARCHAR(255) COMMENT 'Date that the SKU was initially projected to be out of Stock',
	LCL_PLNR_EMAIL VARCHAR(255) COMMENT 'Email for the Local Planner',
	MFG_CELL VARCHAR(255) COMMENT 'Manufacturing Cell',
	NOTICE_OF_DISCONTINUATION_DTE VARCHAR(255) COMMENT 'Date that the Notice of Discontinuation is communicated',
	PRIOR_PO VARCHAR(255) COMMENT 'Prior PO',
	PRODTN_RATE VARCHAR(255) COMMENT 'Production Rate',
	PROMO_PULL_DUR VARCHAR(255) COMMENT 'Indicates how far a promotion is pulled in for IO if this SKU is Opted in for IO Promotional Forecast',
	NOTICE_OF_DISCONTINUATION_FLAG VARCHAR(1) COMMENT 'Indicates if the SKU is on the Notice of Discontinuation',
	PROMO_FCST_INDCTR VARCHAR(255) COMMENT 'Indicates that this SKU allows promotional forecast in the IO Caculation',
	NO_NEW_ARRIVE_DTE TIMESTAMP_NTZ(9) COMMENT 'No New Arrive Date - Date after which planning stops',
	SUPPLY_OUT_DTE TIMESTAMP_NTZ(9) COMMENT 'Supply Out Date',
	VEND_MANAGED_INVTY_PRC VARCHAR(255) COMMENT 'Price of Vendor Managed Inventory',
	BLKD_STK NUMBER(28,10),
	KIT_INDCTR VARCHAR(255),
	REPLENINC_INDCTR VARCHAR(255),
	WGT_UOM VARCHAR(255),
	SRC_SYS_NAME VARCHAR(255) COMMENT 'Source System',
	LATEST_BEG_ON_HAND_ID VARCHAR(255) COMMENT 'Latest Beginning on Hand',
	NEW_SKU_CREATE_DTE TIMESTAMP_NTZ(9) COMMENT 'Date the SKU was created in JDA',
	DISCONTINUATION_EFF_DTE TIMESTAMP_NTZ(9) COMMENT 'Disco Effective Date',
	WKLY_INVTY_OPTIMIZATION_FLAG VARCHAR(1) DEFAULT 'U' COMMENT 'Include SKU in Weekly Inventory Optimization Batch',
	FUTR_DISCONTINUATION_FREEZE_DY VARCHAR(255) COMMENT 'Freeze days for Future Discontinuation',
	PROD_AND_LOC_ID VARCHAR(255) COMMENT ' Item and Loc Concatenation',
	SKU_SOURCING_GRP_ID VARCHAR(255) COMMENT 'Name of the sourcing view that the SKU belongs to',
	SKU_UOM_QTY NUMBER(28,10) COMMENT 'Unit of Measure applied to all quantity values associated with the SKU',
	SKU_CRNCY_UOM_QTY NUMBER(28,10) COMMENT 'Unit of Measure applied to all currency values associated with the SKU',
	SKU_OPTIMIZER_FLAG VARCHAR(1) DEFAULT 'U' COMMENT 'Indicates if the SKU will be used while running the Production and Sourcing Optimization Optimizer',
	SKU_UOM_TM_VAL VARCHAR(255) COMMENT 'Unit of measure applied to all time values associated with the SKU',
	DMD_CARRY_FORWARD_FLAG VARCHAR(1) DEFAULT 'U' COMMENT 'Indicates if the independent demand not met in one period will be carried forward to future periods',
	SFTY_STK_DMD_TYP VARCHAR(255) COMMENT 'Indicates if the Safety Stock is based on forward coverage of independent demand or sum of independent and dependent demand',
	SKU_LEADTIME_GRP_NAME VARCHAR(255) COMMENT 'Name of the lead time deliver constraint group this SKU belongs to',
	TGT_ON_HAND_CVRG_TYP VARCHAR(255) COMMENT ' Indicates if the target on hand is based on forward coverage of independent demand or sum of the independent and dependent demand',
	INFINITE_SUPPLY_SKU_FLAG VARCHAR(1) DEFAULT 'U' COMMENT 'Indicates if the SKU is an infinite supply SKU',
	SEQUENCING_INTEGRATION_ENABLE_FLAG VARCHAR(1) DEFAULT 'U' COMMENT 'Sequencing Integration Enable Switch',
	SKU_BATCH_NBR VARCHAR(255) COMMENT 'Batch numbers for the SKUs that are calculated using the Calculate Requirement Plan process',
	SKU_GRP_ID VARCHAR(255) COMMENT 'Group to which the SKU belongs',
	SKU_PUBLISH_DTE TIMESTAMP_NTZ(9) COMMENT 'Date on which the SKU target is published',
	RCRD_ENABLE_OPT VARCHAR(255) COMMENT 'Identifies the records to select for a specified instance',
	PREV_PROD_OPTIMIZATION_STORG_FLAG VARCHAR(1) DEFAULT 'U' COMMENT 'Previous Inventory Optimization Storage Switch Value',
	LOC_XYZ_CD VARCHAR(255),
	LOC_ABCXYZ_CD  VARCHAR(255),
	constraint EDW_SUPPLY_PLANNING_PRODUCT_VIEW_PK_IDX primary key (SUPPLY_PLNG_PROD_VW_KEY, SRC_SYS_KEY)
);
