version: 2

sources:
 
  - name: BLUEYONDER
    database: "{% if target.database == 'DEV_EDW' -%} DEV_RAW{% elif target.database == 'TEST_EDW' -%} TEST_RAW{% elif target.database == 'PROD_EDW' -%} PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
      {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: BOM

        identifier: VW_BOM

      - name: CAL

        identifier: VW_CAL

      - name: CALDATA

        identifier: VW_CALDATA

      - name: CUST

        identifier: VW_CUST

      - name: CUSTORDER

        identifier: VW_CUSTORDER

      - name: CURRENCYPROFILEVAL

        identifier: VW_CURRENCYPROFILEVAL

      - name: DFU

        identifier: VW_DFU

      - name: DFUEXCEPTION

        identifier: VW_DFUEXCEPTION

      - name: DFUMAP

        identifier: VW_DFUMAP

      - name: DFUTOSKU

        identifier: VW_DFUTOSKU

      - name: DFUTOSKUFCST

        identifier: VW_DFUTOSKUFCST

      - name: DFUVIEW

        identifier: VW_DFUVIEW

      - name: DMDGROUP

        identifier: VW_DMDGROUP

      - name: DMDUNIT

        identifier: VW_DMDUNIT

      - name: DYNDEPSRC

        identifier: VW_DYNDEPSRC

      - name: FCST

        identifier: VW_FCST

      - name: FCSTDRAFT

        identifier: VW_FCSTDRAFT

      - name: FCSTPERFSTATIC

        identifier: VW_FCSTPERFSTATIC

      - name: HIST

        identifier: VW_HIST

      - name: HISTFCST

        identifier: VW_HISTFCST

      - name: INTERR_HIST

        identifier: VW_INTERR_HIST

      - name: ITEM

        identifier: VW_ITEM

      - name: LOC

        identifier: VW_LOC

      - name: MODEL

        identifier: VW_MODEL

      - name: NETWORK

        identifier: VW_NETWORK

      - name: PLANORDER

        identifier: VW_PLANORDER

      - name: PRICEPROFILEVAL

        identifier: VW_PRICEPROFILEVAL

      - name: PRODUCTIONMETHOD

        identifier: VW_PRODUCTIONMETHOD

      - name: PRODUCTIONSTEP

        identifier: VW_PRODUCTIONSTEP

      - name: RECSHIP

        identifier: VW_RECSHIP

      - name: RES

        identifier: VW_RES

      - name: RESEXCEPTION

        identifier: VW_RESEXCEPTION

      - name: RESLOADDETAIL

        identifier: VW_RESLOADDETAIL

      - name: RESPROJSTATIC

        identifier: VW_RESPROJSTATIC

      - name: SKU

        identifier: VW_SKU

      - name: SKUDISPLAY

        identifier: VW_SKUDISPLAY

      - name: SKUDEMANDPARAM

        identifier: VW_SKUDEMANDPARAM

      - name: SKUDEPLOYMENTPARAM

        identifier: VW_SKUDEPLOYMENTPARAM

      - name: SKUEXCEPTION

        identifier: VW_SKUEXCEPTION

      - name: SKUEXTERNALFCST

        identifier: VW_SKUEXTERNALFCST

      - name: SKUPLANNINGPARAM

        identifier: VW_SKUPLANNINGPARAM

      - name: SKUPROJSTATIC

        identifier: VW_SKUPROJSTATIC

      - name: SKUSAFETYSTOCKPARAM

        identifier: VW_SKUSAFETYSTOCKPARAM

      - name: SOURCING

        identifier: VW_SOURCING

      - name: TARGET

        identifier: VW_TARGET

      - name: TARGETDFUMAP

        identifier: VW_TARGETDFUMAP

      - name: VEHICLELOAD

        identifier: VW_VEHICLELOAD

      - name: VEHICLELOADLINE

        identifier: VW_VEHICLELOADLINE

      - name: PLANARRIV

        identifier: VW_PLANARRIV


        