select 
UPPER(concat(coalesce(MAST.STLNR,''),'~',coalesce(MAST.STLAL,''),'~',coalesce(STKO.STLTY,''),'~',coalesce(STKO.STKOZ,''))) AS PROD_BOM_PRNT_KEY,
'SAPSHP' AS  {{var('column_srcsyskey')}},
MD5(UPPER(concat(coalesce(MAST.STLNR,''),'~',coalesce(MAST.STLAL,''),'~',coalesce(STKO.STLTY,''),'~',coalesce(STKO.STKOZ,'')))) AS  {{var('column_rechashkey')}},
{{var('default_n')}} as {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS  {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS  {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_UPD_DTE')}},
MAST.LOADDTS AS  {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS  {{var('column_verexpirydt')}},
{{var('default_y')}} as {{var('column_currrecflag')}},
{{var('default_n')}} as {{var('column_orprecflag')}},
MAST.LOADDTS AS  {{var('column_z3loddtm')}},
case when length(trim(STKO.STLTY)) <1 then {{var('default_mapkey')}} when STKO.STLTY IS NULL then {{var('default_mapkey')}} else UPPER(STKO.STLTY) end as BOM_CTGY_LKEY,
STKO.STKTX AS ALT_BOM_TEXT,
case when length(trim(MAST.STLAL)) <1 then {{var('default_mapkey')}} when MAST.STLAL IS NULL then {{var('default_mapkey')}} else UPPER(MAST.STLAL) end as ALT_BOM_KEY,
case when length(trim(MAST.STLNR)) <1 then {{var('default_mapkey')}} when MAST.STLNR IS NULL then {{var('default_mapkey')}} else UPPER(MAST.STLNR) end as BOM_KEY,
MAST.LOSVN AS MIN_LOT_RANGE_NBR,
MAST.LOSBS AS MAX_LOT_RANGE_NBR,
case when length(trim(MAST.MATNR)) <1 then {{var('default_mapkey')}} when MAST.MATNR IS NULL then {{var('default_mapkey')}} else UPPER(MAST.MATNR) end as PROD_KEY,
case when length(trim(MAST.WERKS)) <1 then {{var('default_mapkey')}} when MAST.WERKS IS NULL then {{var('default_mapkey')}} else UPPER(MAST.WERKS) end as LOC_KEY,
case when length(trim(MAST.STLAN)) <1 then {{var('default_mapkey')}} when MAST.STLAN IS NULL then {{var('default_mapkey')}} else UPPER(MAST.STLAN) end as BOM_USAGE_KEY,
case  when UPPER(STKO.ALEKZ) ='X'  then 'Y' else 'N'  end ALE_DATA_DIST_FLAG,
--case  when UPPER(STKO.GUIDX) ='X'  then 'Y' else 'N'  end GLB_ID_FOR_BOM_HDR_CHG_FLAG,
case  when UPPER(STKO.LKENZ) ='X'  then 'Y' else 'N'  end BOM_DEL_FLAG,
case  when UPPER(STKO.LOEKZ) ='X'  then 'Y' else 'N'  end ARCHIVING_SPECIFIC_BOM_DEL_FLAG,
case  when UPPER(STKO.VERSNLASTIND) ='X'  then 'Y' else 'N'  end LATEST_BOM_VER_FLAG,
case  when UPPER(STKO.CADKZ) ='X'  then 'Y' else 'N'  end CAD_FLAG,
case  when UPPER(MAST.CSLTY) ='X'  then 'Y' else 'N'  end IS_PROD_CONFIGURABLE_FLAG,
TRY_TO_DATE(STKO.DATUV,'YYYY.MM.DD') AS PROD_BOM_EFF_DTE,
TRY_TO_DATE(STKO.VALID_TO,'YYYY.MM.DD') AS VALID_END_DTE,
TRY_TO_DATE(STKO.DUMMY_STKO_INCL_EEW_PS,'YYYY.MM.DD') AS EXTENSIBILITY_ELMNT_DTE,
TRY_TO_DATE(STKO.DVDAT,'YYYY.MM.DD') AS LAST_SHFT_DTE,
STKO.DVNAM AS LAST_SHFT_USER_NAME,
STKO.LABOR AS LABORATORY_OFFICE_NAME,
STKO.TECHV AS PRODTN_STAT,
STKO.ECN_TO AS CHG_NBR,
STKO.BOM_VERSN AS BOM_VER_NBR,
STKO.VERSNST AS BOM_VER_STAT,
STKO.LASTCHANGEDATETIME AS UTC_TM_STAMP,
STKO.BOM_AIN_IND AS BOM_TO_AIN_HNDVR,
STKO.BOM_PREV_VERSN AS BOM_PRED_VER_NBR,
case when length(trim(STKO.BMEIN)) <1 then {{var('default_mapkey')}} when STKO.BMEIN IS NULL then {{var('default_mapkey')}} else UPPER(STKO.BMEIN) end as BASE_UOM_KEY,
case when length(trim(STKO.WRKAN)) <1 then {{var('default_mapkey')}} when STKO.WRKAN IS NULL then {{var('default_mapkey')}} else UPPER(STKO.WRKAN) end as ALT_BOM_PLANT_LOC_KEY,
STKO.AEHLP AS DTE_SHFT_HIER_INDCTR,
STKO.BMENG AS BASE_QTY,
STKO.STKOZ AS BOM_ITRL_CNTR_NBR,
case when length(trim(STKO.STLST)) <1 then {{var('default_mapkey')}} when STKO.STLST IS NULL then {{var('default_mapkey')}} else UPPER(STKO.STLST) end as BOM_STAT_LKEY,
STKO.VGKZL AS PREV_BOM_HDR_CNTR,
case when length(trim(STKO.LTXSP)) <1 then {{var('default_mapkey')}} when STKO.LTXSP IS NULL then {{var('default_mapkey')}} else UPPER(STKO.LTXSP) end as LANG_LKEY
from {{source('SAPSHP','MAST')}} MAST 
left join  {{source('SAPSHP','STKO')}} STKO on 
MAST.STLNR = STKO.STLNR AND MAST.STLAL = STKO.STLAL AND STKO.STLTY = 'M'