SELECT
UPPER(CONCAT(COALESCE(BDPSMSTR.BDPS_PAR::VARCHAR,''),'~',COALESCE(BDPSMSTR.BDPS_COMP::VARCHAR,''),'~',Coalesce(BDPSMSTR.BDPS_START::varchar,''),'~',COALESCE(BDPSMSTR.BDPS_REF::VARCHAR,''),'~',COALESCE(BDPSMSTR.BDPS_SITE::VARCHAR,''))) AS PROD_BOM_CMPNT_KEY,
'QADAR' AS {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(COALESCE(BDPSMSTR.BDPS_PAR::VARCHAR,''),'~',COALESCE(BDPSMSTR.BDPS_COMP::VARCHAR,''),'~',Coalesce(BDPSMSTR.BDPS_START::varchar,''),'~',COALESCE(BDPSMSTR.BDPS_REF::VARCHAR,''),'~',COALESCE(BDPSMSTR.BDPS_SITE::VARCHAR,'')))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
BDPSMSTR.LOADDTS AS {{var('column_z3loddtm')}},
BDPSMSTR.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},
case when length(trim(BDPSMSTR.BDPS_PAR))<1 then {{var('default_mapkey')}} when BDPSMSTR.BDPS_PAR IS NULL then  {{var('default_mapkey')}} else (BDPSMSTR.BDPS_PAR) end AS PROD_KEY,
case when length(trim(BDPSMSTR.BDPS_COMP))<1 then {{var('default_mapkey')}} when BDPSMSTR.BDPS_COMP IS NULL then  {{var('default_mapkey')}} else (BDPSMSTR.BDPS_COMP) end AS CMPNT_PROD_KEY,
BDPSMSTR.BDPS_QTY_PER AS PROD_QTY,
BDPSMSTR.BDPS_SCRP_PCT AS PROD_SCRAP_PCT,
TRY_TO_DATE(BDPSMSTR.BDPS_START,'MM/DD/YY') AS BOM_RELATION_START_DTE,
TRY_TO_DATE(BDPSMSTR.BDPS_END,'MM/DD/YY') AS BOM_RELATION_END_DTE,
BDPSMSTR.BDPS_OP AS OPER_STEP_NBR,
BDPSMSTR.BDPS_ITEM_NO AS PROD_STRC_RPT_NBR,
CASE WHEN UPPER(BDPSMSTR.BDPS_MANDATORY) = 'YES' THEN 'Y' ELSE 'N' END AS IS_CMPNT_ITEM_REQ_FLAG,
case when length(trim(BDPSMSTR.BDPS_QTY_TYPE))<1 then {{var('default_mapkey')}} when BDPSMSTR.BDPS_QTY_TYPE IS NULL then  {{var('default_mapkey')}} else (BDPSMSTR.BDPS_QTY_TYPE) end AS QTY_PER_TYP_LKEY,
case when length(trim(BDPSMSTR.BDPS_GROUP))<1 then {{var('default_mapkey')}} when BDPSMSTR.BDPS_GROUP IS NULL then  {{var('default_mapkey')}} else (BDPSMSTR.BDPS_GROUP) end AS PROD_GRP_TYP_LKEY,
CASE WHEN UPPER(BDPSMSTR.BDPS_CRITICAL) = 'YES' THEN 'Y' ELSE 'N' END AS CRTCL_CMPNT_ASSEMBLY_STAT_FLAG,
BDPSMSTR.BDPS_COMP_UM AS PROD_CMPNT_UNIT_VAL,
BDPSMSTR.BDPS_UM_CONV AS PROD_UM_CONV_FACTOR,
case when length(trim(BDPSMSTR.BDPS_COMM_CODE))<1 then {{var('default_mapkey')}} when BDPSMSTR.BDPS_COMM_CODE IS NULL then  {{var('default_mapkey')}} else (BDPSMSTR.BDPS_COMM_CODE) end AS CMDTY_CD_LKEY,
BDPSMSTR.BDPS_START_ECN AS PROD_BEG_ECN_NBR,
BDPSMSTR.BDPS_END_ECN AS PROD_END_ECN_NBR,
case when length(trim(BDPSMSTR.BDPS_JOINT_TYPE))<1 then {{var('default_mapkey')}} when BDPSMSTR.BDPS_JOINT_TYPE IS NULL then  {{var('default_mapkey')}} else (BDPSMSTR.BDPS_JOINT_TYPE) end AS JOINT_PROD_TYP_LKEY,
BDPSMSTR.BDPS_RMKS AS USER_RMRK_TEXT,
BDPSMSTR.BDPS_QTY_PER_B AS BATCH_SZ_QTY,
{{var('default_key')}} AS BOM_CTGY_LKEY,
{{var('default_key')}} AS RESIDING_LOC_KEY,
{{var('default_key')}} AS ISS_PLANT_LOC_KEY,
{{var('default_key')}} AS CMPNT_UOM_KEY,
{{var('default_key')}} AS BOM_CMPNT_ITEM_CTGY_LKEY,
{{var('default_key')}} AS CLS_TYP_LKEY,
{{var('default_key')}} AS DOC_TYP_LKEY,
{{var('default_key')}} AS PROD_GRP_LKEY,
{{var('default_key')}} AS PROD_BOM_PRNT_KEY,
--{{var('default_key')}} AS OPTIONAL_PROD_BOM_CMPNT_KEY,
-- {{var('default_key')}} AS AUXILIARY_UOM_KEY,
-- {{var('default_key')}} AS PRNT_PROD_KEY,
{{var('default_key')}} AS PROD_EXPLD_TYP_LKEY,
--{{var('default_key')}} AS PUR_ORG_KEY,
{{var('default_key')}} AS BOM_PROCUR_TYP_LKEY,
{{var('default_key')}} AS LANG_FMT_TYP_LKEY,
--{{var('default_key')}} AS LEADTIME_OFFSET_UOM_KEY,
{{var('default_key')}} AS PROD_OBJ_CTGY_LKEY,
{{var('default_key')}} AS PRODTN_SUPPLY_AREA_LKEY,
{{var('default_key')}} AS PROD_COST_RELVNT_LKEY,
{{var('default_key')}} AS CRNCY_KEY,
{{var('default_key')}} AS ALT_PROD_STRAT_LKEY,
--{{var('default_key')}} AS ALT_DISPLAY_FMT_KEY,
{{var('default_key')}} AS PROD_BOM_CTGY_LKEY,
--{{var('default_key')}} AS FORMULA_KEY,
{{var('default_key')}} AS PROD_BOM_REF_POINT_LKEY,
{{var('default_key')}} AS CMPNT_CNSMPTN_DIST_LKEY,
{{var('default_key')}} AS PRODTN_BOM_LKEY,
{{var('default_key')}} AS PROD_CMPNT_TYP_LKEY,
{{var('default_key')}} AS BUS_UNIT_KEY,
{{var('default_key')}} AS PROD_LN_TYP_LKEY,
{{var('default_key')}} AS BASE_UOM_KEY,
{{var('default_key')}} AS BOM_KEY,
{{var('default_key')}} AS LAST_MTNC_USER_KEY,
{{var('default_key')}} AS PROD_CLS_LKEY,
BDPSMSTR.BDPS_REF AS BOM_TEXT_REF,
BDPSMSTR.BDPS_SITE AS BOM_SITE
FROM {{source('QADAR','BDPSMSTR')}} BDPSMSTR
