Select
CONCAT(coalesce(FCSTDRAFT.DMDUNIT::varchar,''),'~',coalesce(FCSTDRAFT.DMDGROUP::varchar,''),'~' ,coalesce(FCSTDRAFT.LOC::varchar,''),'~' ,coalesce(FCSTDRAFT.STARTDATE::varchar,''),'~' ,coalesce(FCSTDRAFT.TYPE::varchar,''),'~' ,coalesce(FCSTDRAFT.FCSTID::varchar,''),'~' ,coalesce(FCSTDRAFT.MODEL::varchar,''),'~','DRAFT') AS DMD_FCST_KEY,
'JDAEDW' AS {{var('column_srcsyskey')}},
MD5(CONCAT(coalesce(FCSTDRAFT.DMDUNIT::varchar,''),'~',coalesce(FCSTDRAFT.DMDGROUP::varchar,''),'~' ,coalesce(FCSTDRAFT.LOC::varchar,''),'~' ,coalesce(FCSTDRAFT.STARTDATE::varchar,''),'~' ,coalesce(FCSTDRAFT.TYPE::varchar,''),'~' ,coalesce(FCSTDRAFT.FCSTID::varchar,''),'~' ,coalesce(FCSTDRAFT.MODEL::varchar,''),'~','DRAFT')) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
FCSTDRAFT.LOADDTS AS {{var('column_z3loddtm')}},
FCSTDRAFT.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},
'CURRENT'	as	DMD_FCST_CTGY,
'EA' as UOM_KEY,
case when length(trim(UPPER((FCSTDRAFT.DMDGROUP)))) <1 then {{var('default_mapkey')}} when UPPER(FCSTDRAFT.DMDGROUP) IS NULL then {{var('default_mapkey')}} else UPPER(FCSTDRAFT.DMDGROUP) end AS DMD_GRP_KEY,
case when length(trim(UPPER((FCSTDRAFT.DMDUNIT)))) <1 then {{var('default_mapkey')}} when UPPER(FCSTDRAFT.DMDUNIT) IS NULL then {{var('default_mapkey')}} else UPPER(FCSTDRAFT.DMDUNIT) end AS DMD_UNIT_KEY,
case when length(trim(UPPER((FCSTDRAFT.FCSTID)))) <1 then {{var('default_mapkey')}} when UPPER(FCSTDRAFT.FCSTID) IS NULL then {{var('default_mapkey')}} else UPPER(FCSTDRAFT.FCSTID) end AS FCST_ID_TYP,
case when length(trim(UPPER((FCSTDRAFT.LOC)))) <1 then {{var('default_mapkey')}} when UPPER(FCSTDRAFT.LOC) IS NULL then {{var('default_mapkey')}} else UPPER(FCSTDRAFT.LOC) end AS LOC_KEY,
case when length(trim(UPPER((FCSTDRAFT.TYPE)))) <1 then {{var('default_mapkey')}} when UPPER(FCSTDRAFT.TYPE) IS NULL then {{var('default_mapkey')}} else UPPER(FCSTDRAFT.TYPE) end AS FCST_TYP,
FCSTDRAFT.DUR/1440	as	FCST_DUR,
FCSTDRAFT.LEWMEANQTY	as	MEAN_FCST_QTY,
FCSTDRAFT.MARKETMGRVERSIONID	as	MKT_MGR_VER_NBR,
FCSTDRAFT.QTY	as	FCST_QTY,
FCSTDRAFT.MODEL	as	PLNG_MODEL_NAME,
to_date(FCSTDRAFT.STARTDATE)	as	FCST_START_DTE,
{{var('default_key')}} AS PROD_KEY,
{{var('default_key')}} AS FCST_STREAM_KEY
FROM {{source('JDAEDW','FCSTDRAFT')}} FCSTDRAFT