Select
concat(coalesce(cast(BDPSMSTR.bdps_par as string),''),'~',coalesce(cast(BDPSMSTR.bdps_comp as string),''),'~',coalesce(cast(BDPSMSTR.bdps_start as string),''),'~',coalesce(cast(BDPSMSTR.bdps_ref as string),''),'~',coalesce(cast(BDPSMSTR.bdps_site as string),'')) AS PROD_BOM_CMPNT_KEY,
'QADPE' AS {{var('column_srcsyskey')}},
MD5(concat(coalesce(cast(BDPSMSTR.bdps_par as string),''),'~',coalesce(cast(BDPSMSTR.bdps_comp as string),''),'~',coalesce(cast(BDPSMSTR.bdps_start as string),''),'~',coalesce(cast(BDPSMSTR.bdps_ref as string),''),'~',coalesce(cast(BDPSMSTR.bdps_site as string),''))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
BDPSMSTR.LOADDTS AS {{var('column_z3loddtm')}},
BDPSMSTR.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},
case when length(trim(BDPSMSTR.bdps_par))<1 then {{var('default_mapkey')}} when BDPSMSTR.bdps_par IS NULL then {{var('default_mapkey')}} else (BDPSMSTR.bdps_par) end AS PROD_KEY,
case when length(trim(BDPSMSTR.bdps_comp))<1 then {{var('default_mapkey')}} when BDPSMSTR.bdps_comp IS NULL then {{var('default_mapkey')}} else (BDPSMSTR.bdps_comp) end AS CMPNT_PROD_KEY,
BDPSMSTR.bdps_qty_per AS PROD_QTY,
BDPSMSTR.bdps_scrp_pct AS PROD_SCRAP_PCT,
TRY_TO_DATE(BDPSMSTR.bdps_start,'MM/DD/YY') AS BOM_RELATION_START_DTE,
TRY_TO_DATE(BDPSMSTR.bdps_end,'MM/DD/YY') AS BOM_RELATION_END_DTE,
BDPSMSTR.bdps_op AS OPER_STEP_NBR,
BDPSMSTR.bdps_item_no AS PROD_STRC_RPT_NBR,
CASE WHEN BDPSMSTR.bdps_mandatory = 'yes' or 'YES' THEN 'Y' else 'N' end AS IS_CMPNT_ITEM_REQ_FLAG,
case when length(trim(BDPSMSTR.bdps_qty_type))<1 then {{var('default_mapkey')}} when BDPSMSTR.bdps_qty_type IS NULL then {{var('default_mapkey')}} else (BDPSMSTR.bdps_qty_type) end AS QTY_PER_TYP_LKEY,
case when length(trim(BDPSMSTR.bdps_group))<1 then {{var('default_mapkey')}} when BDPSMSTR.bdps_group IS NULL then {{var('default_mapkey')}} else (BDPSMSTR.bdps_group) end AS PROD_GRP_TYP_LKEY,
CASE WHEN BDPSMSTR.bdps_critical ='no' or 'NO' THEN 'N' else 'Y' end AS CRTCL_CMPNT_ASSEMBLY_STAT_FLAG,
BDPSMSTR.bdps_comp_um AS PROD_CMPNT_UNIT_VAL,
BDPSMSTR.bdps_um_conv AS PROD_UM_CONV_FACTOR,
case when length(trim(BDPSMSTR.bdps_comm_code))<1 then {{var('default_mapkey')}} when BDPSMSTR.bdps_comm_code IS NULL then {{var('default_mapkey')}} else (BDPSMSTR.bdps_comm_code) end AS CMDTY_CD_LKEY,
BDPSMSTR.bdps_start_ecn AS PROD_BEG_ECN_NBR,
BDPSMSTR.bdps_end_ecn AS PROD_END_ECN_NBR,
case when length(trim(BDPSMSTR.bdps_joint_type))<1 then {{var('default_mapkey')}} when BDPSMSTR.bdps_joint_type IS NULL then {{var('default_mapkey')}} else (BDPSMSTR.bdps_joint_type) end AS JOINT_PROD_TYP_LKEY,
BDPSMSTR.bdps_rmks AS USER_RMRK_TEXT,
BDPSMSTR.bdps_qty_per_b AS BATCH_SZ_QTY,
BDPSMSTR.bdps_ref AS BOM_TEXT_REF,
BDPSMSTR.bdps_site AS BOM_SITE
FROM {{source('QADPE','BDPSMSTR')}} BDPSMSTR 
