select
UPPER(CONCAT(coalesce(SKUSAFETYSTOCKPARAM.ITEM ::VARCHAR,''),'~',coalesce(SKUSAFETYSTOCKPARAM.LOC ::VARCHAR,''))) AS SUPPLY_PLNG_SFTY_STK_PARM_KEY,
'JDA' AS {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(coalesce(SKUSAFETYSTOCKPARAM.ITEM::VARCHAR,''),'~',coalesce(SKUSAFETYSTOCKPARAM.LOC::VARCHAR,'')))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
SKUSAFETYSTOCKPARAM.LOADDTS AS {{var('column_z3loddtm')}},
SKUSAFETYSTOCKPARAM.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},


SKUSAFETYSTOCKPARAM.AVGDMDCAL AS AVG_DMD_CLNDR_TYP,
SKUSAFETYSTOCKPARAM.DMDALLOCCAL AS DMD_ALLOC_CLNDR_TYP,
SKUSAFETYSTOCKPARAM.DMDCAL AS DMD_CLNDR_TYP,
SKUSAFETYSTOCKPARAM.HIGHERBUCKETDMDCAL AS HIGHER_BUCKET_DMD_CLNDR_TYP,

case when length(trim(UPPER((SKUSAFETYSTOCKPARAM.ITEM)))) <1 then {{var('default_mapkey')}} when UPPER(SKUSAFETYSTOCKPARAM.ITEM)
IS NULL then {{var('default_mapkey')}} else UPPER(SKUSAFETYSTOCKPARAM.ITEM) end AS PROD_KEY,

case when length(trim(UPPER((SKUSAFETYSTOCKPARAM.LOC)))) <1 then {{var('default_mapkey')}} when UPPER(SKUSAFETYSTOCKPARAM.LOC)
IS NULL then {{var('default_mapkey')}} else UPPER(SKUSAFETYSTOCKPARAM.LOC) end AS LOC_KEY,

SKUSAFETYSTOCKPARAM.CALCMSERULE AS MEAN_SQUARED_ERR_RULE,
SKUSAFETYSTOCKPARAM.CALCSTATSSRULE  AS STATS_SFTY_STK_RULE,
SKUSAFETYSTOCKPARAM.CSLMETRIC  AS CUST_SVC_LVL_METRIC,
SKUSAFETYSTOCKPARAM.DMDDISTTYPE  AS DMD_DIST_TYP,
SKUSAFETYSTOCKPARAM.MSEMASKOPT  AS MSE_MASKING_OPT,
SKUSAFETYSTOCKPARAM.MSEMODELOPT  AS MSE_MODEL_OPT,
SKUSAFETYSTOCKPARAM.SSPRESENTATIONOPT  AS MIN_PRESENTATION_QTY_OPT,
SKUSAFETYSTOCKPARAM.SSRULE AS SFTY_STK_RULE,
SKUSAFETYSTOCKPARAM.STATSSADJOPT AS SFTY_STK_ADJ_OPT,
SKUSAFETYSTOCKPARAM.MSEMASKMAXVAL AS MASKING_MAX_OPT,
SKUSAFETYSTOCKPARAM.MSEMASKMINVAL AS MASKING_MIN_OPT,

case when UPPER(SKUSAFETYSTOCKPARAM.SSCOVUSEBASEONLYSW) in ('NO','FALSE','0') or UPPER(SKUSAFETYSTOCKPARAM.SSCOVUSEBASEONLYSW) is null
or length(TRIM(SKUSAFETYSTOCKPARAM.SSCOVUSEBASEONLYSW))<1 then 'N' when UPPER(SKUSAFETYSTOCKPARAM.SSCOVUSEBASEONLYSW) in ('YES','TRUE','1')
then 'Y' else 'U' end as USE_BASE_ONLY_FLAG,

case when UPPER(SKUSAFETYSTOCKPARAM.SUPERSEDESSSW) in ('NO','FALSE','0') or UPPER(SKUSAFETYSTOCKPARAM.SUPERSEDESSSW) is null
or length(TRIM(SKUSAFETYSTOCKPARAM.SUPERSEDESSSW))<1 then 'N' when UPPER(SKUSAFETYSTOCKPARAM.SUPERSEDESSSW) in ('YES','TRUE','1')
then 'Y' else 'U' end as SFTY_STK_SUPERSEDE_FLAG,

case when UPPER(SKUSAFETYSTOCKPARAM.ALLOWEARLYARRIVSW) in ('NO','FALSE','0') or UPPER(SKUSAFETYSTOCKPARAM.ALLOWEARLYARRIVSW) is null
or length(TRIM(SKUSAFETYSTOCKPARAM.ALLOWEARLYARRIVSW))<1 then 'N' when UPPER(SKUSAFETYSTOCKPARAM.ALLOWEARLYARRIVSW) in ('YES','TRUE','1')
then 'Y' else 'U' end as ALLOW_EARLY_ARRVL_FLAG,

case when UPPER(SKUSAFETYSTOCKPARAM.ALLOWEARLYORDERSW) in ('NO','FALSE','0') or UPPER(SKUSAFETYSTOCKPARAM.ALLOWEARLYORDERSW) is null
or length(TRIM(SKUSAFETYSTOCKPARAM.ALLOWEARLYORDERSW))<1 then 'N' when UPPER(SKUSAFETYSTOCKPARAM.ALLOWEARLYORDERSW) in ('YES','TRUE','1')
then 'Y' else 'U' end as ALLOW_EARLY_ORD_FLAG,


SKUSAFETYSTOCKPARAM.ACCUMDUR AS PLAN_FRZ_DUR_MNS_CNT,
SKUSAFETYSTOCKPARAM.AVGDMDLOOKBWDDUR AS AVG_DMD_LOOK_BACKWARD_DUR,
SKUSAFETYSTOCKPARAM.AVGDMDLOOKFWDDUR AS AVG_DMD_LOOK_FORWARD_DUR,
SKUSAFETYSTOCKPARAM.FCSTDUR AS FCST_DUR,
SKUSAFETYSTOCKPARAM.LEADTIMESD AS STD_DEVN_LEADTIME_DUR,
SKUSAFETYSTOCKPARAM.MAXSSCOVSKIPDUR AS MAX_CVRG_SKIP_DUR,
SKUSAFETYSTOCKPARAM.ORDERDATADUR AS ORD_DATA_DUR,
SKUSAFETYSTOCKPARAM.SHIPDATADUR AS SHIP_DATA_DUR,
SKUSAFETYSTOCKPARAM.MSEPER AS DMD_PERD_CNT,
SKUSAFETYSTOCKPARAM.SSCOV AS SFTY_STK_CVRG_DUR,
SKUSAFETYSTOCKPARAM.SSMEETEARLYDUR AS MEET_EARLY_DUR,
SKUSAFETYSTOCKPARAM.STATSSCOVLIMITDUR AS STATS_CVRG_LIMIT_DUR,
SKUSAFETYSTOCKPARAM.MAXSS AS MAX_SFTY_STK_QTY,
SKUSAFETYSTOCKPARAM.MINSS AS MIN_SFTY_STK_QTY,
SKUSAFETYSTOCKPARAM.MSEABSTOLERANCELIMIT AS ABSOLUTE_TLRNCE_LIMIT_QTY,
SKUSAFETYSTOCKPARAM.MSELAG AS LAG_PERD_CNT,
SKUSAFETYSTOCKPARAM.NUMREPLENYR AS PER_YR_REPL_CNT,
SKUSAFETYSTOCKPARAM.ORDERLAG AS ORD_LAG_PERD_CNT,
SKUSAFETYSTOCKPARAM.SHIPLAG AS SHIP_LAG_PERD_CNT,
SKUSAFETYSTOCKPARAM.SSPRIORITY AS PRYRT_NBR,
SKUSAFETYSTOCKPARAM.DMDCORRELATIONFACTOR AS DMD_CORRELATION_FACTOR,
SKUSAFETYSTOCKPARAM.MAXSSFACTOR AS MAX_SFTY_STK_FACTOR,
SKUSAFETYSTOCKPARAM.NETFCSTMSESMCONST AS ERR_SMOOTHING_CONSTANT_VAL,
SKUSAFETYSTOCKPARAM.STATSSCSL AS SFTY_STK_CUST_SVC_LVL_VAL,
SKUSAFETYSTOCKPARAM.SSTEMPLATE AS SFTY_STK_TEMP_NAME,
SKUSAFETYSTOCKPARAM.AVGLEADTIME AS AVG_LEADTIME_DY_CNT,
SKUSAFETYSTOCKPARAM.AVGNUMLINES AS AVG_NBR_LN_CNT,

SKUSAFETYSTOCKPARAM.ARRIVALPOSTDATE AS ARRVL_DATA_POST_DTE,
SKUSAFETYSTOCKPARAM.DMDPOSTDATE AS DMD_POST_DTE,
SKUSAFETYSTOCKPARAM.ORDERPOSTDATE AS ORD_POST_DTE,
SKUSAFETYSTOCKPARAM.U_PRE_DMDPOSTDATE AS PRE_DMD_POST_DTE

FROM {{source('JDA','SKUSAFETYSTOCKPARAM')}} SKUSAFETYSTOCKPARAM
