Select
UPPER(CONCAT(coalesce(PRODUCTIONSTEP.PRODUCTIONMETHOD,''),'~',coalesce(PRODUCTIONSTEP.STEPNUM::VARCHAR,''),'~' ,coalesce(PRODUCTIONSTEP.ITEM,''),'~' ,
coalesce(PRODUCTIONSTEP.LOC,''),'~' ,coalesce(PRODUCTIONSTEP.EFF,''))) AS PRODTN_MTHD_STEP_KEY,
'JDA' AS {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(coalesce(PRODUCTIONSTEP.PRODUCTIONMETHOD,''),'~',coalesce(PRODUCTIONSTEP.STEPNUM::VARCHAR,''),'~' ,coalesce(PRODUCTIONSTEP.ITEM,''),'~' ,
coalesce(PRODUCTIONSTEP.LOC,''),'~' ,coalesce(PRODUCTIONSTEP.EFF,'')))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
PRODUCTIONSTEP.LOADDTS AS {{var('column_z3loddtm')}},
PRODUCTIONSTEP.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},
--case when length(trim(UPPER((PRODUCTIONSTEP.PRODUCTIONMETHOD)))) <1 then {{var('default_mapkey')}} when UPPER(PRODUCTIONSTEP.PRODUCTIONMETHOD)
--IS NULL then {{var('default_mapkey')}} else UPPER(PRODUCTIONSTEP.PRODUCTIONMETHOD) end AS PRODTN_MTHD_KEY,
UPPER(CONCAT(coalesce(PRODUCTIONSTEP.PRODUCTIONMETHOD::VARCHAR,''),'~',coalesce(PRODUCTIONSTEP.ITEM::VARCHAR,''),'~' ,coalesce(PRODUCTIONSTEP.LOC::VARCHAR,''))) AS PRODTN_MTHD_KEY,
case when length(trim(UPPER((PRODUCTIONSTEP.ITEM)))) <1 then {{var('default_mapkey')}} when UPPER(PRODUCTIONSTEP.ITEM)
IS NULL then {{var('default_mapkey')}} else UPPER(PRODUCTIONSTEP.ITEM) end AS PROD_KEY,

case when length(trim(UPPER((PRODUCTIONSTEP.LOC)))) <1 then {{var('default_mapkey')}} when UPPER(PRODUCTIONSTEP.LOC)
IS NULL then {{var('default_mapkey')}} else UPPER(PRODUCTIONSTEP.LOC) end AS LOC_KEY,

PRODUCTIONSTEP.PRODRATECAL AS PRODTN_RATE_CLNDR_ID,

PRODUCTIONSTEP.QTYUOM AS UOM_ID,

case when length(trim(UPPER((PRODUCTIONSTEP.RES)))) <1 then {{var('default_mapkey')}} when UPPER(PRODUCTIONSTEP.RES)
IS NULL then {{var('default_mapkey')}} else UPPER(PRODUCTIONSTEP.RES) end AS ASSCTD_RESOURCE_KEY,

PRODUCTIONSTEP.NEXTSTEPTIMING AS NEXT_STEP_TIMING_MTHD,
PRODUCTIONSTEP.PRODFAMILY AS PRODTN_FAMILY,
PRODUCTIONSTEP.EFF AS PRODTN_STEP_START_DTE,
PRODUCTIONSTEP.PRODCOST AS PRODTN_UNIT_COST,
PRODUCTIONSTEP.STEPNUM AS PRODTN_MTHD_STEP_NBR,
PRODUCTIONSTEP.FIXEDRESREQ AS FIXED_RESOURCE_CAPACITY_CNT,
PRODUCTIONSTEP.LOADOFFSETDUR AS LOD_OFFSET_DUR,
PRODUCTIONSTEP.MAXSTARTDUR AS MAX_DUR,
PRODUCTIONSTEP.PRODDUR AS PRODTN_DUR,
PRODUCTIONSTEP.PRODOFFSET AS PRODTN_OFFSET_DUR,
PRODUCTIONSTEP.BASEYIELD AS BASE_YIELD_FACTOR,
PRODUCTIONSTEP.PRODRATE AS PRODTN_RATE,
PRODUCTIONSTEP.DESCR AS PRODTN_STEP_DESC,
case when PRODUCTIONSTEP.ENABLESW= '1' THEN 'Y' ELSE 'N' END AS PRODTN_MTHD_OPTIMIZER_FLAG,
case when PRODUCTIONSTEP.INUSEBEFORESW = '1' THEN 'Y' ELSE 'N' END AS PRODTN_STEP_ACTV_FLAG,
PRODUCTIONSTEP.SETUP AS PRODTN_STEP_SETUP_ID,
PRODUCTIONSTEP.SPREAD AS COMPUTED_LOD_DUR
FROM {{source('JDA','PRODUCTIONSTEP')}} PRODUCTIONSTEP

