select
UPPER(CONCAT(coalesce(PLANORDER.ITEM::VARCHAR,''),'~',coalesce(PLANORDER.LOC::VARCHAR,''),'~' ,coalesce(PLANORDER.SEQNUM::VARCHAR,''))) AS SUPPLY_PLND_ORD_KEY,
'JDA' AS {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(coalesce(PLANORDER.ITEM::VARCHAR,''),'~',coalesce(PLANORDER.LOC::VARCHAR,''),'~' ,coalesce(PLANORDER.SEQNUM::VARCHAR,'')))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
PLANORDER.LOADDTS AS {{var('column_z3loddtm')}},
PLANORDER.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},
trim(PLANORDER.ACTION) AS ACTN_TYP,
case when UPPER(PLANORDER.ACTIONALLOWEDSW) in ('NO','FALSE','0') or UPPER(PLANORDER.ACTIONALLOWEDSW) is null
or length(TRIM(PLANORDER.ACTIONALLOWEDSW))<1 then 'N' when UPPER(PLANORDER.ACTIONALLOWEDSW) in ('YES','TRUE','1')
then 'Y' else 'U' end as ACTN_ALLOW_FLAG,
PLANORDER.ACTIONDATE AS RECOMMENDED_ACTN_DTE,
PLANORDER.ACTIONQTY AS ACTN_QTY,
trim(PLANORDER.COPRODORDERTYPE) AS CO_PROD_ORD_TYP,
trim(PLANORDER.COPRODPRIMARYITEM) AS CO_PROD_TYP,
PLANORDER.COVDURSCHEDDATE AS CVRG_DUR_SCHED_DTE,
PLANORDER.EARLIESTSELLDATE AS EARL_SELL_DTE,
case when UPPER(PLANORDER.EDITSW) in ('NO','FALSE','0') or UPPER(PLANORDER.EDITSW) is null
or length(TRIM(PLANORDER.EDITSW))<1 then 'N' when UPPER(PLANORDER.EDITSW) in ('YES','TRUE','1')
then 'Y' else 'U' end as EDIT_PLND_ORD_FLAG,
PLANORDER.EXPDATE AS PLND_ORD_EXPIRY_DTE,
case when UPPER(PLANORDER.FIRMPLANSW) in ('NO','FALSE','0') or UPPER(PLANORDER.FIRMPLANSW) is null
or length(TRIM(PLANORDER.FIRMPLANSW))<1 then 'N' when UPPER(PLANORDER.FIRMPLANSW) in ('YES','TRUE','1')
then 'Y' else 'U' end as FIRM_PLAN_FLAG,
PLANORDER.HEADERSEQNUM AS PLAN_ORD_HDR_SEQ_NBR,
case when length(trim(UPPER((PLANORDER.ITEM)))) <1 then {{var('default_mapkey')}} when UPPER(PLANORDER.ITEM)
IS NULL then {{var('default_mapkey')}} else UPPER(PLANORDER.ITEM) end AS PROD_KEY,
case when length(trim(UPPER((PLANORDER.LOC)))) <1 then {{var('default_mapkey')}} when UPPER(PLANORDER.LOC)
IS NULL then {{var('default_mapkey')}} else UPPER(PLANORDER.LOC) end AS LOC_KEY,
PLANORDER.NEEDDATE AS DMD_FULFIL_DTE,
trim(PLANORDER.ORDERTYPE) AS DMD_ORD_TYP,
PLANORDER.PRIMARYSEQNUM AS PRIM_SEQ_NBR,
PLANORDER.PRIORITY AS PLND_ORD_PRYRT_NBR,
PLANORDER.PRODUCTIONMETHOD AS PRODTN_MTHD_NAME,
PLANORDER.PROJECT AS PROJ_NBR,
PLANORDER.QTY AS PLND_ORD_QTY,
trim(PLANORDER.RECSCHEDRCPTSOPT) AS SCHED_RCPT_OPT,
PLANORDER.REVISEDDATE AS PLAN_REVISED_DTE,
PLANORDER.REVISEDEXPDATE AS PLAN_REVISED_EXPR_DTE,
PLANORDER.SCHEDDATE AS PLND_ORD_MFG_DTE,
PLANORDER.SEQNUM AS PLAN_ORD_SEQ_NBR,
PLANORDER.STARTDATE AS PLND_ORD_START_DTE,
PLANORDER.SUBSTQTY AS ALT_PROD_PLAN_ORD_QTY,
PLANORDER.U_DC_HOLD AS DIST_CNTR_HOLD,
case when UPPER(PLANORDER.U_INTERNAL) in ('NO','FALSE','0') or UPPER(PLANORDER.U_INTERNAL) is null
or length(TRIM(PLANORDER.U_INTERNAL))<1 then 'N' when UPPER(PLANORDER.U_INTERNAL) in ('YES','TRUE','1')
then 'Y' else 'U' end as PROD_PRODUCED_ITRL_FLAG,
PLANORDER.U_PROMO_NAME AS PROMO_NAME,
PLANORDER.U_PROMO_PERCENT AS PROMO_PCT,
trim(PLANORDER.U_PROMO_TYPE) AS PROMO_TYP,
PLANORDER.U_WKLY_EVENT AS WKLY_DMD_PLAN
FROM {{source('JDA','PLANORDER')}} PLANORDER
