select
UPPER(CONCAT(coalesce(RECSHIP.ITEM ::VARCHAR,''),'~',coalesce(RECSHIP.DEST ::VARCHAR,''),'~' ,coalesce(RECSHIP.SEQNUM ::VARCHAR,''),coalesce(RECSHIP.SOURCE::VARCHAR,''),coalesce(RECSHIP.TYPE ::VARCHAR,''))) AS SUPPLY_PLND_RECOMMENDED_SHIP_KEY,
'JDA' AS {{var('column_srcsyskey')}},
MD5(UPPER(CONCAT(coalesce(RECSHIP.ITEM::VARCHAR,''),'~',coalesce(RECSHIP.DEST::VARCHAR,''),'~' ,coalesce(RECSHIP.SEQNUM::VARCHAR,''),coalesce(RECSHIP.SOURCE::VARCHAR,''),coalesce(RECSHIP.TYPE::VARCHAR,'')))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
RECSHIP.LOADDTS AS {{var('column_z3loddtm')}},
RECSHIP.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},


RECSHIP.ACTIONALLOWEDSW AS ALLOC_GRP_ID,

case when length(trim(UPPER((RECSHIP.DEST)))) <1 then {{var('default_mapkey')}} when UPPER(RECSHIP.DEST)
IS NULL then {{var('default_mapkey')}} else UPPER(RECSHIP.DEST) end AS DEST_LOC_KEY,

case when length(trim(UPPER((RECSHIP.ITEM)))) <1 then {{var('default_mapkey')}} when UPPER(RECSHIP.ITEM)
IS NULL then {{var('default_mapkey')}} else UPPER(RECSHIP.ITEM) end AS PROD_KEY,

case when length(trim(UPPER((RECSHIP.PRIMARYITEM)))) <1 then {{var('default_mapkey')}} when UPPER(RECSHIP.PRIMARYITEM)
IS NULL then {{var('default_mapkey')}} else UPPER(RECSHIP.PRIMARYITEM) end AS PRIM_PROD_KEY,

case when length(trim(UPPER((RECSHIP.SOURCE)))) <1 then {{var('default_mapkey')}} when UPPER(RECSHIP.SOURCE)
IS NULL then {{var('default_mapkey')}} else UPPER(RECSHIP.SOURCE) end AS SRC_LOC_KEY,

RECSHIP.TRANSNAME AS FRT_CARRIER_NAME,

RECSHIP.SOURCING AS SOURCING_MTHD,
RECSHIP.SUPPLYMETHOD AS SUPPLY_MTHD,
RECSHIP.SUPPLYSHAPE AS SUPPLY_ALLOC_TYP,
RECSHIP.SUPPLYTYPE AS SUPPLY_TYP,
RECSHIP.TRANSMODE AS TRNSPRT_MODE,
RECSHIP.TYPE AS RECOMMENDED_SHIP_TYP,

case when UPPER(RECSHIP.FIRMSW) in ('NO','FALSE','0') or UPPER(RECSHIP.FIRMSW) is null
or length(TRIM(RECSHIP.FIRMSW))<1 then 'N' when UPPER(RECSHIP.FIRMSW) in ('YES','TRUE','1')
then 'Y' else 'U' end as SHIP_RECOMMENDATION_FIRM_FLAG,

case when UPPER(RECSHIP.MUSTGOSW) in ('NO','FALSE','0') or UPPER(RECSHIP.MUSTGOSW) is null
or length(TRIM(RECSHIP.MUSTGOSW))<1 then 'N' when UPPER(RECSHIP.MUSTGOSW) in ('YES','TRUE','1')
then 'Y' else 'U' end as SHIP_MUST_GO_FLAG,

RECSHIP.AVAILTOSHIPDATE AS AVAIL_FIRST_SHIP_DTE,
RECSHIP.DELIVERYDATE AS DLV_DTE,
RECSHIP.DEPARTUREDATE AS DEPTR_DTE,
RECSHIP.EARLIESTSELLDATE AS EARL_SELL_DTE,
RECSHIP.EXPDATE AS SCHED_SHIP_EXPIRY_DTE,
RECSHIP.NEEDARRIVDATE AS REQ_ARRVL_DTE,
RECSHIP.NEEDSHIPDATE AS REQ_SHIP_DTE,
RECSHIP.ORDERPLACEDATE AS ORD_PLACE_DTE,
RECSHIP.REVISEDDATE AS REVISED_SHIP_DTE,
RECSHIP.SCHEDARRIVDATE AS SCHED_ARRVL_DTE,
RECSHIP.SCHEDSHIPDATE AS SCHED_SHIP_DTE,


RECSHIP.DOSGROUP AS DYS_OF_SUPPLY_GRP_NBR,
RECSHIP.DRAWQTY AS SKU_DRAW_QTY,
RECSHIP.PLANARRIVSEQNUM AS PLND_ARRVL_SEQ_NBR,
RECSHIP.PRIMARYITEMQTY AS PRIM_PROD_QTY,
RECSHIP.PRIORITY AS SHIP_PRYRT_NBR,
RECSHIP.QTY AS SHIP_QTY,
RECSHIP.SEQNUM AS RECOMMENDED_SHIP_SEQ_NBR,
RECSHIP.SUPPORDERID AS SUPL_ORD_NBR,
RECSHIP.SUPPORDERQTY AS SUPL_ORD_QTY,
RECSHIP.U_MANUAL AS MANUAL

FROM {{source('JDA','RECSHIP')}} RECSHIP