SELECT 
IOH.INVTY_ON_HAND_SNAPSHOT_KEY AS INVTY_ON_HAND_SNAPSHOT_KEY,
IOH.SRC_SYS_KEY,
--IOH.SRC_RCRD_CREATE_DTE,
--IOH.SRC_RCRD_CREATE_USERID,
--IOH.SRC_RCRD_UPD_DTE,
--IOH.SRC_RCRD_UPD_USERID,
IOH.RCRD_HASH_KEY,
IOH.DEL_FROM_SRC_FLAG,
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
IOH.EFF_DTE  AS EFF_DTE,
IOH.EXPR_DTE AS EXPR_DTE,IOH.
ETL_UPD_DTE AS ZONE4_ETL_UPD_DTE,
IOH.ETL_INS_PID AS ZONE4_ETL_INS_PID,
IOH.ZONE3_LOD_DTE,
IOH.PROD_KEY AS PROD_KEY,
IOH.SLOC_ID AS LOC_KEY,
IOH.PROD_RCV_DTE AS PROD_RCV_DTE,
IOH.PROD_ADD_LOC_DTE AS PROD_ADD_LOC_DTE,
IOH.REF_WORK_ORD_NBR AS REF_WORK_ORD_NBR,
IOH.PROD_MAX_ORD_QTY AS PROD_MAX_ORD_QTY,
IOH.PROD_ALLOC_QTY AS PROD_ALLOC_QTY,
IOH.PROD_BKORD_QTY AS PROD_BKORD_QTY,
IOH.PROD_MIN_ORD_QTY AS PROD_MIN_ORD_QTY,
COALESCE(IOH.PROD_ON_HAND_QTY,0) AS VALUATED_UNRSTR_STK_QTY,
IOH.PROD_ON_HAND_QTY * (COALESCE(IOH.STD_COST,0)) AS VALUATED_UNRSTR_STK_AMT,
IOH.DIV_ID AS DIV_ID,
IOH.PROD_RCV_YR_ID AS PROD_RCV_YR_ID,
IOH.INVTY_STAT_TYP AS INVTY_STAT_TYP,
IOH.MISC_TYP AS MISC_TYP,
--PL.CNTRY_OF_ORIG_KEY AS ORIG_CNTRY_ID,
--IOH.SLOC_ID AS SLOC_ID,
IOH.STORG_BIN_ID AS STORG_BIN_ID,
IOH.SUB_LOC_TYP AS SUB_LOC_TYP,
IOH.PROD_ADD_LOC_YR_ID AS PROD_ADD_LOC_YR_ID,
IOH.PROD_REL_SET_ITEM AS PROD_REL_SET_ITEM,
COALESCE(IOH.STD_COST,0) AS STANDARD_PRICE,
PL.VALTN_CLS_LKEY AS VALTN_CLASS ,
PL.HFM_CO_LKEY AS CO_KEY,
PL.CRNCY_KEY AS CRNCY_KEY
FROM
(SELECT IOH.*,PC.STD_COST FROM 
(SELECT * FROM {{source('CONSOLIDATED_PROD','EDW_INVENTORY_ON_HAND_SNAPSHOT')}} 
WHERE SRC_SYS_KEY='LAWSONMAC' AND DIV_ID IN ('USM') AND SLOC_ID IN ('COL','ALL') AND SUB_LOC_TYP IN ('SHP') AND STORG_BIN_ID IN ('AVAILABLE','XXXXX') AND PROD_KEY NOT LIKE '%?%') IOH
LEFT JOIN (SELECT STD_COST,SRC_SYS_KEY,PROD_COST_KEY,SRC_RCRD_UPD_DTE,EXPR_DTE FROM {{source('CONSOLIDATED_PROD','EDW_PRODUCT_COST')}}  WHERE SRC_SYS_KEY='LAWSONMAC') PC ON IOH.PROD_KEY=PC.PROD_COST_KEY AND 
IOH.SRC_SYS_KEY= PC.SRC_SYS_KEY AND TO_DATE(IOH.EXPR_DTE)>=TO_DATE(PC.SRC_RCRD_UPD_DTE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY IOH.INVTY_ON_HAND_SNAPSHOT_KEY,IOH.EFF_DTE,IOH.EXPR_DTE,IOH.PROD_ON_HAND_QTY ORDER BY PC.EXPR_DTE DESC) = 1) IOH
LEFT JOIN ((SELECT PL.*,CO.CRNCY_KEY FROM (SELECT LOC_KEY,VALTN_CLS_LKEY,HFM_CO_LKEY,PROD_KEY,CNTRY_OF_ORIG_KEY,SRC_SYS_KEY FROM {{source('CONSOLIDATED_PROD','VW_EDW_PRODUCT_LOCATION')}} 
WHERE SRC_SYS_KEY='LAWSONMAC')PL 
LEFT JOIN (SELECT CO_KEY,CRNCY_KEY,SRC_SYS_KEY FROM {{source('DIMENSIONS','DIM_COMPANY')}} WHERE SRC_SYS_KEY='LAWSONMAC')CO ON CONCAT(PL.SRC_SYS_KEY,'~',PL.HFM_CO_LKEY) = CO.CO_KEY AND 
PL.SRC_SYS_KEY= CO.SRC_SYS_KEY))PL ON IOH.PROD_KEY = PL.PROD_KEY AND CONCAT(IOH.DIV_ID,'~',IOH.SLOC_ID)=PL.LOC_KEY AND IOH.SRC_SYS_KEY= PL.SRC_SYS_KEY