Select
concat(coalesce(cast(MBM.BPROD as string),''),'~',coalesce(cast(MBM.BMWHS as string),''),'~',coalesce(cast(MBM.BMBOMM as string),''),'~',coalesce(cast(MBM.BSEQ as string),'')) AS PROD_BOM_CMPNT_KEY,
'INFORLX' AS {{var('column_srcsyskey')}},
concat(TRY_TO_DATE(round(MBM.BMENDT)::VARCHAR,'YYYYMMDD'),' ',TO_TIME(ROUND(MBM.BMENTM)::VARCHAR)) AS {{var('column_SRC_RCRD_CREATE_DTE')}},
MBM.BMENUS AS	{{var('column_SRC_RCRD_CREATE_USERID')}},
MD5(concat(coalesce(cast(MBM.BPROD as string),''),'~',coalesce(cast(MBM.BMWHS as string),''),'~',coalesce(cast(MBM.BMBOMM as string),''),'~',coalesce(cast(MBM.BSEQ as string),''))) AS {{var('column_rechashkey')}},
{{var('default_n')}} AS {{var('column_DEL_FROM_SRC_FLAG')}},
'{{model.name}}' AS {{var('column_ETL_INS_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS {{var('column_ETL_UPD_PID')}},
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS {{var('column_ETL_UPD_DTE')}},
MBM.LOADDTS AS {{var('column_z3loddtm')}},
MBM.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS {{var('column_currrecflag')}},
{{var('default_n')}} AS {{var('column_orprecflag')}},
case when length(trim(MBM.BMMNUS))<1 then {{var('default_mapkey')}} when MBM.BMMNUS IS NULL then {{var('default_mapkey')}} else (MBM.BMMNUS) end AS LAST_MTNC_USER_KEY,
case when length(trim(MBM.BCLAS))<1 then {{var('default_mapkey')}} when MBM.BCLAS IS NULL then {{var('default_mapkey')}} else (MBM.BCLAS) end AS PROD_CLS_LKEY,
TRY_TO_DATE(round(MBM.BMMNDT)::VARCHAR,'YYYYMMDD') AS LAST_MTNC_DTE,
MBM.BQREQ AS BASE_QTY,
MBM.BSEQ AS SEQ_NBR,
MBM.BID AS RCRD_ID,
MBM.BMWHS AS BOM_WHSE,
MBM.BMBOMM AS MFG_MTHD_PROD_CD,
MBM.BCHLD AS CHILD_ITEM_NBR,
TRY_TO_DATE(round(MBM.BDDIS)::VARCHAR,'YYYYMMDD') AS DSCTU_DTE,
MBM.BCLAC AS CHILD_PROD_CLS,
MBM.BMSCP AS BOM_SCRAP_FACTOR,
MBM.BBUBB AS BUBBLE_NBR,
MBM.BOPNO AS OPER_NBR,
MBM.BLLOT AS LOWER_LOT_NBR,
MBM.BULOT AS UPPER_LOT_NBR,
MBM.BDOFF AS BOM_DYS_OFFSET,
MBM.BCSTP AS CO_PROD_COST_PCT,
MBM.BMISS AS MUST_ISS_OVRD,
MBM.BUSC AS CMPNT_USAGE_CD,
MBM.BMREOP AS REUSE_OPER,
MBM.BMBDC AS BOUNDED_DISPOSITION_CD,
MBM.BMOFAC AS ORIG_ORD_FAC,
MBM.BMORDT AS ORD_TYP,
MBM.BMECN AS ENGNR_CHG_NBR,
MBM.BMLINE AS ECN_ORD_LN_NBR,
CASE WHEN MBM.BMRDF = '1' THEN 'Y' ELSE 'N' END AS REF_DESIGNATORS_FLAG,
MBM.BMCFAC AS FUTR_CMPNT_FAC,
concat(TRY_TO_DATE(round(MBM.BMMNDT)::VARCHAR,'YYYYMMDD'),' ',TO_TIME(ROUND(MBM.BMMNTM)::VARCHAR)) AS LAST_MTNC_TM,
concat(TRY_TO_DATE(round(MBM.BDEFF)::VARCHAR,'YYYYMMDD'),' ',TO_TIME(ROUND(MBM.BMEFTM)::VARCHAR)) AS PROD_EFF_TM,
MBM.BMEFTZ AS PROD_EFF_TM_ZONE,
concat(TRY_TO_DATE(round(MBM.BDDIS)::VARCHAR,'YYYYMMDD'),' ',TO_TIME(ROUND(MBM.BMDDTM)::VARCHAR)) AS PROD_DSCTU_TM,
MBM.BMDDTZ AS PROD_DSCTU_TM_ZONE,
MBM.BMENTZ AS TM_ZONE_CREATE,
MBM.BMMNTZ AS TM_ZONE_LAST_CHG,
MBM.BMMNPG AS LAST_MTNC_PGM,
MBM.BMEXCM AS EXPR_CMPNT,
MBM.BMAUTO AS AUTO_RCV_CO_PROD,
MBM.BMLOT AS FIXED_LOT_NBR,
MBM.BMEXCS AS EXCL_COST,
MBM.BMEXPL AS EXCL_PLNG,
case when length(trim(MBM.BPROD))<1 then {{var('default_mapkey')}} when MBM.BPROD IS NULL then {{var('default_mapkey')}} else (MBM.BPROD) end AS PROD_KEY,
TRY_TO_DATE(round(MBM.BDEFF)::VARCHAR,'YYYYMMDD') AS BOM_EFF_DTE
FROM {{source('INFORLX','MBM')}} MBM 