version: 2

sources:
 
  - name: QADDE
    schema: QADDE
    database:  "{% if target.database == 'DEV_EDW' -%} 
    PROD_RAW{% elif target.database == 'TEST_EDW' -%} 
    PROD_RAW{% elif target.database == 'PROD_EDW' -%} 
    PROD_RAW{% elif target.database == 'UAT_EDW' -%}UAT_RAW
                 {% else -%} INVALID_DATABASE{% endif -%}"
    tables:
      - name: PTPDET
        identifier: VW_PTPDET
      - name: PSMSTR
        identifier: VW_PSMSTR