SELECT  
--UPPER(concat(COALESCE(trim(ITMRVB.STID)::VARCHAR,''),'~',COALESCE(trim(ITMRVB.ITNBR)::VARCHAR,''),'~',COALESCE(trim(ITMRVB.ITRV)::VARCHAR,''))) AS PROD_KEY,
UPPER(concat(COALESCE(trim(ITMRVB.STID)::VARCHAR,''),'~',COALESCE(trim(ITMRVB.ITNBR)::VARCHAR,''))) AS PROD_KEY,
'INFORXA' AS SRC_SYS_KEY,  
md5 (UPPER(concat(COALESCE(trim(ITMRVB.STID)::VARCHAR,''),'~',COALESCE(trim(ITMRVB.ITNBR)::VARCHAR,'')))) AS RCRD_HASH_KEY,
NULL AS {{var('column_SRC_RCRD_CREATE_DTE')}},
NULL AS {{var('column_SRC_RCRD_CREATE_USERID')}},
NULL AS {{var('column_SRC_RCRD_UPD_DTE')}},
NULL AS {{var('column_SRC_RCRD_UPD_USERID')}},
{{var('default_n')}} AS  {{var('column_DEL_FROM_SRC_FLAG')}},  
'{{model.name}}' AS  {{var('column_ETL_INS_PID')}},  
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_INS_DTE')}},
'{{model.name}}' AS  {{var('column_ETL_UPD_PID')}},  
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS  {{var('column_ETL_UPD_DTE')}},
ITMRVB.LOADDTS AS {{var('column_vereffdte')}},
'9999-12-31 00:00:00.000' AS {{var('column_verexpirydt')}},
{{var('default_y')}} AS  {{var('column_currrecflag')}},                                                                                    
{{var('default_n')}} AS  {{var('column_orprecflag')}},
ITMRVB.LOADDTS AS {{var('column_z3loddtm')}},
--ITMRVB.SITE AS LOC_KEY,
ITMRVB.DLCS AS COST_LAST_CHG_DTE,
ITMRVB.SMAT AS DIR_MATL_COST_AMT,
ITMRVB.SPOT AS INDIR_MATL_COST_AMT,
ITMRVB.SOOT AS OTHER_MATL_COST_AMT,
ITMRVB.SRLT AS DIR_LABR_COST_AMT,
ITMRVB.SSLT AS INDIR_LABR_COST_AMT,
ITMRVB.SOHT AS DIR_OVHD_COST_AMT
from {{source('INFORXA','ITMRVB')}} ITMRVB