with 
IMHISTAUS AS(
select upper(concat(coalesce(trim(IMHISTA.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTA.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTA.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTA.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTA.PSTMAV)::varchar, ''),'~','IMHIST_AUS')) as INVTY_MVMNT_LN_KEY,
'INFORXA' as SRC_SYS_KEY,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTA.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTA.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTA.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTA.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTA.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTA.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
md5(upper(concat(coalesce(trim(IMHISTA.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTA.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTA.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTA.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTA.PSTMAV)::varchar, ''),'~','IMHIST_AUS'))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
IMHISTA.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
IMHISTA.loaddts as ZONE3_LOD_DTE,
--IMHISTA.ACREC AS CURR_RCRD_FLAG,
IMHISTA.TRQTY AS PUR_DLV_QTY,
IMHISTA.LBHNO AS BATCH_NBR_LKEY,
IMHISTA.ITNBR AS PROD_KEY,
IMHISTA.TRQTY AS ACCT_ASGN_PROD_QTY,
IMHISTA.TCODE AS MVMNT_TYP_LKEY,
CONCAT('AUS','~',IMHISTA.HOUSE) AS LOC_KEY,
IMHISTA.TCODE AS TXN_TYP_LKEY,
--IMHISTA.TRNDT AS PROD_MVMNT_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTA.TRNDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTA.TRNDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTA.TRNDT), 7, 0), 6, 2)))) as PROD_MVMNT_DTE,
IMHISTA.HOUSE AS WHSE_NBR,
IMHISTA.BADGE AS EMP_ID_NBR,
IMHISTA.REASN AS RESN_CD_LKEY,
IMHISTA.TRQTY AS CUML_RCV_QTY,
IMHISTA.VNDNR AS VEND_TO_ID,
IMHISTA.LLOCN AS SLOC_ID 
FROM {{source('INFORXA','IMHISTAUS')}} IMHISTA),
--###########################################################################
IMHISTBRN AS(
select upper(concat(coalesce(trim(IMHISTB.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTB.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTB.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTB.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTB.PSTMAV)::varchar, ''),'~','IMHIST_BRN')) as INVTY_MVMNT_LN_KEY,
'INFORXA' as SRC_SYS_KEY,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTB.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTB.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTB.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTB.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTB.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTB.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
md5(upper(concat(coalesce(trim(IMHISTB.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTB.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTB.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTB.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTB.PSTMAV)::varchar, ''),'~','IMHIST_BRN'))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
IMHISTB.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
IMHISTB.loaddts as ZONE3_LOD_DTE,
--IMHISTA.ACREC AS CURR_RCRD_FLAG,
IMHISTB.TRQTY AS PUR_DLV_QTY,
IMHISTB.LBHNO AS BATCH_NBR_LKEY,
IMHISTB.ITNBR AS PROD_KEY,
IMHISTB.TRQTY AS ACCT_ASGN_PROD_QTY,
IMHISTB.TCODE AS MVMNT_TYP_LKEY,
CONCAT('BRN','~',IMHISTB.HOUSE) AS LOC_KEY,
IMHISTB.TCODE AS TXN_TYP_LKEY,
--IMHISTA.TRNDT AS PROD_MVMNT_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTB.TRNDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTB.TRNDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTB.TRNDT), 7, 0), 6, 2)))) as PROD_MVMNT_DTE,
IMHISTB.HOUSE AS WHSE_NBR,
IMHISTB.BADGE AS EMP_ID_NBR,
IMHISTB.REASN AS RESN_CD_LKEY,
IMHISTB.TRQTY AS CUML_RCV_QTY,
IMHISTB.VNDNR AS VEND_TO_ID,
IMHISTB.LLOCN AS SLOC_ID 
FROM {{source('INFORXA','IMHISTBRN')}} IMHISTB),
----###############################################################################
IMHISTCANS AS(
select upper(concat(coalesce(trim(IMHISTC.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTC.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTC.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTC.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTC.PSTMAV)::varchar, ''),'~','IMHIST_CANS')) as INVTY_MVMNT_LN_KEY,
'INFORXA' as SRC_SYS_KEY,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTC.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTC.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTC.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTC.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTC.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTC.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
md5(upper(concat(coalesce(trim(IMHISTC.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTC.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTC.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTC.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTC.PSTMAV)::varchar, ''),'~','IMHIST_CANS'))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
IMHISTC.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
IMHISTC.loaddts as ZONE3_LOD_DTE,
--IMHISTA.ACREC AS CURR_RCRD_FLAG,
IMHISTC.TRQTY AS PUR_DLV_QTY,
IMHISTC.LBHNO AS BATCH_NBR_LKEY,
IMHISTC.ITNBR AS PROD_KEY,
IMHISTC.TRQTY AS ACCT_ASGN_PROD_QTY,
IMHISTC.TCODE AS MVMNT_TYP_LKEY,
CONCAT('CANS','~',IMHISTC.HOUSE) AS LOC_KEY,
IMHISTC.TCODE AS TXN_TYP_LKEY,
--IMHISTA.TRNDT AS PROD_MVMNT_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTC.TRNDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTC.TRNDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTC.TRNDT), 7, 0), 6, 2)))) as PROD_MVMNT_DTE,
IMHISTC.HOUSE AS WHSE_NBR,
IMHISTC.BADGE AS EMP_ID_NBR,
IMHISTC.REASN AS RESN_CD_LKEY,
IMHISTC.TRQTY AS CUML_RCV_QTY,
IMHISTC.VNDNR AS VEND_TO_ID,
IMHISTC.LLOCN AS SLOC_ID 
FROM {{source('INFORXA','IMHISTCANS')}} IMHISTC),
--########################################################################
IMHISTCANW AS(
select upper(concat(coalesce(trim(IMHISTD.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTD.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTD.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTD.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTD.PSTMAV)::varchar, ''),'~','IMHIST_CANW')) as INVTY_MVMNT_LN_KEY,
'INFORXA' as SRC_SYS_KEY,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTD.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTD.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTD.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTD.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTD.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTD.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
md5(upper(concat(coalesce(trim(IMHISTD.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTD.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTD.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTD.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTD.PSTMAV)::varchar, ''),'~','IMHIST_CANW'))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
IMHISTD.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
IMHISTD.loaddts as ZONE3_LOD_DTE,
--IMHISTA.ACREC AS CURR_RCRD_FLAG,
IMHISTD.TRQTY AS PUR_DLV_QTY,
IMHISTD.LBHNO AS BATCH_NBR_LKEY,
IMHISTD.ITNBR AS PROD_KEY,
IMHISTD.TRQTY AS ACCT_ASGN_PROD_QTY,
IMHISTD.TCODE AS MVMNT_TYP_LKEY,
CONCAT('CANW','~',IMHISTD.HOUSE) AS LOC_KEY,
IMHISTD.TCODE AS TXN_TYP_LKEY,
--IMHISTA.TRNDT AS PROD_MVMNT_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTD.TRNDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTD.TRNDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTD.TRNDT), 7, 0), 6, 2)))) as PROD_MVMNT_DTE,
IMHISTD.HOUSE AS WHSE_NBR,
IMHISTD.BADGE AS EMP_ID_NBR,
IMHISTD.REASN AS RESN_CD_LKEY,
IMHISTD.TRQTY AS CUML_RCV_QTY,
IMHISTD.VNDNR AS VEND_TO_ID,
IMHISTD.LLOCN AS SLOC_ID 
FROM {{source('INFORXA','IMHISTCANW')}} IMHISTD),
--########################################################################
IMHISTCHI AS(
select upper(concat(coalesce(trim(IMHISTE.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTE.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTE.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTE.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTE.PSTMAV)::varchar, ''),'~','IMHIST_CHI')) as INVTY_MVMNT_LN_KEY,
'INFORXA' as SRC_SYS_KEY,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTE.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTE.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTE.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTE.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTE.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTE.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
md5(upper(concat(coalesce(trim(IMHISTE.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTE.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTE.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTE.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTE.PSTMAV)::varchar, ''),'~','IMHIST_CHI'))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
IMHISTE.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
IMHISTE.loaddts as ZONE3_LOD_DTE,
--IMHISTA.ACREC AS CURR_RCRD_FLAG,
IMHISTE.TRQTY AS PUR_DLV_QTY,
IMHISTE.LBHNO AS BATCH_NBR_LKEY,
IMHISTE.ITNBR AS PROD_KEY,
IMHISTE.TRQTY AS ACCT_ASGN_PROD_QTY,
IMHISTE.TCODE AS MVMNT_TYP_LKEY,
CONCAT('CHI','~',IMHISTE.HOUSE) AS LOC_KEY,
IMHISTE.TCODE AS TXN_TYP_LKEY,
--IMHISTA.TRNDT AS PROD_MVMNT_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTE.TRNDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTE.TRNDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTE.TRNDT), 7, 0), 6, 2)))) as PROD_MVMNT_DTE,
IMHISTE.HOUSE AS WHSE_NBR,
IMHISTE.BADGE AS EMP_ID_NBR,
IMHISTE.REASN AS RESN_CD_LKEY,
IMHISTE.TRQTY AS CUML_RCV_QTY,
IMHISTE.VNDNR AS VEND_TO_ID,
IMHISTE.LLOCN AS SLOC_ID 
FROM {{source('INFORXA','IMHISTCHI')}} IMHISTE),
--########################################################################
IMHISTLEI AS(
select upper(concat(coalesce(trim(IMHISTF.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTF.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTF.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTF.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTF.PSTMAV)::varchar, ''),'~','IMHIST_LEI')) as INVTY_MVMNT_LN_KEY,
'INFORXA' as SRC_SYS_KEY,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTF.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTF.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTF.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTF.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTF.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTF.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
md5(upper(concat(coalesce(trim(IMHISTF.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTF.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTF.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTF.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTF.PSTMAV)::varchar, ''),'~','IMHIST_LEI'))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
IMHISTF.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
IMHISTF.loaddts as ZONE3_LOD_DTE,
--IMHISTA.ACREC AS CURR_RCRD_FLAG,
IMHISTF.TRQTY AS PUR_DLV_QTY,
IMHISTF.LBHNO AS BATCH_NBR_LKEY,
IMHISTF.ITNBR AS PROD_KEY,
IMHISTF.TRQTY AS ACCT_ASGN_PROD_QTY,
IMHISTF.TCODE AS MVMNT_TYP_LKEY,
CONCAT('LEI','~',IMHISTF.HOUSE) AS LOC_KEY,
IMHISTF.TCODE AS TXN_TYP_LKEY,
--IMHISTA.TRNDT AS PROD_MVMNT_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTF.TRNDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTF.TRNDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTF.TRNDT), 7, 0), 6, 2)))) as PROD_MVMNT_DTE,
IMHISTF.HOUSE AS WHSE_NBR,
IMHISTF.BADGE AS EMP_ID_NBR,
IMHISTF.REASN AS RESN_CD_LKEY,
IMHISTF.TRQTY AS CUML_RCV_QTY,
IMHISTF.VNDNR AS VEND_TO_ID,
IMHISTF.LLOCN AS SLOC_ID 
FROM {{source('INFORXA','IMHISTLEI')}} IMHISTF),
--########################################################################
IMHISTMAR AS(
select upper(concat(coalesce(trim(IMHISTG.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTG.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTG.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTG.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTG.PSTMAV)::varchar, ''),'~','IMHIST_MAR')) as INVTY_MVMNT_LN_KEY,
'INFORXA' as SRC_SYS_KEY,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTG.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTG.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTG.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTG.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTG.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTG.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
md5(upper(concat(coalesce(trim(IMHISTG.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTG.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTG.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTG.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTG.PSTMAV)::varchar, ''),'~','IMHIST_MAR'))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
IMHISTG.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
IMHISTG.loaddts as ZONE3_LOD_DTE,
--IMHISTA.ACREC AS CURR_RCRD_FLAG,
IMHISTG.TRQTY AS PUR_DLV_QTY,
IMHISTG.LBHNO AS BATCH_NBR_LKEY,
IMHISTG.ITNBR AS PROD_KEY,
IMHISTG.TRQTY AS ACCT_ASGN_PROD_QTY,
IMHISTG.TCODE AS MVMNT_TYP_LKEY,
CONCAT('MAR','~',IMHISTG.HOUSE) AS LOC_KEY,
IMHISTG.TCODE AS TXN_TYP_LKEY,
--IMHISTA.TRNDT AS PROD_MVMNT_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTG.TRNDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTG.TRNDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTG.TRNDT), 7, 0), 6, 2)))) as PROD_MVMNT_DTE,
IMHISTG.HOUSE AS WHSE_NBR,
IMHISTG.BADGE AS EMP_ID_NBR,
IMHISTG.REASN AS RESN_CD_LKEY,
IMHISTG.TRQTY AS CUML_RCV_QTY,
IMHISTG.VNDNR AS VEND_TO_ID,
IMHISTG.LLOCN AS SLOC_ID 
FROM {{source('INFORXA','IMHISTMAR')}} IMHISTG),
--########################################################################
--########################################################################
IMHISTRVI AS(
select upper(concat(coalesce(trim(IMHISTH.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTH.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTH.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTH.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTH.PSTMAV)::varchar, ''),'~','IMHIST_RVI')) as INVTY_MVMNT_LN_KEY,
'INFORXA' as SRC_SYS_KEY,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTH.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTH.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTH.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTH.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTH.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTH.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
md5(upper(concat(coalesce(trim(IMHISTH.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTH.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTH.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTH.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTH.PSTMAV)::varchar, ''),'~','IMHIST_RVI'))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
IMHISTH.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
IMHISTH.loaddts as ZONE3_LOD_DTE,
--IMHISTA.ACREC AS CURR_RCRD_FLAG,
IMHISTH.TRQTY AS PUR_DLV_QTY,
IMHISTH.LBHNO AS BATCH_NBR_LKEY,
IMHISTH.ITNBR AS PROD_KEY,
IMHISTH.TRQTY AS ACCT_ASGN_PROD_QTY,
IMHISTH.TCODE AS MVMNT_TYP_LKEY,
CONCAT('RVI','~',IMHISTH.HOUSE) AS LOC_KEY,
IMHISTH.TCODE AS TXN_TYP_LKEY,
--IMHISTA.TRNDT AS PROD_MVMNT_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTH.TRNDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTH.TRNDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTH.TRNDT), 7, 0), 6, 2)))) as PROD_MVMNT_DTE,
IMHISTH.HOUSE AS WHSE_NBR,
IMHISTH.BADGE AS EMP_ID_NBR,
IMHISTH.REASN AS RESN_CD_LKEY,
IMHISTH.TRQTY AS CUML_RCV_QTY,
IMHISTH.VNDNR AS VEND_TO_ID,
IMHISTH.LLOCN AS SLOC_ID 
FROM {{source('INFORXA','IMHISTRVI')}} IMHISTH),
--########################################################################
IMHISTSHB AS(
select upper(concat(coalesce(trim(IMHISTJ.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTJ.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTJ.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTJ.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTJ.PSTMAV)::varchar, ''),'~','IMHIST_SHB')) as INVTY_MVMNT_LN_KEY,
'INFORXA' as SRC_SYS_KEY,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTJ.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTJ.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTJ.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTJ.UPDDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTJ.UPDDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTJ.UPDDT), 7, 0), 6, 2)))) as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
md5(upper(concat(coalesce(trim(IMHISTJ.ITNBR)::varchar, ''),'~',
                    coalesce(trim(IMHISTJ.HOUSE)::varchar, ''),'~',
                    coalesce(trim(IMHISTJ.TAID)::varchar, ''),'~',
                    coalesce(trim(IMHISTJ.TCODE)::varchar, ''),'~',
                    coalesce(trim(IMHISTJ.PSTMAV)::varchar, ''),'~','IMHIST_SHB'))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_MOVEMENT_LINE_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE, ---
IMHISTJ.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
IMHISTJ.loaddts as ZONE3_LOD_DTE,
--IMHISTA.ACREC AS CURR_RCRD_FLAG,
IMHISTJ.TRQTY AS PUR_DLV_QTY,
IMHISTJ.LBHNO AS BATCH_NBR_LKEY,
IMHISTJ.ITNBR AS PROD_KEY,
IMHISTJ.TRQTY AS ACCT_ASGN_PROD_QTY,
IMHISTJ.TCODE AS MVMNT_TYP_LKEY,
CONCAT('SHB','~',IMHISTJ.HOUSE) AS LOC_KEY,
IMHISTJ.TCODE AS TXN_TYP_LKEY,
--IMHISTA.TRNDT AS PROD_MVMNT_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(IMHISTJ.TRNDT), 7, 0), 3),'-',substring(lpad(trim(IMHISTJ.TRNDT), 7, 0), 4, 2),'-',substring(lpad(trim(IMHISTJ.TRNDT), 7, 0), 6, 2)))) as PROD_MVMNT_DTE,
IMHISTJ.HOUSE AS WHSE_NBR,
IMHISTJ.BADGE AS EMP_ID_NBR,
IMHISTJ.REASN AS RESN_CD_LKEY,
IMHISTJ.TRQTY AS CUML_RCV_QTY,
IMHISTJ.VNDNR AS VEND_TO_ID,
IMHISTJ.LLOCN AS SLOC_ID 
FROM {{source('INFORXA','IMHISTSHB')}} IMHISTJ)
--########################################################################
select * from IMHISTAUS
UNION
select * from IMHISTBRN
UNION
select * from IMHISTCANS
UNION
select * from IMHISTCANW
UNION
select * from IMHISTCHI
UNION
select * from IMHISTMAR
UNION
select * from IMHISTRVI
UNION
select * from IMHISTSHB
UNION
select * from IMHISTLEI