 with 
SLQNTY_AUS AS(
select upper(concat('AUS','~',
                    coalesce(trim(SLQNTYB.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYB.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYB.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('AUS','~',
                     coalesce(trim(SLQNTYB.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYB.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYB.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYB.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYB.loaddts as ZONE3_LOD_DTE,
--SLQNTYB.ACREC as CURR_RCRD_FLAG,
SLQNTYB.LLOCN as MRP_SLOC_LKEY,
SLQNTYB.LLOCN as SLOC_NAME,
--SLQNTYB.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYB.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYB.FDATE), 7, 0)
, 4, 2),'-',substring(lpad(trim(SLQNTYB.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYB.ORDNO as PROD_ORD_NBR,
SLQNTYB.HOUSE as WHSE_NAME,
SLQNTYB.LQNTY as WHSE_PROD_CNT,
SLQNTYB.HOUSE as PLANT_LOC_NAME,
SLQNTYB.LLOCN as SLOC_ID from {{source('INFORXA','SLQNTY_AUS')}} SLQNTYB),
--###################################################################################################
SLQNTY_CHI AS(
select upper(concat('CHI','~',
                    coalesce(trim(SLQNTYC.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYC.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYC.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('CHI','~',
                     coalesce(trim(SLQNTYC.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYC.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYC.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYC.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYC.loaddts as ZONE3_LOD_DTE,
--SLQNTYC.ACREC as CURR_RCRD_FLAG,
SLQNTYC.LLOCN as MRP_SLOC_LKEY,
SLQNTYC.LLOCN as SLOC_NAME,
--SLQNTYC.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYC.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYC.FDATE), 7, 0), 4, 2),'-',substring(lpad(trim(SLQNTYC.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYC.ORDNO as PROD_ORD_NBR,
SLQNTYC.HOUSE as WHSE_NAME,
SLQNTYC.LQNTY as WHSE_PROD_CNT,
SLQNTYC.HOUSE as PLANT_LOC_NAME,
SLQNTYC.LLOCN as SLOC_ID 
from {{source('INFORXA','SLQNTY_CHI')}} SLQNTYC),
-- --###################################################################################################
 SLQNTY_GER AS(
select upper(concat('GER','~',
                    coalesce(trim(SLQNTYD.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYD.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYD.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('GER','~',
                     coalesce(trim(SLQNTYD.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYD.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYD.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYD.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYD.loaddts as ZONE3_LOD_DTE,
--SLQNTYD.ACREC as CURR_RCRD_FLAG,
SLQNTYD.LLOCN as MRP_SLOC_LKEY,
SLQNTYD.LLOCN as SLOC_NAME,
--SLQNTYD.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYD.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYD.FDATE), 7, 0), 4, 2),'-',substring(lpad(trim(SLQNTYD.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYD.ORDNO as PROD_ORD_NBR,
SLQNTYD.HOUSE as WHSE_NAME,
SLQNTYD.LQNTY as WHSE_PROD_CNT,
SLQNTYD.HOUSE as PLANT_LOC_NAME,
SLQNTYD.LLOCN as SLOC_ID 
from {{source('INFORXA','SLQNTY_GER')}} SLQNTYD),
 --##################################################################################################
 SLQNTY_MAR AS(
select upper(concat('MAR','~',
                    coalesce(trim(SLQNTYE.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYE.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYE.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('MAR','~',
                     coalesce(trim(SLQNTYE.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYE.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYE.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYE.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYE.loaddts as ZONE3_LOD_DTE,
--SLQNTYE.ACREC as CURR_RCRD_FLAG,
SLQNTYE.LLOCN as MRP_SLOC_LKEY,
SLQNTYE.LLOCN as SLOC_NAME,
--SLQNTYE.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYE.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYE.FDATE), 7, 0), 4, 2),'-',substring(lpad(trim(SLQNTYE.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYE.ORDNO as PROD_ORD_NBR,
SLQNTYE.HOUSE as WHSE_NAME,
SLQNTYE.LQNTY as WHSE_PROD_CNT,
SLQNTYE.HOUSE as PLANT_LOC_NAME,
SLQNTYE.LLOCN as SLOC_ID 
from {{source('INFORXA','SLQNTY_MAR')}} SLQNTYE),
--################################################################################################
 SLQNTY_MEC AS(
select upper(concat('MEC','~',
                    coalesce(trim(SLQNTYF.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYF.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYF.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('MEC','~',
                     coalesce(trim(SLQNTYF.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYF.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYF.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYF.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYF.loaddts as ZONE3_LOD_DTE,
--SLQNTYF.ACREC as CURR_RCRD_FLAG,
SLQNTYF.LLOCN as MRP_SLOC_LKEY,
SLQNTYF.LLOCN as SLOC_NAME,
--SLQNTYF.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYF.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYF.FDATE), 7, 0), 4, 2),'-',substring(lpad(trim(SLQNTYF.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYF.ORDNO as PROD_ORD_NBR,
SLQNTYF.HOUSE as WHSE_NAME,
SLQNTYF.LQNTY as WHSE_PROD_CNT,
SLQNTYF.HOUSE as PLANT_LOC_NAME,
SLQNTYF.LLOCN as SLOC_ID 
from {{source('INFORXA','SLQNTY_MEC')}} SLQNTYF),
--######################################################################################
 SLQNTY_MTDSW AS(
select upper(concat('MTDSW','~',
                    coalesce(trim(SLQNTYG.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYG.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYG.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('MTDSW','~',
                     coalesce(trim(SLQNTYG.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYG.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYG.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYG.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYG.loaddts as ZONE3_LOD_DTE,
--SLQNTYG.ACREC as CURR_RCRD_FLAG,
SLQNTYG.LLOCN as MRP_SLOC_LKEY,
SLQNTYG.LLOCN as SLOC_NAME,
--SLQNTYG.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYG.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYG.FDATE), 7, 0), 4, 2),'-',substring(lpad(trim(SLQNTYG.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYG.ORDNO as PROD_ORD_NBR,
SLQNTYG.HOUSE as WHSE_NAME,
SLQNTYG.LQNTY as WHSE_PROD_CNT,
SLQNTYG.HOUSE as PLANT_LOC_NAME,
SLQNTYG.LLOCN as SLOC_ID 
from {{source('INFORXA','SLQNTY_MTDSW')}} SLQNTYG),
--######################################################################################
 SLQNTY_RVI AS(
select upper(concat('RVI','~',
                    coalesce(trim(SLQNTYH.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYH.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYH.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('RVI','~',
                     coalesce(trim(SLQNTYH.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYH.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYH.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYH.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYH.loaddts as ZONE3_LOD_DTE,
--SLQNTYH.ACREC as CURR_RCRD_FLAG,
SLQNTYH.LLOCN as MRP_SLOC_LKEY,
SLQNTYH.LLOCN as SLOC_NAME,
--SLQNTYH.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYH.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYH.FDATE), 7, 0), 4, 2),'-',substring(lpad(trim(SLQNTYH.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYH.ORDNO as PROD_ORD_NBR,
SLQNTYH.HOUSE as WHSE_NAME,
SLQNTYH.LQNTY as WHSE_PROD_CNT,
SLQNTYH.HOUSE as PLANT_LOC_NAME,
SLQNTYH.LLOCN as SLOC_ID 
from {{source('INFORXA','SLQNTY_RVI')}} SLQNTYH),
--######################################################################################
SLQNTY_SHB AS(
select upper(concat('SHB','~',
                    coalesce(trim(SLQNTYI.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYI.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYI.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('SHB','~',
                     coalesce(trim(SLQNTYI.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYI.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYI.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYI.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYI.loaddts as ZONE3_LOD_DTE,
--SLQNTYI.ACREC as CURR_RCRD_FLAG,
SLQNTYI.LLOCN as MRP_SLOC_LKEY,
SLQNTYI.LLOCN as SLOC_NAME,
--SLQNTYI.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYI.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYI.FDATE), 7, 0), 4, 2),'-',substring(lpad(trim(SLQNTYI.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYI.ORDNO as PROD_ORD_NBR,
SLQNTYI.HOUSE as WHSE_NAME,
SLQNTYI.LQNTY as WHSE_PROD_CNT,
SLQNTYI.HOUSE as PLANT_LOC_NAME,
SLQNTYI.LLOCN as SLOC_ID 
from {{source('INFORXA','SLQNTY_SHB')}} SLQNTYI),
--######################################################################################
SLQNTY_TUP AS(
select upper(concat('TUP','~',
                    coalesce(trim(SLQNTYJ.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYJ.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYJ.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('TUP','~',
                     coalesce(trim(SLQNTYJ.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYJ.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYJ.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYJ.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYJ.loaddts as ZONE3_LOD_DTE,
--SLQNTYJ.ACREC as CURR_RCRD_FLAG,
SLQNTYJ.LLOCN as MRP_SLOC_LKEY,
SLQNTYJ.LLOCN as SLOC_NAME,
--SLQNTYJ.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYJ.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYJ.FDATE), 7, 0), 4, 2),'-',substring(lpad(trim(SLQNTYJ.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYJ.ORDNO as PROD_ORD_NBR,
SLQNTYJ.HOUSE as WHSE_NAME,
SLQNTYJ.LQNTY as WHSE_PROD_CNT,
SLQNTYJ.HOUSE as PLANT_LOC_NAME,
SLQNTYJ.LLOCN as SLOC_ID 
from {{source('INFORXA','SLQNTY_TUP')}} SLQNTYJ),
--################################################################################
SLQNTY_WIL AS(
select upper(concat('WIL','~',
                    coalesce(trim(SLQNTYK.HOUSE)::varchar, ''),'~',
                    coalesce(trim(SLQNTYK.LLOCN)::varchar, ''),'~',
                    coalesce(trim(SLQNTYK.ITNBR)::varchar, ''))) as INVTY_SLOC_KEY,
'INFORXA' as SRC_SYS_KEY,
null as SRC_RCRD_CREATE_DTE,
null as SRC_RCRD_CREATE_USERID,
null as SRC_RCRD_UPD_DTE,
null as SRC_RCRD_UPD_USERID,
 md5(upper(concat('WIL','~',
                     coalesce(trim(SLQNTYK.HOUSE)::varchar, ''),'~',
                     coalesce(trim(SLQNTYK.LLOCN)::varchar, ''),'~',
                     coalesce(trim(SLQNTYK.ITNBR)::varchar, '')))) as RCRD_HASH_KEY,
'N' as DEL_FROM_SRC_FLAG,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_INS_PID,
current_timestamp::timestamp_ntz as ETL_INS_DTE,
'EDW_INFORXA_INVENTORY_STORAGE_LOCATION_VW' as ETL_UPD_PID,
current_timestamp::timestamp_ntz as ETL_UPD_DTE,
SLQNTYK.loaddts as EFF_DTE,
'9999-12-31 00:00:00.000' as EXPR_DTE,
'Y' as CURR_RCRD_FLAG,
'N' as ORP_RCRD_FLAG,
SLQNTYK.loaddts as ZONE3_LOD_DTE,
--SLQNTYK.ACREC as CURR_RCRD_FLAG,
SLQNTYK.LLOCN as MRP_SLOC_LKEY,
SLQNTYK.LLOCN as SLOC_NAME,
--SLQNTYK.FDATE as RCRD_PROC_DTE,
dateadd(year,1900,try_to_date(concat(left(lpad(trim(SLQNTYK.FDATE), 7, 0), 3),'-',substring(lpad(trim(SLQNTYK.FDATE), 7, 0), 4, 2),'-',substring(lpad(trim(SLQNTYK.FDATE), 7, 0), 6, 2)))) as RCRD_PROC_DTE,
SLQNTYK.ORDNO as PROD_ORD_NBR,
SLQNTYK.HOUSE as WHSE_NAME,
SLQNTYK.LQNTY as WHSE_PROD_CNT,
SLQNTYK.HOUSE as PLANT_LOC_NAME,
SLQNTYK.LLOCN as SLOC_ID 
from {{source('INFORXA','SLQNTY_WIL')}} SLQNTYK),
--############################################################################
SLQNTY AS (
select * from SLQNTY_AUS
union 
select * from SLQNTY_CHI
union 
select * from SLQNTY_GER
union 
select * from SLQNTY_MAR
union 
select * from SLQNTY_MEC
union 
select * from SLQNTY_MTDSW
union 
select * from SLQNTY_RVI
union 
select * from SLQNTY_SHB
union 
select * from SLQNTY_TUP
union 
select * from SLQNTY_WIL
)
SELECT * FROM SLQNTY